export type LabelCategory =
  | "ACTION"
  | "ANIMAL"
  | "ARTS"
  | "BODY"
  | "CHARACTER"
  | "CLOTHING"
  | "CONCEPT"
  | "ELECTRONICS"
  | "EVENT"
  | "FOOD"
  | "FURNITURE"
  | "IMAGE"
  | "MATERIAL"
  | "NATURE"
  | "OBJECT"
  | "PEOPLE"
  | "PLACE"
  | "PLANT"
  | "SPACE"
  | "SPORTS"
  | "VEHICLE"
  | "WEATHER";

export type MlkitLabel = { en: string; ja: string; category: LabelCategory };

export function labelText(label: MlkitLabel, uiLocale: string): string {
  return uiLocale === "ja" ? label.ja : label.en;
}

export const MLKIT_LABELS: Readonly<Record<number, MlkitLabel>> = {
  0: { en: "Team", ja: "チーム", category: "PEOPLE" },
  1: { en: "Bonfire", ja: "たき火", category: "NATURE" },
  2: { en: "Comics", ja: "漫画", category: "ARTS" },
  3: { en: "Himalayan", ja: "ヒマラヤン（猫の品種）", category: "ANIMAL" },
  4: { en: "Iceberg", ja: "氷山", category: "NATURE" },
  5: { en: "Bento", ja: "弁当", category: "FOOD" },
  7: { en: "Sink", ja: "流し台・洗面台", category: "FURNITURE" },
  8: { en: "Toy", ja: "おもちゃ", category: "OBJECT" },
  9: { en: "Statue", ja: "像・彫像", category: "ARTS" },
  10: { en: "Cheeseburger", ja: "チーズバーガー", category: "FOOD" },
  11: { en: "Tractor", ja: "トラクター", category: "VEHICLE" },
  12: { en: "Sled", ja: "そり", category: "SPORTS" },
  13: { en: "Aquarium", ja: "水族館・水槽", category: "PLACE" },
  14: { en: "Circus", ja: "サーカス", category: "EVENT" },
  16: { en: "Sitting", ja: "座っている", category: "ACTION" },
  17: { en: "Beard", ja: "あごひげ", category: "BODY" },
  18: { en: "Bridge", ja: "橋", category: "PLACE" },
  19: { en: "Tights", ja: "タイツ", category: "CLOTHING" },
  20: { en: "Bird", ja: "鳥", category: "ANIMAL" },
  21: { en: "Rafting", ja: "ラフティング", category: "SPORTS" },
  22: { en: "Park", ja: "公園", category: "PLACE" },
  24: { en: "Factory", ja: "工場", category: "PLACE" },
  25: { en: "Graduation", ja: "卒業式", category: "EVENT" },
  26: { en: "Porcelain", ja: "磁器", category: "MATERIAL" },
  27: { en: "Twig", ja: "小枝", category: "PLANT" },
  28: { en: "Petal", ja: "花びら", category: "PLANT" },
  29: { en: "Cushion", ja: "クッション", category: "FURNITURE" },
  30: { en: "Sunglasses", ja: "サングラス", category: "CLOTHING" },
  31: { en: "Infrastructure", ja: "インフラ・社会基盤", category: "PLACE" },
  32: { en: "Ferris wheel", ja: "観覧車", category: "PLACE" },
  33: { en: "Pomacentridae", ja: "スズメダイ科（熱帯魚）", category: "ANIMAL" },
  34: { en: "Wetsuit", ja: "ウェットスーツ", category: "CLOTHING" },
  35: {
    en: "Shetland sheepdog",
    ja: "シェットランド・シープドッグ",
    category: "ANIMAL",
  },
  36: { en: "Brig", ja: "ブリッグ（2本マストの帆船）", category: "VEHICLE" },
  37: { en: "Watercolor paint", ja: "水彩画・水彩絵具", category: "ARTS" },
  38: { en: "Competition", ja: "競技・大会", category: "SPORTS" },
  39: { en: "Cliff", ja: "崖", category: "NATURE" },
  40: { en: "Badminton", ja: "バドミントン", category: "SPORTS" },
  41: { en: "Safari", ja: "サファリ", category: "NATURE" },
  42: { en: "Bicycle", ja: "自転車", category: "VEHICLE" },
  43: { en: "Stadium", ja: "競技場", category: "PLACE" },
  45: { en: "Boat", ja: "ボート", category: "VEHICLE" },
  46: { en: "Smile", ja: "笑顔", category: "PEOPLE" },
  47: { en: "Surfboard", ja: "サーフボード", category: "SPORTS" },
  48: { en: "Fast food", ja: "ファストフード", category: "FOOD" },
  49: { en: "Sunset", ja: "夕焼け・日没", category: "WEATHER" },
  50: { en: "Hot dog", ja: "ホットドッグ", category: "FOOD" },
  51: { en: "Shorts", ja: "短パン", category: "CLOTHING" },
  52: { en: "Bus", ja: "バス", category: "VEHICLE" },
  53: { en: "Bullfighting", ja: "闘牛", category: "EVENT" },
  54: { en: "Sky", ja: "空", category: "WEATHER" },
  55: { en: "Gerbil", ja: "スナネズミ", category: "ANIMAL" },
  56: { en: "Rock", ja: "岩", category: "NATURE" },
  57: { en: "Interaction", ja: "交流・触れ合い", category: "CONCEPT" },
  58: { en: "Dress", ja: "ドレス・ワンピース", category: "CLOTHING" },
  59: { en: "Toe", ja: "つま先", category: "BODY" },
  61: { en: "Bear", ja: "クマ", category: "ANIMAL" },
  62: { en: "Eating", ja: "食べている", category: "ACTION" },
  63: { en: "Tower", ja: "塔", category: "PLACE" },
  64: { en: "Brick", ja: "レンガ", category: "MATERIAL" },
  65: { en: "Junk", ja: "ジャンク（がらくた）", category: "OBJECT" },
  66: { en: "Person", ja: "人", category: "PEOPLE" },
  67: { en: "Windsurfing", ja: "ウィンドサーフィン", category: "SPORTS" },
  68: { en: "Swimwear", ja: "水着", category: "CLOTHING" },
  69: { en: "Roller", ja: "ローラー", category: "OBJECT" },
  70: { en: "Camping", ja: "キャンプ", category: "SPORTS" },
  71: { en: "Playground", ja: "遊び場・遊具", category: "PLACE" },
  72: { en: "Bathroom", ja: "浴室・トイレ", category: "PLACE" },
  73: { en: "Laugh", ja: "笑い", category: "PEOPLE" },
  74: { en: "Balloon", ja: "風船", category: "OBJECT" },
  75: { en: "Concert", ja: "コンサート", category: "EVENT" },
  76: { en: "Prom", ja: "プロム（卒業ダンスパーティー）", category: "EVENT" },
  77: { en: "Construction", ja: "建設・工事", category: "PLACE" },
  78: { en: "Product", ja: "製品", category: "OBJECT" },
  79: { en: "Reef", ja: "サンゴ礁", category: "NATURE" },
  80: { en: "Picnic", ja: "ピクニック", category: "SPORTS" },
  81: { en: "Wreath", ja: "リース・花輪", category: "OBJECT" },
  82: { en: "Wheelbarrow", ja: "手押し車", category: "OBJECT" },
  83: {
    en: "Boxer",
    ja: "ボクサー（犬種・ボクシング選手）",
    category: "ANIMAL",
  },
  84: { en: "Necklace", ja: "ネックレス", category: "CLOTHING" },
  85: { en: "Bracelet", ja: "ブレスレット", category: "CLOTHING" },
  86: { en: "Casino", ja: "カジノ", category: "PLACE" },
  87: { en: "Windshield", ja: "フロントガラス", category: "VEHICLE" },
  88: { en: "Stairs", ja: "階段", category: "PLACE" },
  89: { en: "Computer", ja: "コンピューター", category: "ELECTRONICS" },
  90: { en: "Cookware and bakeware", ja: "調理器具", category: "OBJECT" },
  91: { en: "Monochrome", ja: "モノクロ（白黒画像）", category: "IMAGE" },
  92: { en: "Chair", ja: "椅子", category: "FURNITURE" },
  93: { en: "Poster", ja: "ポスター", category: "IMAGE" },
  94: { en: "Bar", ja: "バー・酒場", category: "PLACE" },
  95: { en: "Shipwreck", ja: "難破船", category: "VEHICLE" },
  96: { en: "Pier", ja: "桟橋", category: "PLACE" },
  97: { en: "Community", ja: "コミュニティ", category: "CONCEPT" },
  98: { en: "Caving", ja: "洞窟探検", category: "SPORTS" },
  99: { en: "Cave", ja: "洞窟", category: "NATURE" },
  100: { en: "Tie", ja: "ネクタイ", category: "CLOTHING" },
  101: { en: "Cabinetry", ja: "戸棚・キャビネット類", category: "FURNITURE" },
  102: { en: "Underwater", ja: "水中", category: "NATURE" },
  103: { en: "Clown", ja: "ピエロ", category: "PEOPLE" },
  104: { en: "Nightclub", ja: "ナイトクラブ", category: "PLACE" },
  105: { en: "Cycling", ja: "サイクリング", category: "SPORTS" },
  106: { en: "Comet", ja: "彗星", category: "SPACE" },
  107: { en: "Mortarboard", ja: "角帽", category: "CLOTHING" },
  108: { en: "Track", ja: "陸上トラック・線路", category: "PLACE" },
  109: { en: "Christmas", ja: "クリスマス", category: "EVENT" },
  110: { en: "Church", ja: "教会", category: "PLACE" },
  111: { en: "Clock", ja: "時計", category: "OBJECT" },
  112: { en: "Dude", ja: "男・やつ（俗語）", category: "PEOPLE" },
  113: { en: "Cattle", ja: "牛", category: "ANIMAL" },
  114: { en: "Jungle", ja: "ジャングル", category: "NATURE" },
  115: { en: "Desk", ja: "机", category: "FURNITURE" },
  116: { en: "Curling", ja: "カーリング", category: "SPORTS" },
  117: { en: "Cuisine", ja: "料理", category: "FOOD" },
  118: { en: "Cat", ja: "猫", category: "ANIMAL" },
  119: { en: "Juice", ja: "ジュース", category: "FOOD" },
  120: { en: "Couscous", ja: "クスクス", category: "FOOD" },
  121: { en: "Screenshot", ja: "スクリーンショット", category: "IMAGE" },
  122: { en: "Crew", ja: "乗組員・クルー", category: "PEOPLE" },
  123: { en: "Skyline", ja: "スカイライン（街並みの輪郭）", category: "PLACE" },
  125: { en: "Stuffed toy", ja: "ぬいぐるみ", category: "OBJECT" },
  126: { en: "Cookie", ja: "クッキー", category: "FOOD" },
  127: { en: "Tile", ja: "タイル", category: "MATERIAL" },
  128: { en: "Hanukkah", ja: "ハヌカ（ユダヤ教の祭り）", category: "EVENT" },
  129: { en: "Crochet", ja: "かぎ針編み", category: "ARTS" },
  130: { en: "Skateboarder", ja: "スケートボーダー", category: "PEOPLE" },
  131: { en: "Clipper", ja: "クリッパー（高速帆船）", category: "VEHICLE" },
  132: { en: "Nail", ja: "爪・釘", category: "BODY" },
  133: { en: "Cola", ja: "コーラ", category: "FOOD" },
  134: { en: "Cutlery", ja: "カトラリー", category: "OBJECT" },
  135: { en: "Menu", ja: "メニュー", category: "OBJECT" },
  137: { en: "Sari", ja: "サリー（インドの民族衣装）", category: "CLOTHING" },
  138: { en: "Plush", ja: "ぬいぐるみ・フラシ天", category: "OBJECT" },
  139: { en: "Pocket", ja: "ポケット", category: "CLOTHING" },
  140: { en: "Neon", ja: "ネオン", category: "OBJECT" },
  141: { en: "Icicle", ja: "つらら", category: "NATURE" },
  142: { en: "Pasteles", ja: "パステレス（中南米の料理）", category: "FOOD" },
  143: { en: "Chain", ja: "鎖", category: "OBJECT" },
  144: { en: "Dance", ja: "ダンス", category: "ACTION" },
  145: { en: "Dune", ja: "砂丘", category: "NATURE" },
  146: { en: "Santa claus", ja: "サンタクロース", category: "CHARACTER" },
  147: { en: "Thanksgiving", ja: "感謝祭", category: "EVENT" },
  148: { en: "Tuxedo", ja: "タキシード", category: "CLOTHING" },
  149: { en: "Mouth", ja: "口", category: "BODY" },
  150: { en: "Desert", ja: "砂漠", category: "NATURE" },
  151: { en: "Dinosaur", ja: "恐竜", category: "ANIMAL" },
  152: { en: "Mufti", ja: "私服（軍人などの平服）", category: "CLOTHING" },
  153: { en: "Fire", ja: "火・火災", category: "NATURE" },
  154: { en: "Bedroom", ja: "寝室", category: "PLACE" },
  155: { en: "Goggles", ja: "ゴーグル", category: "CLOTHING" },
  156: { en: "Dragon", ja: "ドラゴン・竜", category: "CHARACTER" },
  157: { en: "Couch", ja: "ソファ", category: "FURNITURE" },
  158: { en: "Sledding", ja: "そり遊び", category: "SPORTS" },
  159: { en: "Cap", ja: "キャップ（帽子）", category: "CLOTHING" },
  160: { en: "Whiteboard", ja: "ホワイトボード", category: "OBJECT" },
  161: { en: "Hat", ja: "帽子", category: "CLOTHING" },
  162: { en: "Gelato", ja: "ジェラート", category: "FOOD" },
  163: { en: "Cavalier", ja: "キャバリア（犬種）", category: "ANIMAL" },
  164: { en: "Beanie", ja: "ニット帽", category: "CLOTHING" },
  165: { en: "Jersey", ja: "ジャージ・ユニフォーム", category: "CLOTHING" },
  166: { en: "Scarf", ja: "マフラー・スカーフ", category: "CLOTHING" },
  167: { en: "Vacation", ja: "休暇", category: "CONCEPT" },
  168: { en: "Pitch", ja: "ピッチ（競技場）", category: "PLACE" },
  169: { en: "Blackboard", ja: "黒板", category: "OBJECT" },
  170: { en: "Deejay", ja: "DJ", category: "PEOPLE" },
  171: { en: "Monument", ja: "記念碑", category: "PLACE" },
  172: { en: "Bumper", ja: "バンパー", category: "VEHICLE" },
  173: { en: "Longboard", ja: "ロングボード", category: "SPORTS" },
  174: { en: "Waterfowl", ja: "水鳥", category: "ANIMAL" },
  175: { en: "Flesh", ja: "肌・肉", category: "BODY" },
  176: { en: "Net", ja: "ネット・網", category: "OBJECT" },
  177: { en: "Icing", ja: "アイシング（糖衣）", category: "FOOD" },
  178: { en: "Dalmatian", ja: "ダルメシアン", category: "ANIMAL" },
  179: { en: "Speedboat", ja: "モーターボート", category: "VEHICLE" },
  180: { en: "Trunk", ja: "木の幹・トランク", category: "PLANT" },
  181: { en: "Coffee", ja: "コーヒー", category: "FOOD" },
  182: { en: "Soccer", ja: "サッカー", category: "SPORTS" },
  183: { en: "Ragdoll", ja: "ラグドール（猫の品種）", category: "ANIMAL" },
  184: { en: "Food", ja: "食べ物", category: "FOOD" },
  185: { en: "Standing", ja: "立っている", category: "ACTION" },
  186: { en: "Fiction", ja: "フィクション", category: "CONCEPT" },
  187: { en: "Fruit", ja: "果物", category: "FOOD" },
  188: { en: "Pho", ja: "フォー", category: "FOOD" },
  189: { en: "Sparkler", ja: "手持ち花火", category: "EVENT" },
  190: { en: "Presentation", ja: "プレゼンテーション", category: "EVENT" },
  191: { en: "Swing", ja: "ブランコ", category: "OBJECT" },
  192: { en: "Cairn terrier", ja: "ケアーン・テリア", category: "ANIMAL" },
  193: { en: "Forest", ja: "森", category: "NATURE" },
  194: { en: "Flag", ja: "旗", category: "OBJECT" },
  195: { en: "Frigate", ja: "フリゲート艦", category: "VEHICLE" },
  196: { en: "Foot", ja: "足", category: "BODY" },
  197: { en: "Jacket", ja: "ジャケット", category: "CLOTHING" },
  199: { en: "Pillow", ja: "枕", category: "FURNITURE" },
  201: { en: "Bathing", ja: "入浴・水浴び", category: "ACTION" },
  202: { en: "Glacier", ja: "氷河", category: "NATURE" },
  203: { en: "Gymnastics", ja: "体操", category: "SPORTS" },
  204: { en: "Ear", ja: "耳", category: "BODY" },
  205: { en: "Flora", ja: "植物相", category: "PLANT" },
  206: { en: "Shell", ja: "貝殻", category: "NATURE" },
  207: { en: "Grandparent", ja: "祖父母", category: "PEOPLE" },
  208: { en: "Ruins", ja: "遺跡", category: "PLACE" },
  209: { en: "Eyelash", ja: "まつげ", category: "BODY" },
  210: { en: "Bunk bed", ja: "二段ベッド", category: "FURNITURE" },
  211: { en: "Balance", ja: "バランス", category: "CONCEPT" },
  212: { en: "Backpacking", ja: "バックパッキング", category: "SPORTS" },
  213: { en: "Horse", ja: "馬", category: "ANIMAL" },
  214: { en: "Glitter", ja: "ラメ・きらめき", category: "MATERIAL" },
  215: { en: "Saucer", ja: "ソーサー（受け皿）", category: "OBJECT" },
  216: { en: "Hair", ja: "髪", category: "BODY" },
  217: { en: "Miniature", ja: "ミニチュア", category: "OBJECT" },
  218: { en: "Crowd", ja: "群衆", category: "PEOPLE" },
  219: { en: "Curtain", ja: "カーテン", category: "FURNITURE" },
  220: { en: "Icon", ja: "アイコン", category: "IMAGE" },
  221: { en: "Pixie-bob", ja: "ピクシーボブ（猫の品種）", category: "ANIMAL" },
  222: { en: "Herd", ja: "群れ", category: "ANIMAL" },
  223: { en: "Insect", ja: "昆虫", category: "ANIMAL" },
  224: { en: "Ice", ja: "氷", category: "NATURE" },
  225: { en: "Bangle", ja: "バングル", category: "CLOTHING" },
  226: { en: "Flap", ja: "フラップ・垂れ蓋", category: "OBJECT" },
  227: { en: "Jewellery", ja: "宝飾品", category: "CLOTHING" },
  228: { en: "Knitting", ja: "編み物", category: "ARTS" },
  229: {
    en: "Centrepiece",
    ja: "センターピース（卓上装飾）",
    category: "OBJECT",
  },
  230: { en: "Outerwear", ja: "上着", category: "CLOTHING" },
  231: { en: "Love", ja: "愛", category: "CONCEPT" },
  232: { en: "Muscle", ja: "筋肉", category: "BODY" },
  233: { en: "Motorcycle", ja: "オートバイ", category: "VEHICLE" },
  234: { en: "Money", ja: "お金", category: "OBJECT" },
  235: { en: "Mosque", ja: "モスク", category: "PLACE" },
  236: { en: "Tableware", ja: "食器", category: "OBJECT" },
  237: { en: "Ballroom", ja: "舞踏場", category: "PLACE" },
  238: { en: "Kayak", ja: "カヤック", category: "VEHICLE" },
  239: { en: "Leisure", ja: "余暇・レジャー", category: "CONCEPT" },
  240: { en: "Receipt", ja: "レシート", category: "OBJECT" },
  241: { en: "Lake", ja: "湖", category: "NATURE" },
  242: { en: "Lighthouse", ja: "灯台", category: "PLACE" },
  243: { en: "Bridle", ja: "頭絡（馬具）", category: "OBJECT" },
  244: { en: "Leather", ja: "革", category: "MATERIAL" },
  245: { en: "Horn", ja: "角・ホルン", category: "OBJECT" },
  246: { en: "Strap", ja: "ストラップ", category: "OBJECT" },
  247: { en: "Lego", ja: "レゴ", category: "OBJECT" },
  248: { en: "Scuba diving", ja: "スキューバダイビング", category: "SPORTS" },
  249: { en: "Leggings", ja: "レギンス", category: "CLOTHING" },
  250: { en: "Pool", ja: "プール", category: "PLACE" },
  251: { en: "Musical instrument", ja: "楽器", category: "ARTS" },
  252: { en: "Musical", ja: "ミュージカル", category: "ARTS" },
  253: { en: "Metal", ja: "金属", category: "MATERIAL" },
  254: { en: "Moon", ja: "月", category: "SPACE" },
  255: { en: "Blazer", ja: "ブレザー", category: "CLOTHING" },
  256: { en: "Marriage", ja: "結婚", category: "EVENT" },
  257: { en: "Mobile phone", ja: "携帯電話", category: "ELECTRONICS" },
  258: { en: "Militia", ja: "民兵", category: "PEOPLE" },
  259: { en: "Tablecloth", ja: "テーブルクロス", category: "OBJECT" },
  260: { en: "Party", ja: "パーティー", category: "EVENT" },
  261: { en: "Nebula", ja: "星雲", category: "SPACE" },
  262: { en: "News", ja: "ニュース", category: "CONCEPT" },
  263: { en: "Newspaper", ja: "新聞", category: "OBJECT" },
  265: { en: "Piano", ja: "ピアノ", category: "ARTS" },
  266: { en: "Plant", ja: "植物", category: "PLANT" },
  267: { en: "Passport", ja: "パスポート", category: "OBJECT" },
  268: { en: "Penguin", ja: "ペンギン", category: "ANIMAL" },
  269: { en: "Shikoku", ja: "四国犬", category: "ANIMAL" },
  270: { en: "Palace", ja: "宮殿", category: "PLACE" },
  271: { en: "Doily", ja: "ドイリー（レースの敷物）", category: "OBJECT" },
  272: { en: "Polo", ja: "ポロ（競技）・ポロシャツ", category: "SPORTS" },
  273: { en: "Paper", ja: "紙", category: "MATERIAL" },
  274: { en: "Pop music", ja: "ポップ音楽", category: "ARTS" },
  275: { en: "Skiff", ja: "小舟", category: "VEHICLE" },
  276: { en: "Pizza", ja: "ピザ", category: "FOOD" },
  277: { en: "Pet", ja: "ペット", category: "ANIMAL" },
  278: { en: "Quilting", ja: "キルティング", category: "ARTS" },
  279: { en: "Cage", ja: "ケージ・檻", category: "OBJECT" },
  280: { en: "Skateboard", ja: "スケートボード", category: "SPORTS" },
  281: { en: "Surfing", ja: "サーフィン", category: "SPORTS" },
  282: { en: "Rugby", ja: "ラグビー", category: "SPORTS" },
  283: { en: "Lipstick", ja: "口紅", category: "OBJECT" },
  284: { en: "River", ja: "川", category: "NATURE" },
  285: { en: "Race", ja: "レース・競走", category: "SPORTS" },
  286: { en: "Rowing", ja: "ボート漕ぎ", category: "SPORTS" },
  287: { en: "Road", ja: "道路", category: "PLACE" },
  288: { en: "Running", ja: "ランニング", category: "SPORTS" },
  289: { en: "Room", ja: "部屋", category: "PLACE" },
  290: { en: "Roof", ja: "屋根", category: "PLACE" },
  291: { en: "Star", ja: "星", category: "SPACE" },
  292: { en: "Sports", ja: "スポーツ", category: "SPORTS" },
  293: { en: "Shoe", ja: "靴", category: "CLOTHING" },
  294: {
    en: "Tubing",
    ja: "チュービング（浮き輪での川下り等）",
    category: "SPORTS",
  },
  295: { en: "Space", ja: "宇宙", category: "SPACE" },
  296: { en: "Sleep", ja: "睡眠", category: "ACTION" },
  297: { en: "Skin", ja: "肌", category: "BODY" },
  298: { en: "Swimming", ja: "水泳", category: "SPORTS" },
  299: { en: "School", ja: "学校", category: "PLACE" },
  300: { en: "Sushi", ja: "寿司", category: "FOOD" },
  301: { en: "Loveseat", ja: "二人掛けソファ", category: "FURNITURE" },
  302: { en: "Superman", ja: "スーパーマン", category: "CHARACTER" },
  303: { en: "Cool", ja: "かっこいい", category: "CONCEPT" },
  304: { en: "Skiing", ja: "スキー", category: "SPORTS" },
  305: { en: "Submarine", ja: "潜水艦", category: "VEHICLE" },
  306: { en: "Song", ja: "歌", category: "ARTS" },
  307: { en: "Class", ja: "授業・教室", category: "PLACE" },
  308: { en: "Skyscraper", ja: "超高層ビル", category: "PLACE" },
  309: { en: "Volcano", ja: "火山", category: "NATURE" },
  310: { en: "Television", ja: "テレビ", category: "ELECTRONICS" },
  311: { en: "Rein", ja: "手綱", category: "OBJECT" },
  312: { en: "Tattoo", ja: "タトゥー", category: "BODY" },
  313: { en: "Train", ja: "電車", category: "VEHICLE" },
  314: { en: "Handrail", ja: "手すり", category: "OBJECT" },
  315: { en: "Cup", ja: "カップ", category: "OBJECT" },
  316: { en: "Vehicle", ja: "乗り物", category: "VEHICLE" },
  317: { en: "Handbag", ja: "ハンドバッグ", category: "CLOTHING" },
  318: { en: "Lampshade", ja: "ランプシェード", category: "FURNITURE" },
  319: { en: "Event", ja: "イベント", category: "CONCEPT" },
  320: { en: "Wine", ja: "ワイン", category: "FOOD" },
  321: { en: "Wing", ja: "翼", category: "ANIMAL" },
  322: { en: "Wheel", ja: "車輪", category: "VEHICLE" },
  323: { en: "Wakeboarding", ja: "ウェイクボード", category: "SPORTS" },
  324: { en: "Web page", ja: "ウェブページ", category: "IMAGE" },
  327: { en: "Ranch", ja: "牧場", category: "PLACE" },
  328: { en: "Fishing", ja: "釣り", category: "SPORTS" },
  329: { en: "Heart", ja: "ハート・心臓", category: "CONCEPT" },
  330: { en: "Cotton", ja: "綿", category: "MATERIAL" },
  331: { en: "Cappuccino", ja: "カプチーノ", category: "FOOD" },
  332: { en: "Bread", ja: "パン", category: "FOOD" },
  333: { en: "Sand", ja: "砂", category: "NATURE" },
  335: { en: "Museum", ja: "博物館・美術館", category: "PLACE" },
  336: { en: "Helicopter", ja: "ヘリコプター", category: "VEHICLE" },
  337: { en: "Mountain", ja: "山", category: "NATURE" },
  338: { en: "Duck", ja: "カモ・アヒル", category: "ANIMAL" },
  339: { en: "Soil", ja: "土", category: "NATURE" },
  340: { en: "Turtle", ja: "カメ", category: "ANIMAL" },
  341: { en: "Crocodile", ja: "ワニ", category: "ANIMAL" },
  342: { en: "Musician", ja: "ミュージシャン", category: "PEOPLE" },
  343: { en: "Sneakers", ja: "スニーカー", category: "CLOTHING" },
  344: { en: "Wool", ja: "羊毛", category: "MATERIAL" },
  345: { en: "Ring", ja: "指輪", category: "CLOTHING" },
  346: { en: "Singer", ja: "歌手", category: "PEOPLE" },
  347: { en: "Carnival", ja: "カーニバル", category: "EVENT" },
  348: { en: "Snowboarding", ja: "スノーボード", category: "SPORTS" },
  349: { en: "Waterskiing", ja: "水上スキー", category: "SPORTS" },
  350: { en: "Wall", ja: "壁", category: "PLACE" },
  351: { en: "Rocket", ja: "ロケット", category: "SPACE" },
  352: { en: "Countertop", ja: "調理台", category: "FURNITURE" },
  353: { en: "Beach", ja: "砂浜・海辺", category: "NATURE" },
  354: { en: "Rainbow", ja: "虹", category: "WEATHER" },
  355: { en: "Branch", ja: "枝", category: "PLANT" },
  356: { en: "Moustache", ja: "口ひげ", category: "BODY" },
  357: { en: "Garden", ja: "庭園", category: "PLACE" },
  358: { en: "Gown", ja: "ガウン・ドレス", category: "CLOTHING" },
  359: { en: "Field", ja: "野原・畑", category: "NATURE" },
  360: { en: "Dog", ja: "犬", category: "ANIMAL" },
  361: { en: "Superhero", ja: "スーパーヒーロー", category: "CHARACTER" },
  362: { en: "Flower", ja: "花", category: "PLANT" },
  363: { en: "Placemat", ja: "ランチョンマット", category: "OBJECT" },
  364: { en: "Subwoofer", ja: "サブウーファー", category: "ELECTRONICS" },
  365: { en: "Cathedral", ja: "大聖堂", category: "PLACE" },
  366: { en: "Building", ja: "建物", category: "PLACE" },
  367: { en: "Airplane", ja: "飛行機", category: "VEHICLE" },
  368: { en: "Fur", ja: "毛皮", category: "MATERIAL" },
  369: { en: "Bull", ja: "雄牛", category: "ANIMAL" },
  370: { en: "Bench", ja: "ベンチ", category: "FURNITURE" },
  371: { en: "Temple", ja: "寺院", category: "PLACE" },
  372: { en: "Butterfly", ja: "蝶", category: "ANIMAL" },
  373: { en: "Model", ja: "モデル・模型", category: "PEOPLE" },
  374: { en: "Marathon", ja: "マラソン", category: "SPORTS" },
  375: { en: "Needlework", ja: "針仕事・刺繍", category: "ARTS" },
  376: { en: "Kitchen", ja: "台所", category: "PLACE" },
  377: { en: "Castle", ja: "城", category: "PLACE" },
  378: { en: "Aurora", ja: "オーロラ", category: "WEATHER" },
  379: { en: "Larva", ja: "幼虫", category: "ANIMAL" },
  380: { en: "Racing", ja: "レース", category: "SPORTS" },
  382: { en: "Airliner", ja: "旅客機", category: "VEHICLE" },
  383: { en: "Dam", ja: "ダム", category: "PLACE" },
  384: { en: "Textile", ja: "織物・布地", category: "MATERIAL" },
  385: { en: "Groom", ja: "新郎", category: "PEOPLE" },
  386: { en: "Fun", ja: "楽しい", category: "CONCEPT" },
  387: { en: "Steaming", ja: "湯気", category: "NATURE" },
  388: { en: "Vegetable", ja: "野菜", category: "FOOD" },
  389: { en: "Unicycle", ja: "一輪車", category: "VEHICLE" },
  390: { en: "Jeans", ja: "ジーンズ", category: "CLOTHING" },
  391: { en: "Flowerpot", ja: "植木鉢", category: "OBJECT" },
  392: { en: "Drawer", ja: "引き出し", category: "FURNITURE" },
  393: { en: "Cake", ja: "ケーキ", category: "FOOD" },
  394: { en: "Armrest", ja: "肘掛け", category: "FURNITURE" },
  395: { en: "Aviation", ja: "航空", category: "VEHICLE" },
  397: { en: "Fog", ja: "霧", category: "WEATHER" },
  398: { en: "Fireworks", ja: "花火", category: "EVENT" },
  399: { en: "Farm", ja: "農場", category: "PLACE" },
  400: { en: "Seal", ja: "アザラシ", category: "ANIMAL" },
  401: { en: "Shelf", ja: "棚", category: "FURNITURE" },
  402: { en: "Bangs", ja: "前髪", category: "BODY" },
  403: { en: "Lightning", ja: "稲妻", category: "WEATHER" },
  404: { en: "Van", ja: "バン", category: "VEHICLE" },
  405: { en: "Sphynx", ja: "スフィンクス（猫の品種）", category: "ANIMAL" },
  406: { en: "Tire", ja: "タイヤ", category: "VEHICLE" },
  407: { en: "Denim", ja: "デニム", category: "MATERIAL" },
  408: { en: "Prairie", ja: "草原", category: "NATURE" },
  409: { en: "Snorkeling", ja: "シュノーケリング", category: "SPORTS" },
  410: { en: "Umbrella", ja: "傘", category: "OBJECT" },
  411: { en: "Asphalt", ja: "アスファルト", category: "MATERIAL" },
  412: { en: "Sailboat", ja: "帆船・ヨット", category: "VEHICLE" },
  413: { en: "Basset hound", ja: "バセット・ハウンド", category: "ANIMAL" },
  414: { en: "Pattern", ja: "模様・柄", category: "IMAGE" },
  415: { en: "Supper", ja: "夕食", category: "FOOD" },
  416: { en: "Veil", ja: "ベール", category: "CLOTHING" },
  417: { en: "Waterfall", ja: "滝", category: "NATURE" },
  419: { en: "Lunch", ja: "昼食", category: "FOOD" },
  420: { en: "Odometer", ja: "走行距離計", category: "VEHICLE" },
  421: { en: "Baby", ja: "赤ちゃん", category: "PEOPLE" },
  422: { en: "Glasses", ja: "眼鏡", category: "CLOTHING" },
  423: { en: "Car", ja: "自動車", category: "VEHICLE" },
  424: { en: "Aircraft", ja: "航空機", category: "VEHICLE" },
  425: { en: "Hand", ja: "手", category: "BODY" },
  426: { en: "Rodeo", ja: "ロデオ", category: "EVENT" },
  427: { en: "Canyon", ja: "峡谷", category: "NATURE" },
  428: { en: "Meal", ja: "食事", category: "FOOD" },
  429: { en: "Softball", ja: "ソフトボール", category: "SPORTS" },
  430: { en: "Alcohol", ja: "酒類", category: "FOOD" },
  431: { en: "Bride", ja: "花嫁", category: "PEOPLE" },
  432: { en: "Swamp", ja: "沼地", category: "NATURE" },
  433: { en: "Pie", ja: "パイ", category: "FOOD" },
  434: { en: "Bag", ja: "かばん", category: "CLOTHING" },
  435: { en: "Joker", ja: "ジョーカー（道化・悪役）", category: "CHARACTER" },
  436: { en: "Supervillain", ja: "悪役", category: "CHARACTER" },
  437: { en: "Army", ja: "軍隊", category: "PEOPLE" },
  438: { en: "Canoe", ja: "カヌー", category: "VEHICLE" },
  439: { en: "Selfie", ja: "自撮り", category: "IMAGE" },
  440: { en: "Rickshaw", ja: "人力車", category: "VEHICLE" },
  441: { en: "Barn", ja: "納屋", category: "PLACE" },
  442: { en: "Archery", ja: "アーチェリー", category: "SPORTS" },
  443: { en: "Aerospace engineering", ja: "航空宇宙工学", category: "SPACE" },
  445: { en: "Storm", ja: "嵐", category: "WEATHER" },
  446: { en: "Helmet", ja: "ヘルメット", category: "CLOTHING" },
  1000: { en: "Smart speaker", ja: "スマートスピーカー", category: "ELECTRONICS" },
  1001: { en: "Virtual reality headset", ja: "VRヘッドセット", category: "ELECTRONICS" },
  1002: { en: "Tumbler", ja: "タンブラー", category: "OBJECT" },
  1003: { en: "Electric kettle", ja: "電気ケトル", category: "ELECTRONICS" },
  1004: { en: "Electric razor", ja: "電気かみそり", category: "ELECTRONICS" },
  1005: { en: "Packaged goods", ja: "包装された商品", category: "OBJECT" },
  1006: { en: "Kid bike", ja: "子ども用自転車", category: "VEHICLE" },
  1007: { en: "2D barcode", ja: "二次元バーコード", category: "OBJECT" },
  1008: { en: "1D barcode", ja: "バーコード", category: "OBJECT" },
  1009: { en: "Water bottle", ja: "水筒・ボトル", category: "OBJECT" },
  1010: { en: "Tortoise", ja: "リクガメ", category: "ANIMAL" },
  1011: { en: "Cooker", ja: "調理器", category: "ELECTRONICS" },
  1012: { en: "Container", ja: "容器", category: "OBJECT" },
  1013: { en: "Magpie", ja: "カササギ", category: "ANIMAL" },
  1014: { en: "Sea turtle", ja: "ウミガメ", category: "ANIMAL" },
  1015: { en: "Football", ja: "フットボール（ボール）", category: "SPORTS" },
  1016: { en: "Vacuum flask", ja: "魔法瓶", category: "OBJECT" },
  1017: { en: "Ambulance", ja: "救急車", category: "VEHICLE" },
  1018: { en: "Ladder", ja: "はしご", category: "OBJECT" },
  1019: { en: "Toothbrush", ja: "歯ブラシ", category: "OBJECT" },
  1020: { en: "Syringe", ja: "注射器", category: "OBJECT" },
  1021: { en: "Sink", ja: "流し台・洗面台", category: "FURNITURE" },
  1022: { en: "Toy", ja: "おもちゃ", category: "OBJECT" },
  1023: { en: "T-shirt", ja: "Tシャツ", category: "CLOTHING" },
  1024: { en: "Organ", ja: "オルガン", category: "ARTS" },
  1025: { en: "Cassette deck", ja: "カセットデッキ", category: "ELECTRONICS" },
  1026: { en: "Apple", ja: "りんご", category: "FOOD" },
  1027: { en: "Paddle", ja: "パドル・オール", category: "SPORTS" },
  1028: { en: "Snowman", ja: "雪だるま", category: "OBJECT" },
  1029: { en: "Beer", ja: "ビール", category: "FOOD" },
  1030: { en: "Bridge", ja: "橋", category: "PLACE" },
  1031: { en: "Board game", ja: "ボードゲーム", category: "OBJECT" },
  1032: { en: "Parking meter", ja: "パーキングメーター", category: "OBJECT" },
  1033: { en: "Traffic light", ja: "信号機", category: "OBJECT" },
  1034: { en: "Croissant", ja: "クロワッサン", category: "FOOD" },
  1035: { en: "Cucumber", ja: "きゅうり", category: "FOOD" },
  1036: { en: "Radish", ja: "大根・ラディッシュ", category: "FOOD" },
  1037: { en: "Towel", ja: "タオル", category: "OBJECT" },
  1038: { en: "Doll", ja: "人形", category: "OBJECT" },
  1039: { en: "Notebook", ja: "ノート", category: "OBJECT" },
  1040: { en: "Washing machine", ja: "洗濯機", category: "ELECTRONICS" },
  1041: { en: "Glove", ja: "手袋", category: "CLOTHING" },
  1042: { en: "Vinyl record", ja: "レコード盤", category: "ARTS" },
  1043: { en: "Tick", ja: "ダニ", category: "ANIMAL" },
  1044: { en: "Belt", ja: "ベルト", category: "CLOTHING" },
  1045: { en: "Sunglasses", ja: "サングラス", category: "CLOTHING" },
  1046: { en: "Action figure", ja: "アクションフィギュア", category: "OBJECT" },
  1047: { en: "Banjo", ja: "バンジョー", category: "ARTS" },
  1048: { en: "Cart", ja: "カート・台車", category: "VEHICLE" },
  1049: { en: "Ball", ja: "ボール", category: "SPORTS" },
  1050: { en: "Backpack", ja: "リュックサック", category: "CLOTHING" },
  1051: { en: "Bicycle", ja: "自転車", category: "VEHICLE" },
  1052: { en: "Sweater", ja: "セーター", category: "CLOTHING" },
  1053: { en: "Stadium", ja: "スタジアム", category: "PLACE" },
  1054: { en: "Home appliance", ja: "家電", category: "ELECTRONICS" },
  1055: { en: "Centipede", ja: "ムカデ", category: "ANIMAL" },
  1056: { en: "Boat", ja: "ボート", category: "VEHICLE" },
  1057: { en: "Lighting", ja: "照明", category: "FURNITURE" },
  1058: { en: "Surfboard", ja: "サーフボード", category: "SPORTS" },
  1059: { en: "Chopsticks", ja: "箸", category: "OBJECT" },
  1060: { en: "Boot", ja: "ブーツ", category: "CLOTHING" },
  1061: { en: "Headphones", ja: "ヘッドホン", category: "ELECTRONICS" },
  1062: { en: "Hot dog", ja: "ホットドッグ", category: "FOOD" },
  1063: { en: "Shorts", ja: "ショートパンツ", category: "CLOTHING" },
  1064: { en: "Bus", ja: "バス", category: "VEHICLE" },
  1065: { en: "Camera lens", ja: "カメラレンズ", category: "ELECTRONICS" },
  1066: { en: "Screwdriver", ja: "ドライバー（工具）", category: "OBJECT" },
  1067: { en: "Bicycle wheel", ja: "自転車の車輪", category: "VEHICLE" },
  1068: { en: "Flash", ja: "フラッシュ（ストロボ）", category: "ELECTRONICS" },
  1069: { en: "Barge", ja: "はしけ・平底船", category: "VEHICLE" },
  1070: { en: "Battery", ja: "電池", category: "ELECTRONICS" },
  1071: { en: "Laptop", ja: "ノートパソコン", category: "ELECTRONICS" },
  1072: { en: "Miniskirt", ja: "ミニスカート", category: "CLOTHING" },
  1073: { en: "Drill", ja: "ドリル", category: "OBJECT" },
  1074: { en: "Dress", ja: "ドレス・ワンピース", category: "CLOTHING" },
  1075: { en: "Bear", ja: "クマ", category: "ANIMAL" },
  1076: { en: "Waffle", ja: "ワッフル", category: "FOOD" },
  1077: { en: "Pancake", ja: "パンケーキ", category: "FOOD" },
  1078: { en: "Brown bear", ja: "ヒグマ", category: "ANIMAL" },
  1079: { en: "Woodpecker", ja: "キツツキ", category: "ANIMAL" },
  1080: { en: "Blue jay", ja: "アオカケス", category: "ANIMAL" },
  1081: { en: "Pretzel", ja: "プレッツェル", category: "FOOD" },
  1082: { en: "Bagel", ja: "ベーグル", category: "FOOD" },
  1083: { en: "Teapot", ja: "ティーポット", category: "OBJECT" },
  1084: { en: "Person", ja: "人", category: "PEOPLE" },
  1085: { en: "Bow and arrow", ja: "弓矢", category: "SPORTS" },
  1086: { en: "Swimwear", ja: "水着", category: "CLOTHING" },
  1087: { en: "Brassiere", ja: "ブラジャー", category: "CLOTHING" },
  1088: { en: "Bee", ja: "ハチ", category: "ANIMAL" },
  1089: { en: "Bat", ja: "コウモリ", category: "ANIMAL" },
  1090: { en: "Starfish", ja: "ヒトデ", category: "ANIMAL" },
  1091: { en: "Popcorn", ja: "ポップコーン", category: "FOOD" },
  1092: { en: "Burrito", ja: "ブリトー", category: "FOOD" },
  1093: { en: "Chainsaw", ja: "チェーンソー", category: "OBJECT" },
  1094: { en: "Balloon", ja: "風船", category: "OBJECT" },
  1095: { en: "Wrench", ja: "レンチ・スパナ", category: "OBJECT" },
  1096: { en: "Tent", ja: "テント", category: "OBJECT" },
  1097: { en: "License plate", ja: "ナンバープレート", category: "VEHICLE" },
  1098: { en: "Lantern", ja: "ランタン", category: "OBJECT" },
  1099: { en: "Toaster", ja: "トースター", category: "ELECTRONICS" },
  1100: { en: "Flashlight", ja: "懐中電灯", category: "OBJECT" },
  1101: { en: "Tiara", ja: "ティアラ", category: "CLOTHING" },
  1102: { en: "Limousine", ja: "リムジン", category: "VEHICLE" },
  1103: { en: "Necklace", ja: "ネックレス", category: "CLOTHING" },
  1104: { en: "Bracelet", ja: "ブレスレット", category: "CLOTHING" },
  1105: { en: "Scissors", ja: "はさみ", category: "OBJECT" },
  1106: { en: "Computer keyboard", ja: "キーボード", category: "ELECTRONICS" },
  1107: { en: "Printer", ja: "プリンター", category: "ELECTRONICS" },
  1108: { en: "Traffic sign", ja: "交通標識", category: "OBJECT" },
  1109: { en: "Chair", ja: "椅子", category: "FURNITURE" },
  1110: { en: "Shirt", ja: "シャツ", category: "CLOTHING" },
  1111: { en: "Poster", ja: "ポスター", category: "ARTS" },
  1112: { en: "Thermostat", ja: "サーモスタット", category: "ELECTRONICS" },
  1113: { en: "Cheese", ja: "チーズ", category: "FOOD" },
  1114: { en: "Sock", ja: "靴下", category: "CLOTHING" },
  1115: { en: "Fire hydrant", ja: "消火栓", category: "OBJECT" },
  1116: { en: "Barbecue grill", ja: "バーベキューグリル", category: "OBJECT" },
  1117: { en: "Earrings", ja: "イヤリング・ピアス", category: "CLOTHING" },
  1118: { en: "Tie", ja: "ネクタイ", category: "CLOTHING" },
  1119: { en: "Cabinetry", ja: "戸棚", category: "FURNITURE" },
  1120: { en: "Suitcase", ja: "スーツケース", category: "OBJECT" },
  1121: { en: "Bodysuit", ja: "ボディスーツ", category: "CLOTHING" },
  1122: { en: "Business card", ja: "名刺", category: "OBJECT" },
  1123: { en: "Vest", ja: "ベスト", category: "CLOTHING" },
  1124: { en: "Muffin", ja: "マフィン", category: "FOOD" },
  1125: { en: "Bidet", ja: "ビデ", category: "FURNITURE" },
  1126: { en: "Expresso machine", ja: "エスプレッソマシン", category: "ELECTRONICS" },
  1127: { en: "Snack", ja: "おやつ・スナック", category: "FOOD" },
  1128: { en: "Snowmobile", ja: "スノーモービル", category: "VEHICLE" },
  1129: { en: "Clock", ja: "時計", category: "OBJECT" },
  1130: { en: "Camel", ja: "ラクダ", category: "ANIMAL" },
  1131: { en: "Figurine", ja: "小さな像・フィギュア", category: "ARTS" },
  1132: { en: "Cattle", ja: "牛", category: "ANIMAL" },
  1133: { en: "Jet ski", ja: "水上バイク", category: "VEHICLE" },
  1134: { en: "Coat", ja: "コート", category: "CLOTHING" },
  1135: { en: "Suit", ja: "スーツ", category: "CLOTHING" },
  1136: { en: "Desk", ja: "机", category: "FURNITURE" },
  1137: { en: "Cat", ja: "猫", category: "ANIMAL" },
  1138: { en: "Bronze sculpture", ja: "ブロンズ像", category: "ARTS" },
  1139: { en: "Juice", ja: "ジュース", category: "FOOD" },
  1140: { en: "Basket", ja: "かご", category: "OBJECT" },
  1141: { en: "Gondola", ja: "ゴンドラ", category: "VEHICLE" },
  1142: { en: "Beetle", ja: "甲虫", category: "ANIMAL" },
  1143: { en: "Cannon", ja: "大砲", category: "OBJECT" },
  1144: { en: "Mouse", ja: "マウス（ネズミ／パソコン）", category: "OBJECT" },
  1145: { en: "Wine bottle", ja: "ワインボトル", category: "FOOD" },
  1146: { en: "Comb", ja: "くし", category: "OBJECT" },
  1147: { en: "Slipper", ja: "スリッパ", category: "CLOTHING" },
  1148: { en: "Stuffed toy", ja: "ぬいぐるみ", category: "OBJECT" },
  1149: { en: "Cookie", ja: "クッキー", category: "FOOD" },
  1150: { en: "Fountain", ja: "噴水", category: "PLACE" },
  1151: { en: "Wine cooler", ja: "ワインクーラー", category: "OBJECT" },
  1152: { en: "Coin", ja: "硬貨", category: "OBJECT" },
  1153: { en: "Calculator", ja: "電卓", category: "ELECTRONICS" },
  1154: { en: "Cocktail", ja: "カクテル", category: "FOOD" },
  1155: { en: "Menu", ja: "メニュー", category: "OBJECT" },
  1156: { en: "Computer monitor", ja: "モニター", category: "ELECTRONICS" },
  1157: { en: "Box", ja: "箱", category: "OBJECT" },
  1158: { en: "Stapler", ja: "ホッチキス", category: "OBJECT" },
  1159: { en: "Christmas tree", ja: "クリスマスツリー", category: "EVENT" },
  1160: { en: "Cowboy hat", ja: "カウボーイハット", category: "CLOTHING" },
  1161: { en: "Video camera", ja: "ビデオカメラ", category: "ELECTRONICS" },
  1162: { en: "Flip-flops", ja: "ビーチサンダル", category: "CLOTHING" },
  1163: { en: "Bean bag", ja: "ビーズクッション", category: "FURNITURE" },
  1164: { en: "Drum", ja: "太鼓・ドラム", category: "ARTS" },
  1165: { en: "Dessert", ja: "デザート", category: "FOOD" },
  1166: { en: "Wine rack", ja: "ワインラック", category: "FURNITURE" },
  1167: { en: "Drink", ja: "飲み物", category: "FOOD" },
  1168: { en: "Zucchini", ja: "ズッキーニ", category: "FOOD" },
  1169: { en: "Ladle", ja: "おたま", category: "OBJECT" },
  1170: { en: "Baseball cap", ja: "野球帽", category: "CLOTHING" },
  1171: { en: "Smartwatch", ja: "スマートウォッチ", category: "ELECTRONICS" },
  1172: { en: "Dairy", ja: "乳製品", category: "FOOD" },
  1173: { en: "Bib", ja: "よだれかけ", category: "CLOTHING" },
  1174: { en: "Bowtie", ja: "蝶ネクタイ", category: "CLOTHING" },
  1175: { en: "Toy train", ja: "おもちゃの電車", category: "OBJECT" },
  1176: { en: "Dice", ja: "サイコロ", category: "OBJECT" },
  1177: { en: "Oven", ja: "オーブン", category: "ELECTRONICS" },
  1178: { en: "Dinosaur", ja: "恐竜", category: "ANIMAL" },
  1179: { en: "Display device", ja: "ディスプレイ", category: "ELECTRONICS" },
  1180: { en: "Goggles", ja: "ゴーグル", category: "CLOTHING" },
  1181: { en: "Wallet", ja: "財布", category: "OBJECT" },
  1182: { en: "Ratchet", ja: "ラチェット（工具）", category: "OBJECT" },
  1183: { en: "Couch", ja: "ソファ", category: "FURNITURE" },
  1184: { en: "Cricket ball", ja: "クリケットボール", category: "SPORTS" },
  1185: { en: "Winter melon", ja: "冬瓜", category: "FOOD" },
  1186: { en: "Spatula", ja: "ヘラ・フライ返し", category: "OBJECT" },
  1187: { en: "Cap", ja: "キャップ（帽子）", category: "CLOTHING" },
  1188: { en: "Whiteboard", ja: "ホワイトボード", category: "OBJECT" },
  1189: { en: "Pencil sharpener", ja: "鉛筆削り", category: "OBJECT" },
  1190: { en: "Door", ja: "ドア", category: "PLACE" },
  1191: { en: "Hat", ja: "帽子", category: "CLOTHING" },
  1192: { en: "Shower", ja: "シャワー", category: "FURNITURE" },
  1193: { en: "Lemur", ja: "キツネザル", category: "ANIMAL" },
  1194: { en: "Fedora", ja: "中折れ帽", category: "CLOTHING" },
  1195: { en: "Guacamole", ja: "ワカモレ", category: "FOOD" },
  1196: { en: "Scarf", ja: "スカーフ・マフラー", category: "CLOTHING" },
  1197: { en: "Dolphin", ja: "イルカ", category: "ANIMAL" },
  1198: { en: "Sombrero", ja: "ソンブレロ", category: "CLOTHING" },
  1199: { en: "Tin can", ja: "缶", category: "OBJECT" },
  1200: { en: "Mug", ja: "マグカップ", category: "OBJECT" },
  1201: { en: "Tap", ja: "蛇口", category: "FURNITURE" },
  1202: { en: "Harbor seal", ja: "ゼニガタアザラシ", category: "ANIMAL" },
  1203: { en: "Stretcher", ja: "担架", category: "OBJECT" },
  1204: { en: "Lock", ja: "錠前", category: "OBJECT" },
  1205: { en: "Roller skates", ja: "ローラースケート", category: "SPORTS" },
  1206: { en: "Coffee cup", ja: "コーヒーカップ", category: "OBJECT" },
  1207: { en: "Straw hat", ja: "麦わら帽子", category: "CLOTHING" },
  1208: { en: "Overall", ja: "オーバーオール", category: "CLOTHING" },
  1209: { en: "Cutting board", ja: "まな板", category: "OBJECT" },
  1210: { en: "Blender", ja: "ミキサー", category: "ELECTRONICS" },
  1211: { en: "Stove", ja: "コンロ", category: "ELECTRONICS" },
  1212: { en: "Stop sign", ja: "一時停止標識", category: "OBJECT" },
  1213: { en: "Volleyball", ja: "バレーボール", category: "SPORTS" },
  1214: { en: "Vase", ja: "花瓶", category: "OBJECT" },
  1215: { en: "Slow cooker", ja: "スロークッカー", category: "ELECTRONICS" },
  1216: { en: "Post-it note", ja: "付箋", category: "OBJECT" },
  1217: { en: "Wardrobe", ja: "洋服だんす", category: "FURNITURE" },
  1218: { en: "Pinwheel", ja: "風車（おもちゃ）", category: "OBJECT" },
  1219: { en: "Whisk", ja: "泡立て器", category: "OBJECT" },
  1220: { en: "Paper towel", ja: "ペーパータオル", category: "OBJECT" },
  1221: { en: "Food", ja: "食べ物", category: "FOOD" },
  1222: { en: "Sun hat", ja: "日よけ帽", category: "CLOTHING" },
  1223: { en: "Flying disc", ja: "フライングディスク", category: "SPORTS" },
  1224: { en: "Chandelier", ja: "シャンデリア", category: "FURNITURE" },
  1225: { en: "Skirt", ja: "スカート", category: "CLOTHING" },
  1226: { en: "Gas stove", ja: "ガスコンロ", category: "ELECTRONICS" },
  1227: { en: "Salt and pepper shakers", ja: "塩・こしょう入れ", category: "OBJECT" },
  1228: { en: "Mechanical fan", ja: "扇風機", category: "ELECTRONICS" },
  1229: { en: "Face powder", ja: "フェイスパウダー", category: "OBJECT" },
  1230: { en: "Fax", ja: "ファックス", category: "ELECTRONICS" },
  1231: { en: "Fruit", ja: "果物", category: "FOOD" },
  1232: { en: "French fries", ja: "フライドポテト", category: "FOOD" },
  1233: { en: "Nightstand", ja: "ナイトテーブル", category: "FURNITURE" },
  1234: { en: "Barrel", ja: "樽", category: "OBJECT" },
  1235: { en: "Kite", ja: "凧", category: "SPORTS" },
  1236: { en: "Tart", ja: "タルト", category: "FOOD" },
  1237: { en: "Treadmill", ja: "ランニングマシン", category: "SPORTS" },
  1238: { en: "Fox", ja: "キツネ", category: "ANIMAL" },
  1239: { en: "Throw pillow", ja: "クッション", category: "FURNITURE" },
  1240: { en: "Flag", ja: "旗", category: "OBJECT" },
  1241: { en: "Horn", ja: "ホルン", category: "ARTS" },
  1242: { en: "Window blind", ja: "ブラインド", category: "FURNITURE" },
  1243: { en: "Golf cart", ja: "ゴルフカート", category: "VEHICLE" },
  1244: { en: "Jacket", ja: "ジャケット", category: "CLOTHING" },
  1245: { en: "Jumpsuit", ja: "つなぎ・ジャンプスーツ", category: "CLOTHING" },
  1246: { en: "Egg", ja: "卵", category: "FOOD" },
  1247: { en: "Street light", ja: "街灯", category: "OBJECT" },
  1248: { en: "Guitar", ja: "ギター", category: "ARTS" },
  1249: { en: "Pillow", ja: "枕", category: "FURNITURE" },
  1250: { en: "Isopod", ja: "ダンゴムシ・ワラジムシ", category: "ANIMAL" },
  1251: { en: "Visor", ja: "サンバイザー", category: "CLOTHING" },
  1252: { en: "Grape", ja: "ぶどう", category: "FOOD" },
  1253: { en: "Bookcase", ja: "本棚", category: "FURNITURE" },
  1254: { en: "Candle hold", ja: "燭台", category: "OBJECT" },
  1255: { en: "Power outlet", ja: "コンセント", category: "ELECTRONICS" },
  1256: { en: "Panda", ja: "パンダ", category: "ANIMAL" },
  1257: { en: "Giraffe", ja: "キリン", category: "ANIMAL" },
  1258: { en: "Door handle", ja: "ドアノブ", category: "OBJECT" },
  1259: { en: "Rhinoceros", ja: "サイ", category: "ANIMAL" },
  1260: { en: "Bathtub", ja: "浴槽", category: "FURNITURE" },
  1261: { en: "Stroller", ja: "ベビーカー", category: "VEHICLE" },
  1262: { en: "Goldfish", ja: "金魚", category: "ANIMAL" },
  1263: { en: "Houseplant", ja: "観葉植物", category: "PLANT" },
  1264: { en: "Goat", ja: "ヤギ", category: "ANIMAL" },
  1265: { en: "Baseball bat", ja: "野球のバット", category: "SPORTS" },
  1266: { en: "Baseball glove", ja: "野球のグローブ", category: "SPORTS" },
  1267: { en: "Top", ja: "トップス", category: "CLOTHING" },
  1268: { en: "Grandfather clock", ja: "大型の振り子時計", category: "FURNITURE" },
  1269: { en: "Light switch", ja: "照明スイッチ", category: "ELECTRONICS" },
  1270: { en: "House", ja: "家", category: "PLACE" },
  1271: { en: "Stationary bicycle", ja: "エアロバイク", category: "SPORTS" },
  1272: { en: "Hammer", ja: "ハンマー", category: "OBJECT" },
  1273: { en: "Ceiling fan", ja: "シーリングファン", category: "ELECTRONICS" },
  1274: { en: "Keychain", ja: "キーホルダー", category: "OBJECT" },
  1275: { en: "Adhesive tape", ja: "粘着テープ", category: "OBJECT" },
  1276: { en: "Harp", ja: "ハープ", category: "ARTS" },
  1277: { en: "Blanket", ja: "毛布", category: "OBJECT" },
  1278: { en: "Sandal", ja: "サンダル", category: "CLOTHING" },
  1279: { en: "Bicycle helmet", ja: "自転車用ヘルメット", category: "CLOTHING" },
  1280: { en: "Handheld video game console", ja: "携帯ゲーム機", category: "ELECTRONICS" },
  1281: { en: "Saucer", ja: "ソーサー（受け皿）", category: "OBJECT" },
  1282: { en: "Teacup", ja: "ティーカップ", category: "OBJECT" },
  1283: { en: "Harpsichord", ja: "チェンバロ", category: "ARTS" },
  1284: { en: "Heater", ja: "ヒーター", category: "ELECTRONICS" },
  1285: { en: "Harmonica", ja: "ハーモニカ", category: "ARTS" },
  1286: { en: "Hamster", ja: "ハムスター", category: "ANIMAL" },
  1287: { en: "Hardware", ja: "金物・工具類", category: "OBJECT" },
  1288: { en: "Greeting card", ja: "グリーティングカード", category: "OBJECT" },
  1289: { en: "Curtain", ja: "カーテン", category: "FURNITURE" },
  1290: { en: "Kettle", ja: "やかん", category: "OBJECT" },
  1291: { en: "Bed", ja: "ベッド", category: "FURNITURE" },
  1292: { en: "Fireplace", ja: "暖炉", category: "FURNITURE" },
  1293: { en: "Scale", ja: "はかり", category: "OBJECT" },
  1294: { en: "Baseball", ja: "野球ボール", category: "SPORTS" },
  1295: { en: "Insect", ja: "昆虫", category: "ANIMAL" },
  1296: { en: "Luggage", ja: "手荷物", category: "OBJECT" },
  1297: { en: "Hair dryer", ja: "ヘアドライヤー", category: "ELECTRONICS" },
  1298: { en: "Indoor rower", ja: "ローイングマシン", category: "SPORTS" },
  1299: { en: "Food processor", ja: "フードプロセッサー", category: "ELECTRONICS" },
  1300: { en: "Jewellery", ja: "宝飾品", category: "CLOTHING" },
  1301: { en: "Refrigerator", ja: "冷蔵庫", category: "ELECTRONICS" },
  1302: { en: "Wood-burning stove", ja: "薪ストーブ", category: "FURNITURE" },
  1303: { en: "Punching bag", ja: "サンドバッグ", category: "SPORTS" },
  1304: { en: "Deep fryer", ja: "フライヤー", category: "ELECTRONICS" },
  1305: { en: "Common fig", ja: "いちじく", category: "FOOD" },
  1306: { en: "Cocktail shaker", ja: "カクテルシェーカー", category: "OBJECT" },
  1307: { en: "Jaguar", ja: "ジャガー", category: "ANIMAL" },
  1308: { en: "Golf ball", ja: "ゴルフボール", category: "SPORTS" },
  1309: { en: "Wireless router", ja: "無線ルーター", category: "ELECTRONICS" },
  1310: { en: "Alarm clock", ja: "目覚まし時計", category: "OBJECT" },
  1311: { en: "Filing cabinet", ja: "ファイルキャビネット", category: "FURNITURE" },
  1312: { en: "Artichoke", ja: "アーティチョーク", category: "FOOD" },
  1313: { en: "Outerwear", ja: "上着", category: "CLOTHING" },
  1314: { en: "Cufflink", ja: "カフスボタン", category: "CLOTHING" },
  1315: { en: "Motorcycle", ja: "オートバイ", category: "VEHICLE" },
  1316: { en: "Table", ja: "テーブル", category: "FURNITURE" },
  1317: { en: "Tableware", ja: "食器", category: "OBJECT" },
  1318: { en: "Kangaroo", ja: "カンガルー", category: "ANIMAL" },
  1319: { en: "Koala", ja: "コアラ", category: "ANIMAL" },
  1320: { en: "Knife", ja: "ナイフ", category: "OBJECT" },
  1321: { en: "Bottle", ja: "ボトル・瓶", category: "OBJECT" },
  1322: { en: "Bottle opener", ja: "栓抜き", category: "OBJECT" },
  1323: { en: "Electric toothbrush", ja: "電動歯ブラシ", category: "ELECTRONICS" },
  1324: { en: "Lynx", ja: "オオヤマネコ", category: "ANIMAL" },
  1325: { en: "Receipt", ja: "レシート", category: "OBJECT" },
  1326: { en: "Lighthouse", ja: "灯台", category: "PLACE" },
  1327: { en: "Dumbbell", ja: "ダンベル", category: "SPORTS" },
  1328: { en: "Bowl", ja: "ボウル・どんぶり", category: "OBJECT" },
  1329: { en: "Lizard", ja: "トカゲ", category: "ANIMAL" },
  1330: { en: "Head-mounted display", ja: "ヘッドマウントディスプレイ", category: "ELECTRONICS" },
  1331: { en: "Lego", ja: "ブロック玩具", category: "OBJECT" },
  1332: { en: "Check", ja: "小切手", category: "OBJECT" },
  1333: { en: "Billiard table", ja: "ビリヤード台", category: "SPORTS" },
  1334: { en: "Mouse", ja: "マウス（ネズミ／パソコン）", category: "OBJECT" },
  1335: { en: "Swim cap", ja: "水泳帽", category: "CLOTHING" },
  1336: { en: "Frying pan", ja: "フライパン", category: "OBJECT" },
  1337: { en: "Snowplow", ja: "除雪車", category: "VEHICLE" },
  1338: { en: "Bathroom cabinet", ja: "洗面所の戸棚", category: "FURNITURE" },
  1339: { en: "Bust", ja: "胸像", category: "ARTS" },
  1340: { en: "Waffle iron", ja: "ワッフルメーカー", category: "ELECTRONICS" },
  1341: { en: "Milk", ja: "牛乳", category: "FOOD" },
  1342: { en: "Ring binder", ja: "リングバインダー", category: "OBJECT" },
  1343: { en: "Plate", ja: "皿", category: "OBJECT" },
  1344: { en: "Mobile phone", ja: "携帯電話", category: "ELECTRONICS" },
  1345: { en: "Baked goods", ja: "焼き菓子・パン", category: "FOOD" },
  1346: { en: "Mushroom", ja: "きのこ", category: "PLANT" },
  1347: { en: "Crutch", ja: "松葉づえ", category: "OBJECT" },
  1348: { en: "Mirror", ja: "鏡", category: "FURNITURE" },
  1349: { en: "Pitcher", ja: "水差し（ピッチャー）", category: "OBJECT" },
  1350: { en: "Lifejacket", ja: "救命胴衣", category: "CLOTHING" },
  1351: { en: "Pencil case", ja: "筆箱", category: "OBJECT" },
  1352: { en: "Sweatpants", ja: "スウェットパンツ", category: "CLOTHING" },
  1353: { en: "Musical keyboard", ja: "鍵盤楽器", category: "ARTS" },
  1354: { en: "Scoreboard", ja: "スコアボード", category: "SPORTS" },
  1355: { en: "Briefcase", ja: "ブリーフケース", category: "OBJECT" },
  1356: { en: "Kitchen knife", ja: "包丁", category: "OBJECT" },
  1357: { en: "Magazine", ja: "雑誌", category: "OBJECT" },
  1358: { en: "Table tennis racket", ja: "卓球のラケット", category: "SPORTS" },
  1359: { en: "Portable media player", ja: "携帯音楽プレーヤー", category: "ELECTRONICS" },
  1360: { en: "Hoodie", ja: "パーカー", category: "CLOTHING" },
  1361: { en: "Nail", ja: "釘", category: "OBJECT" },
  1362: { en: "Tennis ball", ja: "テニスボール", category: "SPORTS" },
  1363: { en: "Oboe", ja: "オーボエ", category: "ARTS" },
  1364: { en: "Chest of drawers", ja: "たんす", category: "FURNITURE" },
  1365: { en: "Ostrich", ja: "ダチョウ", category: "ANIMAL" },
  1366: { en: "Painting", ja: "絵画", category: "ARTS" },
  1367: { en: "Piano", ja: "ピアノ", category: "ARTS" },
  1368: { en: "Playing card", ja: "トランプ", category: "OBJECT" },
  1369: { en: "Plant", ja: "植物", category: "PLANT" },
  1370: { en: "Passport", ja: "パスポート", category: "OBJECT" },
  1371: { en: "Potato", ja: "じゃがいも", category: "FOOD" },
  1372: { en: "Pasta", ja: "パスタ", category: "FOOD" },
  1373: { en: "Penguin", ja: "ペンギン", category: "ANIMAL" },
  1374: { en: "Pumpkin", ja: "かぼちゃ", category: "FOOD" },
  1375: { en: "Pear", ja: "洋なし", category: "FOOD" },
  1376: { en: "Infant bed", ja: "ベビーベッド", category: "FURNITURE" },
  1377: { en: "Polar bear", ja: "ホッキョクグマ", category: "ANIMAL" },
  1378: { en: "Mixer", ja: "ハンドミキサー", category: "ELECTRONICS" },
  1379: { en: "Cupboard", ja: "食器棚", category: "FURNITURE" },
  1380: { en: "Jacuzzi", ja: "ジャグジー", category: "FURNITURE" },
  1381: { en: "Pizza", ja: "ピザ", category: "FOOD" },
  1382: { en: "Pig", ja: "ブタ", category: "ANIMAL" },
  1383: { en: "Digital clock", ja: "デジタル時計", category: "ELECTRONICS" },
  1384: { en: "Snowboard", ja: "スノーボード", category: "SPORTS" },
  1385: { en: "Skateboard", ja: "スケートボード", category: "SPORTS" },
  1386: { en: "Rifle", ja: "ライフル", category: "OBJECT" },
  1387: { en: "Lipstick", ja: "口紅", category: "OBJECT" },
  1388: { en: "Raven", ja: "カラス", category: "ANIMAL" },
  1389: { en: "High heels", ja: "ハイヒール", category: "CLOTHING" },
  1390: { en: "Red panda", ja: "レッサーパンダ", category: "ANIMAL" },
  1391: { en: "Rabbit", ja: "ウサギ", category: "ANIMAL" },
  1392: { en: "Sculpture", ja: "彫刻", category: "ARTS" },
  1393: { en: "Saxophone", ja: "サックス", category: "ARTS" },
  1394: { en: "Shotgun", ja: "散弾銃", category: "OBJECT" },
  1395: { en: "Submarine sandwich", ja: "サブマリンサンド", category: "FOOD" },
  1396: { en: "Ship", ja: "船", category: "VEHICLE" },
  1397: { en: "Shoe", ja: "靴", category: "CLOTHING" },
  1398: { en: "Sword", ja: "剣・刀", category: "OBJECT" },
  1399: { en: "Picture frame", ja: "額縁", category: "OBJECT" },
  1400: { en: "Sushi", ja: "寿司", category: "FOOD" },
  1401: { en: "Loveseat", ja: "二人掛けソファ", category: "FURNITURE" },
  1402: { en: "Ski", ja: "スキー板", category: "SPORTS" },
  1403: { en: "Squirrel", ja: "リス", category: "ANIMAL" },
  1404: { en: "Tripod", ja: "三脚", category: "OBJECT" },
  1405: { en: "Stethoscope", ja: "聴診器", category: "OBJECT" },
  1406: { en: "Submarine", ja: "潜水艦", category: "VEHICLE" },
  1407: { en: "Scorpion", ja: "サソリ", category: "ANIMAL" },
  1408: { en: "Segway", ja: "セグウェイ", category: "VEHICLE" },
  1409: { en: "Weight training bench", ja: "トレーニングベンチ", category: "SPORTS" },
  1410: { en: "Snake", ja: "ヘビ", category: "ANIMAL" },
  1411: { en: "Coffee table", ja: "ローテーブル", category: "FURNITURE" },
  1412: { en: "Video game console", ja: "ゲーム機", category: "ELECTRONICS" },
  1413: { en: "Sheep", ja: "ヒツジ", category: "ANIMAL" },
  1414: { en: "Single-lens reflex camera", ja: "一眼レフカメラ", category: "ELECTRONICS" },
  1415: { en: "Television", ja: "テレビ", category: "ELECTRONICS" },
  1416: { en: "Trombone", ja: "トロンボーン", category: "ARTS" },
  1417: { en: "Tank", ja: "戦車", category: "VEHICLE" },
  1418: { en: "Taco", ja: "タコス", category: "FOOD" },
  1419: { en: "Telephone", ja: "電話機", category: "ELECTRONICS" },
  1420: { en: "Torch", ja: "たいまつ", category: "OBJECT" },
  1421: { en: "Tiger", ja: "トラ", category: "ANIMAL" },
  1422: { en: "Strawberry", ja: "いちご", category: "FOOD" },
  1423: { en: "Trumpet", ja: "トランペット", category: "ARTS" },
  1424: { en: "Tomato", ja: "トマト", category: "FOOD" },
  1425: { en: "Train", ja: "電車・列車", category: "VEHICLE" },
  1426: { en: "Pants", ja: "ズボン", category: "CLOTHING" },
  1427: { en: "cup", ja: "カップ", category: "OBJECT" },
  1428: { en: "Football helmet", ja: "アメフト用ヘルメット", category: "SPORTS" },
  1429: { en: "Truck", ja: "トラック", category: "VEHICLE" },
  1430: { en: "Measuring cup", ja: "計量カップ", category: "OBJECT" },
  1431: { en: "Coffeemaker", ja: "コーヒーメーカー", category: "ELECTRONICS" },
  1432: { en: "Violin", ja: "バイオリン", category: "ARTS" },
  1433: { en: "Vacuum", ja: "掃除機", category: "ELECTRONICS" },
  1434: { en: "Handbag", ja: "ハンドバッグ", category: "CLOTHING" },
  1435: { en: "Weapon", ja: "武器", category: "OBJECT" },
  1436: { en: "Wheel", ja: "車輪", category: "VEHICLE" },
  1437: { en: "Worm", ja: "ミミズ", category: "ANIMAL" },
  1438: { en: "Wok", ja: "中華鍋", category: "OBJECT" },
  1439: { en: "Whale", ja: "クジラ", category: "ANIMAL" },
  1440: { en: "Zebra", ja: "シマウマ", category: "ANIMAL" },
  1441: { en: "Carseat", ja: "チャイルドシート", category: "VEHICLE" },
  1442: { en: "Jug", ja: "水差し", category: "OBJECT" },
  1443: { en: "Light fixture", ja: "照明器具", category: "FURNITURE" },
  1444: { en: "Pizza cutter", ja: "ピザカッター", category: "OBJECT" },
  1445: { en: "Cream", ja: "クリーム", category: "FOOD" },
  1446: { en: "Monkey", ja: "サル", category: "ANIMAL" },
  1447: { en: "Lion", ja: "ライオン", category: "ANIMAL" },
  1448: { en: "Bread", ja: "パン", category: "FOOD" },
  1449: { en: "Chicken", ja: "ニワトリ", category: "ANIMAL" },
  1450: { en: "Eagle", ja: "ワシ", category: "ANIMAL" },
  1451: { en: "Helicopter", ja: "ヘリコプター", category: "VEHICLE" },
  1452: { en: "Owl", ja: "フクロウ", category: "ANIMAL" },
  1453: { en: "Duck", ja: "カモ・アヒル", category: "ANIMAL" },
  1454: { en: "Turtle", ja: "カメ", category: "ANIMAL" },
  1455: { en: "Hippopotamus", ja: "カバ", category: "ANIMAL" },
  1456: { en: "Crocodile", ja: "ワニ", category: "ANIMAL" },
  1457: { en: "Toilet", ja: "トイレ（便器）", category: "FURNITURE" },
  1458: { en: "Garden gnome", ja: "庭の小人の置物", category: "OBJECT" },
  1459: { en: "Toilet paper", ja: "トイレットペーパー", category: "OBJECT" },
  1460: { en: "Squid", ja: "イカ", category: "ANIMAL" },
  1461: { en: "Clothing", ja: "衣服", category: "CLOTHING" },
  1462: { en: "Footwear", ja: "履物", category: "CLOTHING" },
  1463: { en: "Lemon", ja: "レモン", category: "FOOD" },
  1464: { en: "Sneakers", ja: "スニーカー", category: "CLOTHING" },
  1465: { en: "Spider", ja: "クモ", category: "ANIMAL" },
  1466: { en: "Deer", ja: "シカ", category: "ANIMAL" },
  1467: { en: "Ring", ja: "指輪", category: "CLOTHING" },
  1468: { en: "Frog", ja: "カエル", category: "ANIMAL" },
  1469: { en: "Banana", ja: "バナナ", category: "FOOD" },
  1470: { en: "Rocket", ja: "ロケット", category: "SPACE" },
  1471: { en: "Wine glass", ja: "ワイングラス", category: "OBJECT" },
  1472: { en: "Oyster", ja: "カキ（貝）", category: "FOOD" },
  1473: { en: "Chisel", ja: "のみ（工具）", category: "OBJECT" },
  1474: { en: "Ant", ja: "アリ", category: "ANIMAL" },
  1475: { en: "Countertop", ja: "調理台", category: "FURNITURE" },
  1476: { en: "Optical disc", ja: "光ディスク", category: "ELECTRONICS" },
  1477: { en: "Tablet computer", ja: "タブレット", category: "ELECTRONICS" },
  1478: { en: "Waste container", ja: "ごみ箱", category: "OBJECT" },
  1479: { en: "Electronic device", ja: "電子機器", category: "ELECTRONICS" },
  1480: { en: "Book", ja: "本", category: "OBJECT" },
  1481: { en: "Elephant", ja: "ゾウ", category: "ANIMAL" },
  1482: { en: "Robotic vacuum cleaner", ja: "ロボット掃除機", category: "ELECTRONICS" },
  1483: { en: "Shark", ja: "サメ", category: "ANIMAL" },
  1484: { en: "Toy block", ja: "積み木", category: "OBJECT" },
  1485: { en: "Candle", ja: "ろうそく", category: "OBJECT" },
  1486: { en: "Leopard", ja: "ヒョウ", category: "ANIMAL" },
  1487: { en: "Axe", ja: "斧", category: "OBJECT" },
  1488: { en: "Hand dryer", ja: "ハンドドライヤー", category: "ELECTRONICS" },
  1489: { en: "Soap dispenser", ja: "ソープディスペンサー", category: "OBJECT" },
  1490: { en: "Porcupine", ja: "ヤマアラシ", category: "ANIMAL" },
  1491: { en: "Flower", ja: "花", category: "PLANT" },
  1492: { en: "Furniture", ja: "家具", category: "FURNITURE" },
  1493: { en: "Canary", ja: "カナリア", category: "ANIMAL" },
  1494: { en: "Cheetah", ja: "チーター", category: "ANIMAL" },
  1495: { en: "Hamburger", ja: "ハンバーガー", category: "FOOD" },
  1496: { en: "Satchel", ja: "ショルダーバッグ", category: "CLOTHING" },
  1497: { en: "Loudspeaker", ja: "スピーカー", category: "ELECTRONICS" },
  1498: { en: "Building", ja: "建物", category: "PLACE" },
  1499: { en: "Fish", ja: "魚", category: "ANIMAL" },
  1500: { en: "Lobster", ja: "ロブスター", category: "ANIMAL" },
  1501: { en: "Asparagus", ja: "アスパラガス", category: "FOOD" },
  1502: { en: "Hedgehog", ja: "ハリネズミ", category: "ANIMAL" },
  1503: { en: "Airplane", ja: "飛行機", category: "VEHICLE" },
  1504: { en: "Spoon", ja: "スプーン", category: "OBJECT" },
  1505: { en: "Otter", ja: "カワウソ", category: "ANIMAL" },
  1506: { en: "Bull", ja: "雄牛", category: "ANIMAL" },
  1507: { en: "Underpants", ja: "下着（パンツ）", category: "CLOTHING" },
  1508: { en: "Projector", ja: "プロジェクター", category: "ELECTRONICS" },
  1509: { en: "Bench", ja: "ベンチ", category: "FURNITURE" },
  1510: { en: "Driver's license", ja: "運転免許証", category: "OBJECT" },
  1511: { en: "Ice cream", ja: "アイスクリーム", category: "FOOD" },
  1512: { en: "Caterpillar", ja: "毛虫・イモムシ", category: "ANIMAL" },
  1513: { en: "Butterfly", ja: "チョウ", category: "ANIMAL" },
  1514: { en: "Parachute", ja: "パラシュート", category: "SPORTS" },
  1515: { en: "Orange", ja: "オレンジ", category: "FOOD" },
  1516: { en: "Antelope", ja: "レイヨウ", category: "ANIMAL" },
  1517: { en: "Beaker", ja: "ビーカー", category: "OBJECT" },
  1518: { en: "Romper", ja: "ロンパース", category: "CLOTHING" },
  1519: { en: "Window", ja: "窓", category: "PLACE" },
  1520: { en: "Castle", ja: "城", category: "PLACE" },
  1521: { en: "Jellyfish", ja: "クラゲ", category: "ANIMAL" },
  1522: { en: "Moths and butterflies", ja: "ガ・チョウ", category: "ANIMAL" },
  1523: { en: "Goose", ja: "ガチョウ", category: "ANIMAL" },
  1524: { en: "Mule", ja: "ラバ", category: "ANIMAL" },
  1525: { en: "Swan", ja: "白鳥", category: "ANIMAL" },
  1526: { en: "Peach", ja: "桃", category: "FOOD" },
  1527: { en: "Coconut", ja: "ココナッツ", category: "FOOD" },
  1528: { en: "Scooter", ja: "スクーター・キックボード", category: "VEHICLE" },
  1529: { en: "Soccer ball", ja: "サッカーボール", category: "SPORTS" },
  1530: { en: "Raccoon", ja: "アライグマ", category: "ANIMAL" },
  1531: { en: "Fork", ja: "フォーク", category: "OBJECT" },
  1532: { en: "Lamp", ja: "ランプ・電気スタンド", category: "FURNITURE" },
  1533: { en: "Camera", ja: "カメラ", category: "ELECTRONICS" },
  1534: { en: "Squash", ja: "カボチャ類（スクワッシュ）", category: "FOOD" },
  1535: { en: "Racket", ja: "ラケット", category: "SPORTS" },
  1536: { en: "Vegetable", ja: "野菜", category: "FOOD" },
  1537: { en: "Diaper", ja: "おむつ", category: "CLOTHING" },
  1538: { en: "Unicycle", ja: "一輪車", category: "VEHICLE" },
  1539: { en: "Falcon", ja: "ハヤブサ", category: "ANIMAL" },
  1540: { en: "Apron", ja: "エプロン", category: "CLOTHING" },
  1541: { en: "Chime", ja: "チャイム・風鈴", category: "ARTS" },
  1542: { en: "Snail", ja: "カタツムリ", category: "ANIMAL" },
  1543: { en: "Cabbage", ja: "キャベツ", category: "FOOD" },
  1544: { en: "Carrot", ja: "にんじん", category: "FOOD" },
  1545: { en: "Mango", ja: "マンゴー", category: "FOOD" },
  1546: { en: "Jeans", ja: "ジーンズ", category: "CLOTHING" },
  1547: { en: "Flowerpot", ja: "植木鉢", category: "OBJECT" },
  1548: { en: "Pineapple", ja: "パイナップル", category: "FOOD" },
  1549: { en: "Stool", ja: "スツール", category: "FURNITURE" },
  1550: { en: "Basketball", ja: "バスケットボール", category: "SPORTS" },
  1551: { en: "Envelope", ja: "封筒", category: "OBJECT" },
  1552: { en: "Cake", ja: "ケーキ", category: "FOOD" },
  1553: { en: "Dragonfly", ja: "トンボ", category: "ANIMAL" },
  1554: { en: "Microwave oven", ja: "電子レンジ", category: "ELECTRONICS" },
  1555: { en: "Honeycomb", ja: "ハチの巣", category: "NATURE" },
  1556: { en: "Drone", ja: "ドローン", category: "ELECTRONICS" },
  1557: { en: "Sea lion", ja: "アシカ", category: "ANIMAL" },
  1558: { en: "Barcode", ja: "バーコード", category: "OBJECT" },
  1559: { en: "Lady bug", ja: "テントウムシ", category: "ANIMAL" },
  1560: { en: "Shelf", ja: "棚", category: "FURNITURE" },
  1561: { en: "Watch", ja: "腕時計", category: "CLOTHING" },
  1562: { en: "Candy", ja: "キャンディ・お菓子", category: "FOOD" },
  1563: { en: "Salad", ja: "サラダ", category: "FOOD" },
  1564: { en: "Parrot", ja: "オウム", category: "ANIMAL" },
  1565: { en: "Handgun", ja: "拳銃", category: "OBJECT" },
  1566: { en: "Sparrow", ja: "スズメ", category: "ANIMAL" },
  1567: { en: "Van", ja: "バン", category: "VEHICLE" },
  1568: { en: "Ice skate", ja: "アイススケート靴", category: "SPORTS" },
  1569: { en: "Grinder", ja: "グラインダー", category: "OBJECT" },
  1570: { en: "Spice rack", ja: "スパイスラック", category: "FURNITURE" },
  1571: { en: "Light bulb", ja: "電球", category: "ELECTRONICS" },
  1572: { en: "Toy vehicle", ja: "おもちゃの乗り物", category: "OBJECT" },
  1573: { en: "Corded phone", ja: "固定電話", category: "ELECTRONICS" },
  1574: { en: "Dartboard", ja: "ダーツボード", category: "SPORTS" },
  1575: { en: "Tennis racket", ja: "テニスラケット", category: "SPORTS" },
  1576: { en: "Wall clock", ja: "掛け時計", category: "FURNITURE" },
  1577: { en: "Serving tray", ja: "お盆", category: "OBJECT" },
  1578: { en: "Kitchen & dining room table", ja: "ダイニングテーブル", category: "FURNITURE" },
  1579: { en: "Dog bed", ja: "犬用ベッド", category: "FURNITURE" },
  1580: { en: "Cake stand", ja: "ケーキスタンド", category: "OBJECT" },
  1581: { en: "Baby carrier", ja: "抱っこひも", category: "OBJECT" },
  1582: { en: "Facial tissue holder", ja: "ティッシュケース", category: "OBJECT" },
  1583: { en: "Pressure cooker", ja: "圧力鍋", category: "OBJECT" },
  1584: { en: "Shipping box", ja: "段ボール箱", category: "OBJECT" },
  1585: { en: "Kitchen Appliance", ja: "キッチン家電", category: "ELECTRONICS" },
  1586: { en: "Tire", ja: "タイヤ", category: "VEHICLE" },
  1587: { en: "Ruler", ja: "定規", category: "OBJECT" },
  1588: { en: "Luggage & bags", ja: "かばん類", category: "OBJECT" },
  1589: { en: "Microphone", ja: "マイク", category: "ELECTRONICS" },
  1590: { en: "Broccoli", ja: "ブロッコリー", category: "FOOD" },
  1591: { en: "Umbrella", ja: "傘", category: "OBJECT" },
  1592: { en: "Pastry", ja: "ペストリー", category: "FOOD" },
  1593: { en: "Grapefruit", ja: "グレープフルーツ", category: "FOOD" },
  1594: { en: "Eyewear", ja: "アイウェア", category: "CLOTHING" },
  1595: { en: "Band-aid", ja: "ばんそうこう", category: "OBJECT" },
  1596: { en: "Bell pepper", ja: "ピーマン", category: "FOOD" },
  1597: { en: "Turkey", ja: "七面鳥", category: "ANIMAL" },
  1598: { en: "Pomegranate", ja: "ざくろ", category: "FOOD" },
  1599: { en: "Doughnut", ja: "ドーナツ", category: "FOOD" },
  1600: { en: "Glasses", ja: "眼鏡", category: "CLOTHING" },
  1601: { en: "Pen", ja: "ペン", category: "OBJECT" },
  1602: { en: "Car", ja: "自動車", category: "VEHICLE" },
  1603: { en: "Skunk", ja: "スカンク", category: "ANIMAL" },
  1604: { en: "Teddy bear", ja: "テディベア", category: "OBJECT" },
  1605: { en: "Watermelon", ja: "スイカ", category: "FOOD" },
  1606: { en: "Cantaloupe", ja: "メロン", category: "FOOD" },
  1607: { en: "Dishwasher", ja: "食器洗い機", category: "ELECTRONICS" },
  1608: { en: "Flute", ja: "フルート", category: "ARTS" },
  1609: { en: "Sandwich", ja: "サンドイッチ", category: "FOOD" },
  1610: { en: "Bladeless fan", ja: "羽根のない扇風機", category: "ELECTRONICS" },
  1611: { en: "Shrimp", ja: "エビ", category: "FOOD" },
  1612: { en: "Sewing machine", ja: "ミシン", category: "ELECTRONICS" },
  1613: { en: "Binoculars", ja: "双眼鏡", category: "OBJECT" },
  1614: { en: "Rays and skates", ja: "エイ", category: "ANIMAL" },
  1615: { en: "Accordion", ja: "アコーディオン", category: "ARTS" },
  1616: { en: "Crab", ja: "カニ", category: "ANIMAL" },
  1617: { en: "Bag", ja: "かばん", category: "CLOTHING" },
  1618: { en: "Crown", ja: "王冠", category: "CLOTHING" },
  1619: { en: "Seahorse", ja: "タツノオトシゴ", category: "ANIMAL" },
  1620: { en: "Perfume", ja: "香水", category: "OBJECT" },
  1621: { en: "Alpaca", ja: "アルパカ", category: "ANIMAL" },
  1622: { en: "Canoe", ja: "カヌー", category: "VEHICLE" },
  1623: { en: "Game controller", ja: "ゲームコントローラー", category: "ELECTRONICS" },
  1624: { en: "Remote control", ja: "リモコン", category: "ELECTRONICS" },
  1625: { en: "Wheelchair", ja: "車椅子", category: "VEHICLE" },
  1626: { en: "Rugby ball", ja: "ラグビーボール", category: "SPORTS" },
  1627: { en: "Armadillo", ja: "アルマジロ", category: "ANIMAL" },
  1628: { en: "Maracas", ja: "マラカス", category: "ARTS" },
  1629: { en: "Activity tracker", ja: "活動量計", category: "ELECTRONICS" },
  1630: { en: "Helmet", ja: "ヘルメット", category: "CLOTHING" },
};
