export type LabelCategory =
  | "ACTION"
  | "ANIMAL"
  | "ARTS"
  | "BODY"
  | "CHARACTER"
  | "CLOTHING"
  | "CONCEPT"
  | "ELECTRONICS"
  | "EVENT"
  | "FOOD"
  | "FURNITURE"
  | "IMAGE"
  | "MATERIAL"
  | "NATURE"
  | "OBJECT"
  | "PEOPLE"
  | "PLACE"
  | "PLANT"
  | "SPACE"
  | "SPORTS"
  | "VEHICLE"
  | "WEATHER";

export type MlkitLabel = { en: string; ja: string; category: LabelCategory };

export function labelText(label: MlkitLabel, uiLocale: string): string {
  return uiLocale === "ja" ? label.ja : label.en;
}

export const MLKIT_LABELS: Readonly<Record<number, MlkitLabel>> = {
  0: { en: "Team", ja: "チーム", category: "PEOPLE" },
  1: { en: "Bonfire", ja: "たき火", category: "NATURE" },
  2: { en: "Comics", ja: "漫画", category: "ARTS" },
  3: { en: "Himalayan", ja: "ヒマラヤン（猫の品種）", category: "ANIMAL" },
  4: { en: "Iceberg", ja: "氷山", category: "NATURE" },
  5: { en: "Bento", ja: "弁当", category: "FOOD" },
  7: { en: "Sink", ja: "流し台・洗面台", category: "FURNITURE" },
  8: { en: "Toy", ja: "おもちゃ", category: "OBJECT" },
  9: { en: "Statue", ja: "像・彫像", category: "ARTS" },
  10: { en: "Cheeseburger", ja: "チーズバーガー", category: "FOOD" },
  11: { en: "Tractor", ja: "トラクター", category: "VEHICLE" },
  12: { en: "Sled", ja: "そり", category: "SPORTS" },
  13: { en: "Aquarium", ja: "水族館・水槽", category: "PLACE" },
  14: { en: "Circus", ja: "サーカス", category: "EVENT" },
  16: { en: "Sitting", ja: "座っている", category: "ACTION" },
  17: { en: "Beard", ja: "あごひげ", category: "BODY" },
  18: { en: "Bridge", ja: "橋", category: "PLACE" },
  19: { en: "Tights", ja: "タイツ", category: "CLOTHING" },
  20: { en: "Bird", ja: "鳥", category: "ANIMAL" },
  21: { en: "Rafting", ja: "ラフティング", category: "SPORTS" },
  22: { en: "Park", ja: "公園", category: "PLACE" },
  24: { en: "Factory", ja: "工場", category: "PLACE" },
  25: { en: "Graduation", ja: "卒業式", category: "EVENT" },
  26: { en: "Porcelain", ja: "磁器", category: "MATERIAL" },
  27: { en: "Twig", ja: "小枝", category: "PLANT" },
  28: { en: "Petal", ja: "花びら", category: "PLANT" },
  29: { en: "Cushion", ja: "クッション", category: "FURNITURE" },
  30: { en: "Sunglasses", ja: "サングラス", category: "CLOTHING" },
  31: { en: "Infrastructure", ja: "インフラ・社会基盤", category: "PLACE" },
  32: { en: "Ferris wheel", ja: "観覧車", category: "PLACE" },
  33: { en: "Pomacentridae", ja: "スズメダイ科（熱帯魚）", category: "ANIMAL" },
  34: { en: "Wetsuit", ja: "ウェットスーツ", category: "CLOTHING" },
  35: {
    en: "Shetland sheepdog",
    ja: "シェットランド・シープドッグ",
    category: "ANIMAL",
  },
  36: { en: "Brig", ja: "ブリッグ（2本マストの帆船）", category: "VEHICLE" },
  37: { en: "Watercolor paint", ja: "水彩画・水彩絵具", category: "ARTS" },
  38: { en: "Competition", ja: "競技・大会", category: "SPORTS" },
  39: { en: "Cliff", ja: "崖", category: "NATURE" },
  40: { en: "Badminton", ja: "バドミントン", category: "SPORTS" },
  41: { en: "Safari", ja: "サファリ", category: "NATURE" },
  42: { en: "Bicycle", ja: "自転車", category: "VEHICLE" },
  43: { en: "Stadium", ja: "競技場", category: "PLACE" },
  45: { en: "Boat", ja: "ボート", category: "VEHICLE" },
  46: { en: "Smile", ja: "笑顔", category: "PEOPLE" },
  47: { en: "Surfboard", ja: "サーフボード", category: "SPORTS" },
  48: { en: "Fast food", ja: "ファストフード", category: "FOOD" },
  49: { en: "Sunset", ja: "夕焼け・日没", category: "WEATHER" },
  50: { en: "Hot dog", ja: "ホットドッグ", category: "FOOD" },
  51: { en: "Shorts", ja: "短パン", category: "CLOTHING" },
  52: { en: "Bus", ja: "バス", category: "VEHICLE" },
  53: { en: "Bullfighting", ja: "闘牛", category: "EVENT" },
  54: { en: "Sky", ja: "空", category: "WEATHER" },
  55: { en: "Gerbil", ja: "スナネズミ", category: "ANIMAL" },
  56: { en: "Rock", ja: "岩", category: "NATURE" },
  57: { en: "Interaction", ja: "交流・触れ合い", category: "CONCEPT" },
  58: { en: "Dress", ja: "ドレス・ワンピース", category: "CLOTHING" },
  59: { en: "Toe", ja: "つま先", category: "BODY" },
  61: { en: "Bear", ja: "クマ", category: "ANIMAL" },
  62: { en: "Eating", ja: "食べている", category: "ACTION" },
  63: { en: "Tower", ja: "塔", category: "PLACE" },
  64: { en: "Brick", ja: "レンガ", category: "MATERIAL" },
  65: { en: "Junk", ja: "ジャンク（がらくた）", category: "OBJECT" },
  66: { en: "Person", ja: "人", category: "PEOPLE" },
  67: { en: "Windsurfing", ja: "ウィンドサーフィン", category: "SPORTS" },
  68: { en: "Swimwear", ja: "水着", category: "CLOTHING" },
  69: { en: "Roller", ja: "ローラー", category: "OBJECT" },
  70: { en: "Camping", ja: "キャンプ", category: "SPORTS" },
  71: { en: "Playground", ja: "遊び場・遊具", category: "PLACE" },
  72: { en: "Bathroom", ja: "浴室・トイレ", category: "PLACE" },
  73: { en: "Laugh", ja: "笑い", category: "PEOPLE" },
  74: { en: "Balloon", ja: "風船", category: "OBJECT" },
  75: { en: "Concert", ja: "コンサート", category: "EVENT" },
  76: { en: "Prom", ja: "プロム（卒業ダンスパーティー）", category: "EVENT" },
  77: { en: "Construction", ja: "建設・工事", category: "PLACE" },
  78: { en: "Product", ja: "製品", category: "OBJECT" },
  79: { en: "Reef", ja: "サンゴ礁", category: "NATURE" },
  80: { en: "Picnic", ja: "ピクニック", category: "SPORTS" },
  81: { en: "Wreath", ja: "リース・花輪", category: "OBJECT" },
  82: { en: "Wheelbarrow", ja: "手押し車", category: "OBJECT" },
  83: {
    en: "Boxer",
    ja: "ボクサー（犬種・ボクシング選手）",
    category: "ANIMAL",
  },
  84: { en: "Necklace", ja: "ネックレス", category: "CLOTHING" },
  85: { en: "Bracelet", ja: "ブレスレット", category: "CLOTHING" },
  86: { en: "Casino", ja: "カジノ", category: "PLACE" },
  87: { en: "Windshield", ja: "フロントガラス", category: "VEHICLE" },
  88: { en: "Stairs", ja: "階段", category: "PLACE" },
  89: { en: "Computer", ja: "コンピューター", category: "ELECTRONICS" },
  90: { en: "Cookware and bakeware", ja: "調理器具", category: "OBJECT" },
  91: { en: "Monochrome", ja: "モノクロ（白黒画像）", category: "IMAGE" },
  92: { en: "Chair", ja: "椅子", category: "FURNITURE" },
  93: { en: "Poster", ja: "ポスター", category: "IMAGE" },
  94: { en: "Bar", ja: "バー・酒場", category: "PLACE" },
  95: { en: "Shipwreck", ja: "難破船", category: "VEHICLE" },
  96: { en: "Pier", ja: "桟橋", category: "PLACE" },
  97: { en: "Community", ja: "コミュニティ", category: "CONCEPT" },
  98: { en: "Caving", ja: "洞窟探検", category: "SPORTS" },
  99: { en: "Cave", ja: "洞窟", category: "NATURE" },
  100: { en: "Tie", ja: "ネクタイ", category: "CLOTHING" },
  101: { en: "Cabinetry", ja: "戸棚・キャビネット類", category: "FURNITURE" },
  102: { en: "Underwater", ja: "水中", category: "NATURE" },
  103: { en: "Clown", ja: "ピエロ", category: "PEOPLE" },
  104: { en: "Nightclub", ja: "ナイトクラブ", category: "PLACE" },
  105: { en: "Cycling", ja: "サイクリング", category: "SPORTS" },
  106: { en: "Comet", ja: "彗星", category: "SPACE" },
  107: { en: "Mortarboard", ja: "角帽", category: "CLOTHING" },
  108: { en: "Track", ja: "陸上トラック・線路", category: "PLACE" },
  109: { en: "Christmas", ja: "クリスマス", category: "EVENT" },
  110: { en: "Church", ja: "教会", category: "PLACE" },
  111: { en: "Clock", ja: "時計", category: "OBJECT" },
  112: { en: "Dude", ja: "男・やつ（俗語）", category: "PEOPLE" },
  113: { en: "Cattle", ja: "牛", category: "ANIMAL" },
  114: { en: "Jungle", ja: "ジャングル", category: "NATURE" },
  115: { en: "Desk", ja: "机", category: "FURNITURE" },
  116: { en: "Curling", ja: "カーリング", category: "SPORTS" },
  117: { en: "Cuisine", ja: "料理", category: "FOOD" },
  118: { en: "Cat", ja: "猫", category: "ANIMAL" },
  119: { en: "Juice", ja: "ジュース", category: "FOOD" },
  120: { en: "Couscous", ja: "クスクス", category: "FOOD" },
  121: { en: "Screenshot", ja: "スクリーンショット", category: "IMAGE" },
  122: { en: "Crew", ja: "乗組員・クルー", category: "PEOPLE" },
  123: { en: "Skyline", ja: "スカイライン（街並みの輪郭）", category: "PLACE" },
  125: { en: "Stuffed toy", ja: "ぬいぐるみ", category: "OBJECT" },
  126: { en: "Cookie", ja: "クッキー", category: "FOOD" },
  127: { en: "Tile", ja: "タイル", category: "MATERIAL" },
  128: { en: "Hanukkah", ja: "ハヌカ（ユダヤ教の祭り）", category: "EVENT" },
  129: { en: "Crochet", ja: "かぎ針編み", category: "ARTS" },
  130: { en: "Skateboarder", ja: "スケートボーダー", category: "PEOPLE" },
  131: { en: "Clipper", ja: "クリッパー（高速帆船）", category: "VEHICLE" },
  132: { en: "Nail", ja: "爪・釘", category: "BODY" },
  133: { en: "Cola", ja: "コーラ", category: "FOOD" },
  134: { en: "Cutlery", ja: "カトラリー", category: "OBJECT" },
  135: { en: "Menu", ja: "メニュー", category: "OBJECT" },
  137: { en: "Sari", ja: "サリー（インドの民族衣装）", category: "CLOTHING" },
  138: { en: "Plush", ja: "ぬいぐるみ・フラシ天", category: "OBJECT" },
  139: { en: "Pocket", ja: "ポケット", category: "CLOTHING" },
  140: { en: "Neon", ja: "ネオン", category: "OBJECT" },
  141: { en: "Icicle", ja: "つらら", category: "NATURE" },
  142: { en: "Pasteles", ja: "パステレス（中南米の料理）", category: "FOOD" },
  143: { en: "Chain", ja: "鎖", category: "OBJECT" },
  144: { en: "Dance", ja: "ダンス", category: "ACTION" },
  145: { en: "Dune", ja: "砂丘", category: "NATURE" },
  146: { en: "Santa claus", ja: "サンタクロース", category: "CHARACTER" },
  147: { en: "Thanksgiving", ja: "感謝祭", category: "EVENT" },
  148: { en: "Tuxedo", ja: "タキシード", category: "CLOTHING" },
  149: { en: "Mouth", ja: "口", category: "BODY" },
  150: { en: "Desert", ja: "砂漠", category: "NATURE" },
  151: { en: "Dinosaur", ja: "恐竜", category: "ANIMAL" },
  152: { en: "Mufti", ja: "私服（軍人などの平服）", category: "CLOTHING" },
  153: { en: "Fire", ja: "火・火災", category: "NATURE" },
  154: { en: "Bedroom", ja: "寝室", category: "PLACE" },
  155: { en: "Goggles", ja: "ゴーグル", category: "CLOTHING" },
  156: { en: "Dragon", ja: "ドラゴン・竜", category: "CHARACTER" },
  157: { en: "Couch", ja: "ソファ", category: "FURNITURE" },
  158: { en: "Sledding", ja: "そり遊び", category: "SPORTS" },
  159: { en: "Cap", ja: "キャップ（帽子）", category: "CLOTHING" },
  160: { en: "Whiteboard", ja: "ホワイトボード", category: "OBJECT" },
  161: { en: "Hat", ja: "帽子", category: "CLOTHING" },
  162: { en: "Gelato", ja: "ジェラート", category: "FOOD" },
  163: { en: "Cavalier", ja: "キャバリア（犬種）", category: "ANIMAL" },
  164: { en: "Beanie", ja: "ニット帽", category: "CLOTHING" },
  165: { en: "Jersey", ja: "ジャージ・ユニフォーム", category: "CLOTHING" },
  166: { en: "Scarf", ja: "マフラー・スカーフ", category: "CLOTHING" },
  167: { en: "Vacation", ja: "休暇", category: "CONCEPT" },
  168: { en: "Pitch", ja: "ピッチ（競技場）", category: "PLACE" },
  169: { en: "Blackboard", ja: "黒板", category: "OBJECT" },
  170: { en: "Deejay", ja: "DJ", category: "PEOPLE" },
  171: { en: "Monument", ja: "記念碑", category: "PLACE" },
  172: { en: "Bumper", ja: "バンパー", category: "VEHICLE" },
  173: { en: "Longboard", ja: "ロングボード", category: "SPORTS" },
  174: { en: "Waterfowl", ja: "水鳥", category: "ANIMAL" },
  175: { en: "Flesh", ja: "肌・肉", category: "BODY" },
  176: { en: "Net", ja: "ネット・網", category: "OBJECT" },
  177: { en: "Icing", ja: "アイシング（糖衣）", category: "FOOD" },
  178: { en: "Dalmatian", ja: "ダルメシアン", category: "ANIMAL" },
  179: { en: "Speedboat", ja: "モーターボート", category: "VEHICLE" },
  180: { en: "Trunk", ja: "木の幹・トランク", category: "PLANT" },
  181: { en: "Coffee", ja: "コーヒー", category: "FOOD" },
  182: { en: "Soccer", ja: "サッカー", category: "SPORTS" },
  183: { en: "Ragdoll", ja: "ラグドール（猫の品種）", category: "ANIMAL" },
  184: { en: "Food", ja: "食べ物", category: "FOOD" },
  185: { en: "Standing", ja: "立っている", category: "ACTION" },
  186: { en: "Fiction", ja: "フィクション", category: "CONCEPT" },
  187: { en: "Fruit", ja: "果物", category: "FOOD" },
  188: { en: "Pho", ja: "フォー", category: "FOOD" },
  189: { en: "Sparkler", ja: "手持ち花火", category: "EVENT" },
  190: { en: "Presentation", ja: "プレゼンテーション", category: "EVENT" },
  191: { en: "Swing", ja: "ブランコ", category: "OBJECT" },
  192: { en: "Cairn terrier", ja: "ケアーン・テリア", category: "ANIMAL" },
  193: { en: "Forest", ja: "森", category: "NATURE" },
  194: { en: "Flag", ja: "旗", category: "OBJECT" },
  195: { en: "Frigate", ja: "フリゲート艦", category: "VEHICLE" },
  196: { en: "Foot", ja: "足", category: "BODY" },
  197: { en: "Jacket", ja: "ジャケット", category: "CLOTHING" },
  199: { en: "Pillow", ja: "枕", category: "FURNITURE" },
  201: { en: "Bathing", ja: "入浴・水浴び", category: "ACTION" },
  202: { en: "Glacier", ja: "氷河", category: "NATURE" },
  203: { en: "Gymnastics", ja: "体操", category: "SPORTS" },
  204: { en: "Ear", ja: "耳", category: "BODY" },
  205: { en: "Flora", ja: "植物相", category: "PLANT" },
  206: { en: "Shell", ja: "貝殻", category: "NATURE" },
  207: { en: "Grandparent", ja: "祖父母", category: "PEOPLE" },
  208: { en: "Ruins", ja: "遺跡", category: "PLACE" },
  209: { en: "Eyelash", ja: "まつげ", category: "BODY" },
  210: { en: "Bunk bed", ja: "二段ベッド", category: "FURNITURE" },
  211: { en: "Balance", ja: "バランス", category: "CONCEPT" },
  212: { en: "Backpacking", ja: "バックパッキング", category: "SPORTS" },
  213: { en: "Horse", ja: "馬", category: "ANIMAL" },
  214: { en: "Glitter", ja: "ラメ・きらめき", category: "MATERIAL" },
  215: { en: "Saucer", ja: "ソーサー（受け皿）", category: "OBJECT" },
  216: { en: "Hair", ja: "髪", category: "BODY" },
  217: { en: "Miniature", ja: "ミニチュア", category: "OBJECT" },
  218: { en: "Crowd", ja: "群衆", category: "PEOPLE" },
  219: { en: "Curtain", ja: "カーテン", category: "FURNITURE" },
  220: { en: "Icon", ja: "アイコン", category: "IMAGE" },
  221: { en: "Pixie-bob", ja: "ピクシーボブ（猫の品種）", category: "ANIMAL" },
  222: { en: "Herd", ja: "群れ", category: "ANIMAL" },
  223: { en: "Insect", ja: "昆虫", category: "ANIMAL" },
  224: { en: "Ice", ja: "氷", category: "NATURE" },
  225: { en: "Bangle", ja: "バングル", category: "CLOTHING" },
  226: { en: "Flap", ja: "フラップ・垂れ蓋", category: "OBJECT" },
  227: { en: "Jewellery", ja: "宝飾品", category: "CLOTHING" },
  228: { en: "Knitting", ja: "編み物", category: "ARTS" },
  229: {
    en: "Centrepiece",
    ja: "センターピース（卓上装飾）",
    category: "OBJECT",
  },
  230: { en: "Outerwear", ja: "上着", category: "CLOTHING" },
  231: { en: "Love", ja: "愛", category: "CONCEPT" },
  232: { en: "Muscle", ja: "筋肉", category: "BODY" },
  233: { en: "Motorcycle", ja: "オートバイ", category: "VEHICLE" },
  234: { en: "Money", ja: "お金", category: "OBJECT" },
  235: { en: "Mosque", ja: "モスク", category: "PLACE" },
  236: { en: "Tableware", ja: "食器", category: "OBJECT" },
  237: { en: "Ballroom", ja: "舞踏場", category: "PLACE" },
  238: { en: "Kayak", ja: "カヤック", category: "VEHICLE" },
  239: { en: "Leisure", ja: "余暇・レジャー", category: "CONCEPT" },
  240: { en: "Receipt", ja: "レシート", category: "OBJECT" },
  241: { en: "Lake", ja: "湖", category: "NATURE" },
  242: { en: "Lighthouse", ja: "灯台", category: "PLACE" },
  243: { en: "Bridle", ja: "頭絡（馬具）", category: "OBJECT" },
  244: { en: "Leather", ja: "革", category: "MATERIAL" },
  245: { en: "Horn", ja: "角・ホルン", category: "OBJECT" },
  246: { en: "Strap", ja: "ストラップ", category: "OBJECT" },
  247: { en: "Lego", ja: "レゴ", category: "OBJECT" },
  248: { en: "Scuba diving", ja: "スキューバダイビング", category: "SPORTS" },
  249: { en: "Leggings", ja: "レギンス", category: "CLOTHING" },
  250: { en: "Pool", ja: "プール", category: "PLACE" },
  251: { en: "Musical instrument", ja: "楽器", category: "ARTS" },
  252: { en: "Musical", ja: "ミュージカル", category: "ARTS" },
  253: { en: "Metal", ja: "金属", category: "MATERIAL" },
  254: { en: "Moon", ja: "月", category: "SPACE" },
  255: { en: "Blazer", ja: "ブレザー", category: "CLOTHING" },
  256: { en: "Marriage", ja: "結婚", category: "EVENT" },
  257: { en: "Mobile phone", ja: "携帯電話", category: "ELECTRONICS" },
  258: { en: "Militia", ja: "民兵", category: "PEOPLE" },
  259: { en: "Tablecloth", ja: "テーブルクロス", category: "OBJECT" },
  260: { en: "Party", ja: "パーティー", category: "EVENT" },
  261: { en: "Nebula", ja: "星雲", category: "SPACE" },
  262: { en: "News", ja: "ニュース", category: "CONCEPT" },
  263: { en: "Newspaper", ja: "新聞", category: "OBJECT" },
  265: { en: "Piano", ja: "ピアノ", category: "ARTS" },
  266: { en: "Plant", ja: "植物", category: "PLANT" },
  267: { en: "Passport", ja: "パスポート", category: "OBJECT" },
  268: { en: "Penguin", ja: "ペンギン", category: "ANIMAL" },
  269: { en: "Shikoku", ja: "四国犬", category: "ANIMAL" },
  270: { en: "Palace", ja: "宮殿", category: "PLACE" },
  271: { en: "Doily", ja: "ドイリー（レースの敷物）", category: "OBJECT" },
  272: { en: "Polo", ja: "ポロ（競技）・ポロシャツ", category: "SPORTS" },
  273: { en: "Paper", ja: "紙", category: "MATERIAL" },
  274: { en: "Pop music", ja: "ポップ音楽", category: "ARTS" },
  275: { en: "Skiff", ja: "小舟", category: "VEHICLE" },
  276: { en: "Pizza", ja: "ピザ", category: "FOOD" },
  277: { en: "Pet", ja: "ペット", category: "ANIMAL" },
  278: { en: "Quilting", ja: "キルティング", category: "ARTS" },
  279: { en: "Cage", ja: "ケージ・檻", category: "OBJECT" },
  280: { en: "Skateboard", ja: "スケートボード", category: "SPORTS" },
  281: { en: "Surfing", ja: "サーフィン", category: "SPORTS" },
  282: { en: "Rugby", ja: "ラグビー", category: "SPORTS" },
  283: { en: "Lipstick", ja: "口紅", category: "OBJECT" },
  284: { en: "River", ja: "川", category: "NATURE" },
  285: { en: "Race", ja: "レース・競走", category: "SPORTS" },
  286: { en: "Rowing", ja: "ボート漕ぎ", category: "SPORTS" },
  287: { en: "Road", ja: "道路", category: "PLACE" },
  288: { en: "Running", ja: "ランニング", category: "SPORTS" },
  289: { en: "Room", ja: "部屋", category: "PLACE" },
  290: { en: "Roof", ja: "屋根", category: "PLACE" },
  291: { en: "Star", ja: "星", category: "SPACE" },
  292: { en: "Sports", ja: "スポーツ", category: "SPORTS" },
  293: { en: "Shoe", ja: "靴", category: "CLOTHING" },
  294: {
    en: "Tubing",
    ja: "チュービング（浮き輪での川下り等）",
    category: "SPORTS",
  },
  295: { en: "Space", ja: "宇宙", category: "SPACE" },
  296: { en: "Sleep", ja: "睡眠", category: "ACTION" },
  297: { en: "Skin", ja: "肌", category: "BODY" },
  298: { en: "Swimming", ja: "水泳", category: "SPORTS" },
  299: { en: "School", ja: "学校", category: "PLACE" },
  300: { en: "Sushi", ja: "寿司", category: "FOOD" },
  301: { en: "Loveseat", ja: "二人掛けソファ", category: "FURNITURE" },
  302: { en: "Superman", ja: "スーパーマン", category: "CHARACTER" },
  303: { en: "Cool", ja: "かっこいい", category: "CONCEPT" },
  304: { en: "Skiing", ja: "スキー", category: "SPORTS" },
  305: { en: "Submarine", ja: "潜水艦", category: "VEHICLE" },
  306: { en: "Song", ja: "歌", category: "ARTS" },
  307: { en: "Class", ja: "授業・教室", category: "PLACE" },
  308: { en: "Skyscraper", ja: "超高層ビル", category: "PLACE" },
  309: { en: "Volcano", ja: "火山", category: "NATURE" },
  310: { en: "Television", ja: "テレビ", category: "ELECTRONICS" },
  311: { en: "Rein", ja: "手綱", category: "OBJECT" },
  312: { en: "Tattoo", ja: "タトゥー", category: "BODY" },
  313: { en: "Train", ja: "電車", category: "VEHICLE" },
  314: { en: "Handrail", ja: "手すり", category: "OBJECT" },
  315: { en: "Cup", ja: "カップ", category: "OBJECT" },
  316: { en: "Vehicle", ja: "乗り物", category: "VEHICLE" },
  317: { en: "Handbag", ja: "ハンドバッグ", category: "CLOTHING" },
  318: { en: "Lampshade", ja: "ランプシェード", category: "FURNITURE" },
  319: { en: "Event", ja: "イベント", category: "CONCEPT" },
  320: { en: "Wine", ja: "ワイン", category: "FOOD" },
  321: { en: "Wing", ja: "翼", category: "ANIMAL" },
  322: { en: "Wheel", ja: "車輪", category: "VEHICLE" },
  323: { en: "Wakeboarding", ja: "ウェイクボード", category: "SPORTS" },
  324: { en: "Web page", ja: "ウェブページ", category: "IMAGE" },
  327: { en: "Ranch", ja: "牧場", category: "PLACE" },
  328: { en: "Fishing", ja: "釣り", category: "SPORTS" },
  329: { en: "Heart", ja: "ハート・心臓", category: "CONCEPT" },
  330: { en: "Cotton", ja: "綿", category: "MATERIAL" },
  331: { en: "Cappuccino", ja: "カプチーノ", category: "FOOD" },
  332: { en: "Bread", ja: "パン", category: "FOOD" },
  333: { en: "Sand", ja: "砂", category: "NATURE" },
  335: { en: "Museum", ja: "博物館・美術館", category: "PLACE" },
  336: { en: "Helicopter", ja: "ヘリコプター", category: "VEHICLE" },
  337: { en: "Mountain", ja: "山", category: "NATURE" },
  338: { en: "Duck", ja: "カモ・アヒル", category: "ANIMAL" },
  339: { en: "Soil", ja: "土", category: "NATURE" },
  340: { en: "Turtle", ja: "カメ", category: "ANIMAL" },
  341: { en: "Crocodile", ja: "ワニ", category: "ANIMAL" },
  342: { en: "Musician", ja: "ミュージシャン", category: "PEOPLE" },
  343: { en: "Sneakers", ja: "スニーカー", category: "CLOTHING" },
  344: { en: "Wool", ja: "羊毛", category: "MATERIAL" },
  345: { en: "Ring", ja: "指輪", category: "CLOTHING" },
  346: { en: "Singer", ja: "歌手", category: "PEOPLE" },
  347: { en: "Carnival", ja: "カーニバル", category: "EVENT" },
  348: { en: "Snowboarding", ja: "スノーボード", category: "SPORTS" },
  349: { en: "Waterskiing", ja: "水上スキー", category: "SPORTS" },
  350: { en: "Wall", ja: "壁", category: "PLACE" },
  351: { en: "Rocket", ja: "ロケット", category: "SPACE" },
  352: { en: "Countertop", ja: "調理台", category: "FURNITURE" },
  353: { en: "Beach", ja: "砂浜・海辺", category: "NATURE" },
  354: { en: "Rainbow", ja: "虹", category: "WEATHER" },
  355: { en: "Branch", ja: "枝", category: "PLANT" },
  356: { en: "Moustache", ja: "口ひげ", category: "BODY" },
  357: { en: "Garden", ja: "庭園", category: "PLACE" },
  358: { en: "Gown", ja: "ガウン・ドレス", category: "CLOTHING" },
  359: { en: "Field", ja: "野原・畑", category: "NATURE" },
  360: { en: "Dog", ja: "犬", category: "ANIMAL" },
  361: { en: "Superhero", ja: "スーパーヒーロー", category: "CHARACTER" },
  362: { en: "Flower", ja: "花", category: "PLANT" },
  363: { en: "Placemat", ja: "ランチョンマット", category: "OBJECT" },
  364: { en: "Subwoofer", ja: "サブウーファー", category: "ELECTRONICS" },
  365: { en: "Cathedral", ja: "大聖堂", category: "PLACE" },
  366: { en: "Building", ja: "建物", category: "PLACE" },
  367: { en: "Airplane", ja: "飛行機", category: "VEHICLE" },
  368: { en: "Fur", ja: "毛皮", category: "MATERIAL" },
  369: { en: "Bull", ja: "雄牛", category: "ANIMAL" },
  370: { en: "Bench", ja: "ベンチ", category: "FURNITURE" },
  371: { en: "Temple", ja: "寺院", category: "PLACE" },
  372: { en: "Butterfly", ja: "蝶", category: "ANIMAL" },
  373: { en: "Model", ja: "モデル・模型", category: "PEOPLE" },
  374: { en: "Marathon", ja: "マラソン", category: "SPORTS" },
  375: { en: "Needlework", ja: "針仕事・刺繍", category: "ARTS" },
  376: { en: "Kitchen", ja: "台所", category: "PLACE" },
  377: { en: "Castle", ja: "城", category: "PLACE" },
  378: { en: "Aurora", ja: "オーロラ", category: "WEATHER" },
  379: { en: "Larva", ja: "幼虫", category: "ANIMAL" },
  380: { en: "Racing", ja: "レース", category: "SPORTS" },
  382: { en: "Airliner", ja: "旅客機", category: "VEHICLE" },
  383: { en: "Dam", ja: "ダム", category: "PLACE" },
  384: { en: "Textile", ja: "織物・布地", category: "MATERIAL" },
  385: { en: "Groom", ja: "新郎", category: "PEOPLE" },
  386: { en: "Fun", ja: "楽しい", category: "CONCEPT" },
  387: { en: "Steaming", ja: "湯気", category: "NATURE" },
  388: { en: "Vegetable", ja: "野菜", category: "FOOD" },
  389: { en: "Unicycle", ja: "一輪車", category: "VEHICLE" },
  390: { en: "Jeans", ja: "ジーンズ", category: "CLOTHING" },
  391: { en: "Flowerpot", ja: "植木鉢", category: "OBJECT" },
  392: { en: "Drawer", ja: "引き出し", category: "FURNITURE" },
  393: { en: "Cake", ja: "ケーキ", category: "FOOD" },
  394: { en: "Armrest", ja: "肘掛け", category: "FURNITURE" },
  395: { en: "Aviation", ja: "航空", category: "VEHICLE" },
  397: { en: "Fog", ja: "霧", category: "WEATHER" },
  398: { en: "Fireworks", ja: "花火", category: "EVENT" },
  399: { en: "Farm", ja: "農場", category: "PLACE" },
  400: { en: "Seal", ja: "アザラシ", category: "ANIMAL" },
  401: { en: "Shelf", ja: "棚", category: "FURNITURE" },
  402: { en: "Bangs", ja: "前髪", category: "BODY" },
  403: { en: "Lightning", ja: "稲妻", category: "WEATHER" },
  404: { en: "Van", ja: "バン", category: "VEHICLE" },
  405: { en: "Sphynx", ja: "スフィンクス（猫の品種）", category: "ANIMAL" },
  406: { en: "Tire", ja: "タイヤ", category: "VEHICLE" },
  407: { en: "Denim", ja: "デニム", category: "MATERIAL" },
  408: { en: "Prairie", ja: "草原", category: "NATURE" },
  409: { en: "Snorkeling", ja: "シュノーケリング", category: "SPORTS" },
  410: { en: "Umbrella", ja: "傘", category: "OBJECT" },
  411: { en: "Asphalt", ja: "アスファルト", category: "MATERIAL" },
  412: { en: "Sailboat", ja: "帆船・ヨット", category: "VEHICLE" },
  413: { en: "Basset hound", ja: "バセット・ハウンド", category: "ANIMAL" },
  414: { en: "Pattern", ja: "模様・柄", category: "IMAGE" },
  415: { en: "Supper", ja: "夕食", category: "FOOD" },
  416: { en: "Veil", ja: "ベール", category: "CLOTHING" },
  417: { en: "Waterfall", ja: "滝", category: "NATURE" },
  419: { en: "Lunch", ja: "昼食", category: "FOOD" },
  420: { en: "Odometer", ja: "走行距離計", category: "VEHICLE" },
  421: { en: "Baby", ja: "赤ちゃん", category: "PEOPLE" },
  422: { en: "Glasses", ja: "眼鏡", category: "CLOTHING" },
  423: { en: "Car", ja: "自動車", category: "VEHICLE" },
  424: { en: "Aircraft", ja: "航空機", category: "VEHICLE" },
  425: { en: "Hand", ja: "手", category: "BODY" },
  426: { en: "Rodeo", ja: "ロデオ", category: "EVENT" },
  427: { en: "Canyon", ja: "峡谷", category: "NATURE" },
  428: { en: "Meal", ja: "食事", category: "FOOD" },
  429: { en: "Softball", ja: "ソフトボール", category: "SPORTS" },
  430: { en: "Alcohol", ja: "酒類", category: "FOOD" },
  431: { en: "Bride", ja: "花嫁", category: "PEOPLE" },
  432: { en: "Swamp", ja: "沼地", category: "NATURE" },
  433: { en: "Pie", ja: "パイ", category: "FOOD" },
  434: { en: "Bag", ja: "かばん", category: "CLOTHING" },
  435: { en: "Joker", ja: "ジョーカー（道化・悪役）", category: "CHARACTER" },
  436: { en: "Supervillain", ja: "悪役", category: "CHARACTER" },
  437: { en: "Army", ja: "軍隊", category: "PEOPLE" },
  438: { en: "Canoe", ja: "カヌー", category: "VEHICLE" },
  439: { en: "Selfie", ja: "自撮り", category: "IMAGE" },
  440: { en: "Rickshaw", ja: "人力車", category: "VEHICLE" },
  441: { en: "Barn", ja: "納屋", category: "PLACE" },
  442: { en: "Archery", ja: "アーチェリー", category: "SPORTS" },
  443: { en: "Aerospace engineering", ja: "航空宇宙工学", category: "SPACE" },
  445: { en: "Storm", ja: "嵐", category: "WEATHER" },
  446: { en: "Helmet", ja: "ヘルメット", category: "CLOTHING" },
};
