plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.parktracker'
version = '0.1.0'

android {
  namespace "expo.modules.parktracker"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-location:21.3.0'
  implementation "com.google.mlkit:image-labeling:17.0.9"
  implementation "com.google.mlkit:image-labeling-custom:17.0.3"
  implementation "com.google.mlkit:object-detection-custom:17.0.2"
  implementation "androidx.camera:camera-core:1.4.2"
  implementation "androidx.camera:camera-camera2:1.4.2"
  implementation "androidx.camera:camera-lifecycle:1.4.2"
  implementation "androidx.lifecycle:lifecycle-service:2.8.7"
}
