export const CATEGORY = {
  PEOPLE: { en: "People", ja: "人物" },
  BODY: { en: "Body", ja: "身体" },
  CLOTHING: { en: "Clothing & Accessories", ja: "服飾・装身具" },
  ANIMAL: { en: "Animals", ja: "動物" },
  PLANT: { en: "Plants", ja: "植物" },
  NATURE: { en: "Nature & Phenomena", ja: "自然・現象" },
  WEATHER: { en: "Sky & Weather", ja: "空・天候" },
  SPACE: { en: "Space", ja: "宇宙" },
  FOOD: { en: "Food & Drink", ja: "飲食" },
  VEHICLE: { en: "Vehicles", ja: "乗り物" },
  PLACE: { en: "Buildings & Places", ja: "建物・場所" },
  SPORTS: { en: "Sports & Recreation", ja: "スポーツ・レジャー" },
  EVENT: { en: "Events & Celebrations", ja: "行事・イベント" },
  ARTS: { en: "Arts & Music", ja: "芸術・音楽" },
  OBJECT: { en: "Objects", ja: "物品・日用品" },
  FURNITURE: { en: "Furniture & Interior", ja: "家具・インテリア" },
  ELECTRONICS: { en: "Electronics", ja: "電子機器" },
  MATERIAL: { en: "Materials & Textures", ja: "素材・質感" },
  ACTION: { en: "Actions", ja: "動作・行為" },
  CONCEPT: { en: "Abstract Concepts", ja: "抽象・概念" },
  IMAGE: { en: "Image Types", ja: "画像の種類" },
  CHARACTER: { en: "Characters", ja: "キャラクター" },
} as const;

export type Category = (typeof CATEGORY)[keyof typeof CATEGORY];

export type LabelInfo = {
  en: string;
  ja: string;
  category: Category;
};

const C = CATEGORY;

export const LABEL: Record<string, LabelInfo> = {
  "0": { en: "Team", ja: "チーム", category: C.PEOPLE },
  "1": { en: "Bonfire", ja: "たき火", category: C.NATURE },
  "2": { en: "Comics", ja: "漫画", category: C.ARTS },
  "3": { en: "Himalayan", ja: "ヒマラヤン（猫の品種）", category: C.ANIMAL },
  // [A] "4": { en: "Iceberg", ja: "氷山", category: C.NATURE },
  "5": { en: "Bento", ja: "弁当", category: C.FOOD },
  "7": { en: "Sink", ja: "流し台・洗面台", category: C.FURNITURE },
  "8": { en: "Toy", ja: "おもちゃ", category: C.OBJECT },
  "9": { en: "Statue", ja: "像・彫像", category: C.ARTS },
  "10": { en: "Cheeseburger", ja: "チーズバーガー", category: C.FOOD },
  "11": { en: "Tractor", ja: "トラクター", category: C.VEHICLE },
  "12": { en: "Sled", ja: "そり", category: C.SPORTS },
  // [B] "13": { en: "Aquarium", ja: "水族館・水槽", category: C.PLACE },
  "14": { en: "Circus", ja: "サーカス", category: C.EVENT },
  "16": { en: "Sitting", ja: "座っている", category: C.ACTION },
  // [C] "17": { en: "Beard", ja: "あごひげ", category: C.BODY },
  "18": { en: "Bridge", ja: "橋", category: C.PLACE },
  "19": { en: "Tights", ja: "タイツ", category: C.CLOTHING },
  "20": { en: "Bird", ja: "鳥", category: C.ANIMAL },
  "21": { en: "Rafting", ja: "ラフティング", category: C.SPORTS },
  "22": { en: "Park", ja: "公園", category: C.PLACE },
  "24": { en: "Factory", ja: "工場", category: C.PLACE },
  // "25": { en: "Graduation", ja: "卒業式", category: C.EVENT },
  "26": { en: "Porcelain", ja: "磁器", category: C.MATERIAL },
  "27": { en: "Twig", ja: "小枝", category: C.PLANT },
  "28": { en: "Petal", ja: "花びら", category: C.PLANT },
  // [A] "29": { en: "Cushion", ja: "クッション", category: C.FURNITURE },
  "30": { en: "Sunglasses", ja: "サングラス", category: C.CLOTHING },
  // "31": { en: "Infrastructure", ja: "インフラ・社会基盤", category: C.PLACE },
  "32": { en: "Ferris wheel", ja: "観覧車", category: C.PLACE },
  // [A] "33": { en: "Pomacentridae", ja: "スズメダイ科（熱帯魚）", category: C.ANIMAL },
  "34": { en: "Wetsuit", ja: "ウェットスーツ", category: C.CLOTHING },
  "35": {
    en: "Shetland sheepdog",
    ja: "シェットランド・シープドッグ",
    category: C.ANIMAL,
  },
  // [A] "36": { en: "Brig", ja: "ブリッグ（2本マストの帆船）", category: C.VEHICLE },
  "37": { en: "Watercolor paint", ja: "水彩画・水彩絵具", category: C.ARTS },
  "38": { en: "Competition", ja: "競技・大会", category: C.SPORTS },
  "39": { en: "Cliff", ja: "崖", category: C.NATURE },
  "40": { en: "Badminton", ja: "バドミントン", category: C.SPORTS },
  // [A] "41": { en: "Safari", ja: "サファリ", category: C.NATURE },
  "42": { en: "Bicycle", ja: "自転車", category: C.VEHICLE },
  // "43": { en: "Stadium", ja: "競技場", category: C.PLACE },
  "45": { en: "Boat", ja: "ボート", category: C.VEHICLE },
  // [C] "46": { en: "Smile", ja: "笑顔", category: C.PEOPLE },
  "47": { en: "Surfboard", ja: "サーフボード", category: C.SPORTS },
  "48": { en: "Fast food", ja: "ファストフード", category: C.FOOD },
  "49": { en: "Sunset", ja: "夕焼け・日没", category: C.WEATHER },
  "50": { en: "Hot dog", ja: "ホットドッグ", category: C.FOOD },
  // "51": { en: "Shorts", ja: "短パン", category: C.CLOTHING },
  "52": { en: "Bus", ja: "バス", category: C.VEHICLE },
  // [A] "53": { en: "Bullfighting", ja: "闘牛", category: C.EVENT },
  // [C] "54": { en: "Sky", ja: "空", category: C.WEATHER },
  "55": { en: "Gerbil", ja: "スナネズミ", category: C.ANIMAL },
  "56": { en: "Rock", ja: "岩", category: C.NATURE },
  // [A] "57": { en: "Interaction", ja: "交流・触れ合い", category: C.CONCEPT },
  "58": { en: "Dress", ja: "ドレス・ワンピース", category: C.CLOTHING },
  // [C] "59": { en: "Toe", ja: "つま先", category: C.BODY },
  "61": { en: "Bear", ja: "クマ", category: C.ANIMAL },
  "62": { en: "Eating", ja: "食べている", category: C.ACTION },
  "63": { en: "Tower", ja: "塔", category: C.PLACE },
  "64": { en: "Brick", ja: "レンガ", category: C.MATERIAL },
  "65": {
    en: "Junk",
    ja: "ジャンク（がらくた）",
    category: C.OBJECT,
  },
  // [C] "66": { en: "Person", ja: "人", category: C.PEOPLE },
  // [B] "67": { en: "Windsurfing", ja: "ウィンドサーフィン", category: C.SPORTS },
  "68": { en: "Swimwear", ja: "水着", category: C.CLOTHING },
  "69": { en: "Roller", ja: "ローラー", category: C.OBJECT },
  "70": { en: "Camping", ja: "キャンプ", category: C.SPORTS },
  "71": { en: "Playground", ja: "遊び場・遊具", category: C.PLACE },
  "72": { en: "Bathroom", ja: "浴室・トイレ", category: C.PLACE },
  // "73": { en: "Laugh", ja: "笑い", category: C.PEOPLE },
  "74": { en: "Balloon", ja: "風船", category: C.OBJECT },
  // "75": { en: "Concert", ja: "コンサート", category: C.EVENT },
  // "76": { en: "Prom", ja: "プロム（卒業ダンスパーティー）", category: C.EVENT },
  "77": { en: "Construction", ja: "建設・工事", category: C.PLACE },
  "78": { en: "Product", ja: "製品", category: C.OBJECT },
  // [A] "79": { en: "Reef", ja: "サンゴ礁", category: C.NATURE },
  "80": { en: "Picnic", ja: "ピクニック", category: C.SPORTS },
  "81": { en: "Wreath", ja: "リース・花輪", category: C.OBJECT },
  "82": { en: "Wheelbarrow", ja: "手押し車", category: C.OBJECT },
  "83": {
    en: "Boxer",
    ja: "ボクサー（犬種・ボクシング選手）",
    category: C.ANIMAL,
  },
  "84": { en: "Necklace", ja: "ネックレス", category: C.CLOTHING },
  "85": { en: "Bracelet", ja: "ブレスレット", category: C.CLOTHING },
  // [A] "86": { en: "Casino", ja: "カジノ", category: C.PLACE },
  // [A] "87": { en: "Windshield", ja: "フロントガラス", category: C.VEHICLE },
  "88": { en: "Stairs", ja: "階段", category: C.PLACE },
  "89": { en: "Computer", ja: "コンピューター", category: C.ELECTRONICS },
  "90": { en: "Cookware and bakeware", ja: "調理器具", category: C.OBJECT },
  // [A] "91": { en: "Monochrome", ja: "モノクロ（白黒画像）", category: C.IMAGE },
  "92": { en: "Chair", ja: "椅子", category: C.FURNITURE },
  "93": { en: "Poster", ja: "ポスター", category: C.IMAGE },
  "94": { en: "Bar", ja: "バー・酒場", category: C.PLACE },
  // [A] "95": { en: "Shipwreck", ja: "難破船", category: C.VEHICLE },
  "96": { en: "Pier", ja: "桟橋", category: C.PLACE },
  // [A] "97": { en: "Community", ja: "コミュニティ", category: C.CONCEPT },
  // [A] "98": { en: "Caving", ja: "洞窟探検", category: C.SPORTS },
  "99": { en: "Cave", ja: "洞窟", category: C.NATURE },
  // "100": { en: "Tie", ja: "ネクタイ", category: C.CLOTHING },
  // [A] "101": { en: "Cabinetry", ja: "戸棚・キャビネット類", category: C.FURNITURE },
  // [A] "102": { en: "Underwater", ja: "水中", category: C.NATURE },
  "103": { en: "Clown", ja: "ピエロ", category: C.PEOPLE },
  // [A] "104": { en: "Nightclub", ja: "ナイトクラブ", category: C.PLACE },
  "105": { en: "Cycling", ja: "サイクリング", category: C.SPORTS },
  // [A] "106": { en: "Comet", ja: "彗星", category: C.SPACE },
  "107": { en: "Mortarboard", ja: "角帽", category: C.CLOTHING },
  "108": { en: "Track", ja: "陸上トラック・線路", category: C.PLACE },
  // "109": { en: "Christmas", ja: "クリスマス", category: C.EVENT },
  "110": { en: "Church", ja: "教会", category: C.PLACE },
  "111": { en: "Clock", ja: "時計", category: C.OBJECT },
  // [A] "112": { en: "Dude", ja: "男・やつ（俗語）", category: C.PEOPLE },
  "113": { en: "Cattle", ja: "牛", category: C.ANIMAL },
  // [A] "114": { en: "Jungle", ja: "ジャングル", category: C.NATURE },
  "115": { en: "Desk", ja: "机", category: C.FURNITURE },
  // [B] "116": { en: "Curling", ja: "カーリング", category: C.SPORTS },
  "117": { en: "Cuisine", ja: "料理", category: C.FOOD },
  "118": { en: "Cat", ja: "猫", category: C.ANIMAL },
  "119": { en: "Juice", ja: "ジュース", category: C.FOOD },
  // "120": { en: "Couscous", ja: "クスクス", category: C.FOOD },
  // [A] "121": { en: "Screenshot", ja: "スクリーンショット", category: C.IMAGE },
  // "122": { en: "Crew", ja: "乗組員・クルー", category: C.PEOPLE },
  // "123": {
  //   en: "Skyline",
  //   ja: "スカイライン（街並みの輪郭）",
  //   category: C.PLACE,
  // },
  "125": { en: "Stuffed toy", ja: "ぬいぐるみ", category: C.OBJECT },
  "126": { en: "Cookie", ja: "クッキー", category: C.FOOD },
  "127": { en: "Tile", ja: "タイル", category: C.MATERIAL },
  // "128": { en: "Hanukkah", ja: "ハヌカ（ユダヤ教の祭り）", category: C.EVENT },
  // "129": { en: "Crochet", ja: "かぎ針編み", category: C.ARTS },
  "130": { en: "Skateboarder", ja: "スケートボーダー", category: C.PEOPLE },
  // [A] "131": { en: "Clipper", ja: "クリッパー（高速帆船）", category: C.VEHICLE },
  // "132": { en: "Nail", ja: "爪・釘", category: C.BODY },
  "133": { en: "Cola", ja: "コーラ", category: C.FOOD },
  "134": { en: "Cutlery", ja: "カトラリー", category: C.OBJECT },
  // [A] "135": { en: "Menu", ja: "メニュー", category: C.OBJECT },
  // "137": { en: "Sari", ja: "サリー（インドの民族衣装）", category: C.CLOTHING },
  "138": { en: "Plush", ja: "ぬいぐるみ・フラシ天", category: C.OBJECT },
  // "139": { en: "Pocket", ja: "ポケット", category: C.CLOTHING },
  "140": { en: "Neon", ja: "ネオン", category: C.OBJECT },
  "141": { en: "Icicle", ja: "つらら", category: C.NATURE },
  // "142": { en: "Pasteles", ja: "パステレス（中南米の料理）", category: C.FOOD },
  "143": { en: "Chain", ja: "鎖", category: C.OBJECT },
  "144": { en: "Dance", ja: "ダンス", category: C.ACTION },
  // [A] "145": { en: "Dune", ja: "砂丘", category: C.NATURE },
  "146": { en: "Santa claus", ja: "サンタクロース", category: C.CHARACTER },
  // "147": { en: "Thanksgiving", ja: "感謝祭", category: C.EVENT },
  // "148": { en: "Tuxedo", ja: "タキシード", category: C.CLOTHING },
  // [C] "149": { en: "Mouth", ja: "口", category: C.BODY },
  // [A] "150": { en: "Desert", ja: "砂漠", category: C.NATURE },
  "151": { en: "Dinosaur", ja: "恐竜", category: C.ANIMAL },
  // "152": { en: "Mufti", ja: "私服（軍人などの平服）", category: C.CLOTHING },
  "153": { en: "Fire", ja: "火・火災", category: C.NATURE },
  // [A] "154": { en: "Bedroom", ja: "寝室", category: C.PLACE },
  "155": { en: "Goggles", ja: "ゴーグル", category: C.CLOTHING },
  "156": { en: "Dragon", ja: "ドラゴン・竜", category: C.CHARACTER },
  // [A] "157": { en: "Couch", ja: "ソファ", category: C.FURNITURE },
  // [B] "158": { en: "Sledding", ja: "そり遊び", category: C.SPORTS },
  "159": { en: "Cap", ja: "キャップ（帽子）", category: C.CLOTHING },
  // [A] "160": { en: "Whiteboard", ja: "ホワイトボード", category: C.OBJECT },
  "161": { en: "Hat", ja: "帽子", category: C.CLOTHING },
  "162": { en: "Gelato", ja: "ジェラート", category: C.FOOD },
  "163": { en: "Cavalier", ja: "キャバリア（犬種）", category: C.ANIMAL },
  "164": { en: "Beanie", ja: "ニット帽", category: C.CLOTHING },
  "165": { en: "Jersey", ja: "ジャージ・ユニフォーム", category: C.CLOTHING },
  "166": { en: "Scarf", ja: "マフラー・スカーフ", category: C.CLOTHING },
  // [A] "167": { en: "Vacation", ja: "休暇", category: C.CONCEPT },
  "168": { en: "Pitch", ja: "ピッチ（競技場）", category: C.PLACE },
  // [A] "169": { en: "Blackboard", ja: "黒板", category: C.OBJECT },
  // "170": { en: "Deejay", ja: "DJ", category: C.PEOPLE },
  "171": { en: "Monument", ja: "記念碑", category: C.PLACE },
  "172": { en: "Bumper", ja: "バンパー", category: C.VEHICLE },
  "173": { en: "Longboard", ja: "ロングボード", category: C.SPORTS },
  "174": { en: "Waterfowl", ja: "水鳥", category: C.ANIMAL },
  // [C] "175": { en: "Flesh", ja: "肌・肉", category: C.BODY },
  "176": { en: "Net", ja: "ネット・網", category: C.OBJECT },
  // "177": { en: "Icing", ja: "アイシング（糖衣）", category: C.FOOD },
  "178": { en: "Dalmatian", ja: "ダルメシアン", category: C.ANIMAL },
  // [B] "179": { en: "Speedboat", ja: "モーターボート", category: C.VEHICLE },
  "180": { en: "Trunk", ja: "木の幹・トランク", category: C.PLANT },
  "181": { en: "Coffee", ja: "コーヒー", category: C.FOOD },
  "182": { en: "Soccer", ja: "サッカー", category: C.SPORTS },
  "183": { en: "Ragdoll", ja: "ラグドール（猫の品種）", category: C.ANIMAL },
  "184": { en: "Food", ja: "食べ物", category: C.FOOD },
  // [C] "185": { en: "Standing", ja: "立っている", category: C.ACTION },
  // [A] "186": { en: "Fiction", ja: "フィクション", category: C.CONCEPT },
  "187": { en: "Fruit", ja: "果物", category: C.FOOD },
  // "188": { en: "Pho", ja: "フォー", category: C.FOOD },
  "189": { en: "Sparkler", ja: "手持ち花火", category: C.EVENT },
  // "190": { en: "Presentation", ja: "プレゼンテーション", category: C.EVENT },
  "191": { en: "Swing", ja: "ブランコ", category: C.OBJECT },
  "192": { en: "Cairn terrier", ja: "ケアーン・テリア", category: C.ANIMAL },
  // "193": { en: "Forest", ja: "森", category: C.NATURE },
  "194": { en: "Flag", ja: "旗", category: C.OBJECT },
  // [A] "195": { en: "Frigate", ja: "フリゲート艦", category: C.VEHICLE },
  // "196": { en: "Foot", ja: "足", category: C.BODY },
  "197": { en: "Jacket", ja: "ジャケット", category: C.CLOTHING },
  // [A] "199": { en: "Pillow", ja: "枕", category: C.FURNITURE },
  // "201": { en: "Bathing", ja: "入浴・水浴び", category: C.ACTION },
  // [A] "202": { en: "Glacier", ja: "氷河", category: C.NATURE },
  "203": { en: "Gymnastics", ja: "体操", category: C.SPORTS },
  // [C] "204": { en: "Ear", ja: "耳", category: C.BODY },
  // [C] "205": { en: "Flora", ja: "植物相", category: C.PLANT },
  "206": { en: "Shell", ja: "貝殻", category: C.NATURE },
  // "207": { en: "Grandparent", ja: "祖父母", category: C.PEOPLE },
  "208": { en: "Ruins", ja: "遺跡", category: C.PLACE },
  // [C] "209": { en: "Eyelash", ja: "まつげ", category: C.BODY },
  // [A] "210": { en: "Bunk bed", ja: "二段ベッド", category: C.FURNITURE },
  // "211": { en: "Balance", ja: "バランス", category: C.CONCEPT },
  "212": { en: "Backpacking", ja: "バックパッキング", category: C.SPORTS },
  "213": { en: "Horse", ja: "馬", category: C.ANIMAL },
  "214": { en: "Glitter", ja: "ラメ・きらめき", category: C.MATERIAL },
  "215": { en: "Saucer", ja: "ソーサー（受け皿）", category: C.OBJECT },
  // [C] "216": { en: "Hair", ja: "髪", category: C.BODY },
  "217": { en: "Miniature", ja: "ミニチュア", category: C.OBJECT },
  "218": { en: "Crowd", ja: "群衆", category: C.PEOPLE },
  // [A] "219": { en: "Curtain", ja: "カーテン", category: C.FURNITURE },
  // [A] "220": { en: "Icon", ja: "アイコン", category: C.IMAGE },
  "221": {
    en: "Pixie-bob",
    ja: "ピクシーボブ（猫の品種）",
    category: C.ANIMAL,
  },
  "222": { en: "Herd", ja: "群れ", category: C.ANIMAL },
  "223": { en: "Insect", ja: "昆虫", category: C.ANIMAL },
  "224": { en: "Ice", ja: "氷", category: C.NATURE },
  // "225": { en: "Bangle", ja: "バングル", category: C.CLOTHING },
  // "226": { en: "Flap", ja: "フラップ・垂れ蓋", category: C.OBJECT },
  "227": { en: "Jewellery", ja: "宝飾品", category: C.CLOTHING },
  "228": { en: "Knitting", ja: "編み物", category: C.ARTS },
  "229": {
    en: "Centrepiece",
    ja: "センターピース（卓上装飾）",
    category: C.OBJECT,
  },
  "230": { en: "Outerwear", ja: "上着", category: C.CLOTHING },
  // [A] "231": { en: "Love", ja: "愛", category: C.CONCEPT },
  // [C] "232": { en: "Muscle", ja: "筋肉", category: C.BODY },
  "233": { en: "Motorcycle", ja: "オートバイ", category: C.VEHICLE },
  "234": { en: "Money", ja: "お金", category: C.OBJECT },
  // [A] "235": { en: "Mosque", ja: "モスク", category: C.PLACE },
  "236": { en: "Tableware", ja: "食器", category: C.OBJECT },
  // [A] "237": { en: "Ballroom", ja: "舞踏場", category: C.PLACE },
  "238": { en: "Kayak", ja: "カヤック", category: C.VEHICLE },
  // [A] "239": { en: "Leisure", ja: "余暇・レジャー", category: C.CONCEPT },
  "240": { en: "Receipt", ja: "レシート", category: C.OBJECT },
  "241": { en: "Lake", ja: "湖", category: C.NATURE },
  "242": { en: "Lighthouse", ja: "灯台", category: C.PLACE },
  "243": { en: "Bridle", ja: "頭絡（馬具）", category: C.OBJECT },
  "244": { en: "Leather", ja: "革", category: C.MATERIAL },
  "245": { en: "Horn", ja: "角・ホルン", category: C.OBJECT },
  "246": { en: "Strap", ja: "ストラップ", category: C.OBJECT },
  "247": { en: "Lego", ja: "レゴ", category: C.OBJECT },
  // [A] "248": { en: "Scuba diving", ja: "スキューバダイビング", category: C.SPORTS },
  "249": { en: "Leggings", ja: "レギンス", category: C.CLOTHING },
  "250": { en: "Pool", ja: "プール", category: C.PLACE },
  "251": { en: "Musical instrument", ja: "楽器", category: C.ARTS },
  // "252": { en: "Musical", ja: "ミュージカル", category: C.ARTS },
  "253": { en: "Metal", ja: "金属", category: C.MATERIAL },
  "254": { en: "Moon", ja: "月", category: C.SPACE },
  "255": { en: "Blazer", ja: "ブレザー", category: C.CLOTHING },
  // "256": { en: "Marriage", ja: "結婚", category: C.EVENT },
  "257": { en: "Mobile phone", ja: "携帯電話", category: C.ELECTRONICS },
  // "258": { en: "Militia", ja: "民兵", category: C.PEOPLE },
  "259": { en: "Tablecloth", ja: "テーブルクロス", category: C.OBJECT },
  "260": { en: "Party", ja: "パーティー", category: C.EVENT },
  // [A] "261": { en: "Nebula", ja: "星雲", category: C.SPACE },
  // "262": { en: "News", ja: "ニュース", category: C.CONCEPT },
  "263": { en: "Newspaper", ja: "新聞", category: C.OBJECT },
  "265": { en: "Piano", ja: "ピアノ", category: C.ARTS },
  "266": { en: "Plant", ja: "植物", category: C.PLANT },
  // [A] "267": { en: "Passport", ja: "パスポート", category: C.OBJECT },
  "268": { en: "Penguin", ja: "ペンギン", category: C.ANIMAL },
  "269": { en: "Shikoku", ja: "四国犬", category: C.ANIMAL },
  "270": { en: "Palace", ja: "宮殿", category: C.PLACE },
  // "271": { en: "Doily", ja: "ドイリー（レースの敷物）", category: C.OBJECT },
  // "272": { en: "Polo", ja: "ポロ（競技）・ポロシャツ", category: C.SPORTS },
  "273": { en: "Paper", ja: "紙", category: C.MATERIAL },
  "274": { en: "Pop music", ja: "ポップ音楽", category: C.ARTS },
  "275": { en: "Skiff", ja: "小舟", category: C.VEHICLE },
  "276": { en: "Pizza", ja: "ピザ", category: C.FOOD },
  "277": { en: "Pet", ja: "ペット", category: C.ANIMAL },
  // "278": { en: "Quilting", ja: "キルティング", category: C.ARTS },
  "279": { en: "Cage", ja: "ケージ・檻", category: C.OBJECT },
  "280": { en: "Skateboard", ja: "スケートボード", category: C.SPORTS },
  // [B] "281": { en: "Surfing", ja: "サーフィン", category: C.SPORTS },
  "282": { en: "Rugby", ja: "ラグビー", category: C.SPORTS },
  // "283": { en: "Lipstick", ja: "口紅", category: C.OBJECT },
  "284": { en: "River", ja: "川", category: C.NATURE },
  "285": { en: "Race", ja: "レース・競走", category: C.SPORTS },
  // "286": { en: "Rowing", ja: "ボート漕ぎ", category: C.SPORTS },
  // [C] "287": { en: "Road", ja: "道路", category: C.PLACE },
  "288": { en: "Running", ja: "ランニング", category: C.SPORTS },
  // "289": { en: "Room", ja: "部屋", category: C.PLACE },
  "290": { en: "Roof", ja: "屋根", category: C.PLACE },
  "291": { en: "Star", ja: "星", category: C.SPACE },
  "292": { en: "Sports", ja: "スポーツ", category: C.SPORTS },
  "293": { en: "Shoe", ja: "靴", category: C.CLOTHING },
  // "294": {
  //   en: "Tubing",
  //   ja: "チュービング（浮き輪での川下り等）",
  //   category: C.SPORTS,
  // },
  // [A] "295": { en: "Space", ja: "宇宙", category: C.SPACE },
  "296": { en: "Sleep", ja: "睡眠", category: C.ACTION },
  // [C] "297": { en: "Skin", ja: "肌", category: C.BODY },
  "298": { en: "Swimming", ja: "水泳", category: C.SPORTS },
  "299": { en: "School", ja: "学校", category: C.PLACE },
  "300": { en: "Sushi", ja: "寿司", category: C.FOOD },
  // [A] "301": { en: "Loveseat", ja: "二人掛けソファ", category: C.FURNITURE },
  // [A] "302": { en: "Superman", ja: "スーパーマン", category: C.CHARACTER },
  // [A] "303": { en: "Cool", ja: "かっこいい", category: C.CONCEPT },
  // [B] "304": { en: "Skiing", ja: "スキー", category: C.SPORTS },
  // [A] "305": { en: "Submarine", ja: "潜水艦", category: C.VEHICLE },
  "306": { en: "Song", ja: "歌", category: C.ARTS },
  // [A] "307": { en: "Class", ja: "授業・教室", category: C.PLACE },
  "308": { en: "Skyscraper", ja: "超高層ビル", category: C.PLACE },
  "309": { en: "Volcano", ja: "火山", category: C.NATURE },
  // [A] "310": { en: "Television", ja: "テレビ", category: C.ELECTRONICS },
  "311": { en: "Rein", ja: "手綱", category: C.OBJECT },
  "312": { en: "Tattoo", ja: "タトゥー", category: C.BODY },
  "313": { en: "Train", ja: "電車", category: C.VEHICLE },
  "314": { en: "Handrail", ja: "手すり", category: C.OBJECT },
  "315": { en: "Cup", ja: "カップ", category: C.OBJECT },
  "316": { en: "Vehicle", ja: "乗り物", category: C.VEHICLE },
  "317": { en: "Handbag", ja: "ハンドバッグ", category: C.CLOTHING },
  // [A] "318": { en: "Lampshade", ja: "ランプシェード", category: C.FURNITURE },
  // [A] "319": { en: "Event", ja: "イベント", category: C.CONCEPT },
  "320": { en: "Wine", ja: "ワイン", category: C.FOOD },
  "321": { en: "Wing", ja: "翼", category: C.ANIMAL },
  "322": { en: "Wheel", ja: "車輪", category: C.VEHICLE },
  // [B] "323": { en: "Wakeboarding", ja: "ウェイクボード", category: C.SPORTS },
  // [A] "324": { en: "Web page", ja: "ウェブページ", category: C.IMAGE },
  "327": { en: "Ranch", ja: "牧場", category: C.PLACE },
  "328": { en: "Fishing", ja: "釣り", category: C.SPORTS },
  // "329": { en: "Heart", ja: "ハート・心臓", category: C.CONCEPT },
  "330": { en: "Cotton", ja: "綿", category: C.MATERIAL },
  "331": { en: "Cappuccino", ja: "カプチーノ", category: C.FOOD },
  "332": { en: "Bread", ja: "パン", category: C.FOOD },
  "333": { en: "Sand", ja: "砂", category: C.NATURE },
  "335": { en: "Museum", ja: "博物館・美術館", category: C.PLACE },
  "336": { en: "Helicopter", ja: "ヘリコプター", category: C.VEHICLE },
  "337": { en: "Mountain", ja: "山", category: C.NATURE },
  "338": { en: "Duck", ja: "カモ・アヒル", category: C.ANIMAL },
  "339": { en: "Soil", ja: "土", category: C.NATURE },
  "340": { en: "Turtle", ja: "カメ", category: C.ANIMAL },
  "341": { en: "Crocodile", ja: "ワニ", category: C.ANIMAL },
  "342": { en: "Musician", ja: "ミュージシャン", category: C.PEOPLE },
  // "343": { en: "Sneakers", ja: "スニーカー", category: C.CLOTHING },
  // "344": { en: "Wool", ja: "羊毛", category: C.MATERIAL },
  "345": { en: "Ring", ja: "指輪", category: C.CLOTHING },
  "346": { en: "Singer", ja: "歌手", category: C.PEOPLE },
  // "347": { en: "Carnival", ja: "カーニバル", category: C.EVENT },
  // [B] "348": { en: "Snowboarding", ja: "スノーボード", category: C.SPORTS },
  // [B] "349": { en: "Waterskiing", ja: "水上スキー", category: C.SPORTS },
  "350": { en: "Wall", ja: "壁", category: C.PLACE },
  // [A] "351": { en: "Rocket", ja: "ロケット", category: C.SPACE },
  // [A] "352": { en: "Countertop", ja: "調理台", category: C.FURNITURE },
  "353": { en: "Beach", ja: "砂浜・海辺", category: C.NATURE },
  "354": { en: "Rainbow", ja: "虹", category: C.WEATHER },
  "355": { en: "Branch", ja: "枝", category: C.PLANT },
  // [C] "356": { en: "Moustache", ja: "口ひげ", category: C.BODY },
  "357": { en: "Garden", ja: "庭園", category: C.PLACE },
  "358": { en: "Gown", ja: "ガウン・ドレス", category: C.CLOTHING },
  "359": { en: "Field", ja: "野原・畑", category: C.NATURE },
  "360": { en: "Dog", ja: "犬", category: C.ANIMAL },
  // [A] "361": { en: "Superhero", ja: "スーパーヒーロー", category: C.CHARACTER },
  "362": { en: "Flower", ja: "花", category: C.PLANT },
  "363": { en: "Placemat", ja: "ランチョンマット", category: C.OBJECT },
  // "364": { en: "Subwoofer", ja: "サブウーファー", category: C.ELECTRONICS },
  // [A] "365": { en: "Cathedral", ja: "大聖堂", category: C.PLACE },
  "366": { en: "Building", ja: "建物", category: C.PLACE },
  "367": { en: "Airplane", ja: "飛行機", category: C.VEHICLE },
  "368": { en: "Fur", ja: "毛皮", category: C.MATERIAL },
  "369": { en: "Bull", ja: "雄牛", category: C.ANIMAL },
  "370": { en: "Bench", ja: "ベンチ", category: C.FURNITURE },
  "371": { en: "Temple", ja: "寺院", category: C.PLACE },
  "372": { en: "Butterfly", ja: "蝶", category: C.ANIMAL },
  // "373": { en: "Model", ja: "モデル・模型", category: C.PEOPLE },
  "374": { en: "Marathon", ja: "マラソン", category: C.SPORTS },
  // "375": { en: "Needlework", ja: "針仕事・刺繍", category: C.ARTS },
  // [A] "376": { en: "Kitchen", ja: "台所", category: C.PLACE },
  "377": { en: "Castle", ja: "城", category: C.PLACE },
  // [A] "378": { en: "Aurora", ja: "オーロラ", category: C.WEATHER },
  "379": { en: "Larva", ja: "幼虫", category: C.ANIMAL },
  "380": { en: "Racing", ja: "レース", category: C.SPORTS },
  "382": { en: "Airliner", ja: "旅客機", category: C.VEHICLE },
  "383": { en: "Dam", ja: "ダム", category: C.PLACE },
  // "384": { en: "Textile", ja: "織物・布地", category: C.MATERIAL },
  // "385": { en: "Groom", ja: "新郎", category: C.PEOPLE },
  // [A] "386": { en: "Fun", ja: "楽しい", category: C.CONCEPT },
  "387": { en: "Steaming", ja: "湯気", category: C.NATURE },
  "388": { en: "Vegetable", ja: "野菜", category: C.FOOD },
  "389": { en: "Unicycle", ja: "一輪車", category: C.VEHICLE },
  "390": { en: "Jeans", ja: "ジーンズ", category: C.CLOTHING },
  "391": { en: "Flowerpot", ja: "植木鉢", category: C.OBJECT },
  // [A] "392": { en: "Drawer", ja: "引き出し", category: C.FURNITURE },
  "393": { en: "Cake", ja: "ケーキ", category: C.FOOD },
  // "394": { en: "Armrest", ja: "肘掛け", category: C.FURNITURE },
  // "395": { en: "Aviation", ja: "航空", category: C.VEHICLE },
  "397": { en: "Fog", ja: "霧", category: C.WEATHER },
  "398": { en: "Fireworks", ja: "花火", category: C.EVENT },
  "399": { en: "Farm", ja: "農場", category: C.PLACE },
  // [B] "400": { en: "Seal", ja: "アザラシ", category: C.ANIMAL },
  "401": { en: "Shelf", ja: "棚", category: C.FURNITURE },
  // [C] "402": { en: "Bangs", ja: "前髪", category: C.BODY },
  // "403": { en: "Lightning", ja: "稲妻", category: C.WEATHER },
  // "404": { en: "Van", ja: "バン", category: C.VEHICLE },
  "405": { en: "Sphynx", ja: "スフィンクス（猫の品種）", category: C.ANIMAL },
  "406": { en: "Tire", ja: "タイヤ", category: C.VEHICLE },
  // "407": { en: "Denim", ja: "デニム", category: C.MATERIAL },
  "408": { en: "Prairie", ja: "草原", category: C.NATURE },
  // [A] "409": { en: "Snorkeling", ja: "シュノーケリング", category: C.SPORTS },
  "410": { en: "Umbrella", ja: "傘", category: C.OBJECT },
  "411": { en: "Asphalt", ja: "アスファルト", category: C.MATERIAL },
  // [B] "412": { en: "Sailboat", ja: "帆船・ヨット", category: C.VEHICLE },
  // "413": { en: "Basset hound", ja: "バセット・ハウンド", category: C.ANIMAL },
  // [A] "414": { en: "Pattern", ja: "模様・柄", category: C.IMAGE },
  // "415": { en: "Supper", ja: "夕食", category: C.FOOD },
  // "416": { en: "Veil", ja: "ベール", category: C.CLOTHING },
  "417": { en: "Waterfall", ja: "滝", category: C.NATURE },
  "419": { en: "Lunch", ja: "昼食", category: C.FOOD },
  // [A] "420": { en: "Odometer", ja: "走行距離計", category: C.VEHICLE },
  "421": { en: "Baby", ja: "赤ちゃん", category: C.PEOPLE },
  "422": { en: "Glasses", ja: "眼鏡", category: C.CLOTHING },
  "423": { en: "Car", ja: "自動車", category: C.VEHICLE },
  // "424": { en: "Aircraft", ja: "航空機", category: C.VEHICLE },
  // [C] "425": { en: "Hand", ja: "手", category: C.BODY },
  // [A] "426": { en: "Rodeo", ja: "ロデオ", category: C.EVENT },
  // [A] "427": { en: "Canyon", ja: "峡谷", category: C.NATURE },
  "428": { en: "Meal", ja: "食事", category: C.FOOD },
  "429": { en: "Softball", ja: "ソフトボール", category: C.SPORTS },
  "430": { en: "Alcohol", ja: "酒類", category: C.FOOD },
  // "431": { en: "Bride", ja: "花嫁", category: C.PEOPLE },
  // [A] "432": { en: "Swamp", ja: "沼地", category: C.NATURE },
  "433": { en: "Pie", ja: "パイ", category: C.FOOD },
  "434": { en: "Bag", ja: "かばん", category: C.CLOTHING },
  // [A] "435": { en: "Joker", ja: "ジョーカー（道化・悪役）", category: C.CHARACTER },
  // [A] "436": { en: "Supervillain", ja: "悪役", category: C.CHARACTER },
  // "437": { en: "Army", ja: "軍隊", category: C.PEOPLE },
  "438": { en: "Canoe", ja: "カヌー", category: C.VEHICLE },
  "439": { en: "Selfie", ja: "自撮り", category: C.IMAGE },
  "440": { en: "Rickshaw", ja: "人力車", category: C.VEHICLE },
  "441": { en: "Barn", ja: "納屋", category: C.PLACE },
  "442": { en: "Archery", ja: "アーチェリー", category: C.SPORTS },
  // [A] "443": { en: "Aerospace engineering", ja: "航空宇宙工学", category: C.SPACE },
  "445": { en: "Storm", ja: "嵐", category: C.WEATHER },
  "446": { en: "Helmet", ja: "ヘルメット", category: C.CLOTHING },
};
