export const CATEGORY = {
  PEOPLE: { en: "People", ja: "人物" },
  BODY: { en: "Body", ja: "身体" },
  CLOTHING: { en: "Clothing & Accessories", ja: "服飾・装身具" },
  ANIMAL: { en: "Animals", ja: "動物" },
  PLANT: { en: "Plants", ja: "植物" },
  NATURE: { en: "Nature & Phenomena", ja: "自然・現象" },
  WEATHER: { en: "Sky & Weather", ja: "空・天候" },
  SPACE: { en: "Space", ja: "宇宙" },
  FOOD: { en: "Food & Drink", ja: "飲食" },
  VEHICLE: { en: "Vehicles", ja: "乗り物" },
  PLACE: { en: "Buildings & Places", ja: "建物・場所" },
  SPORTS: { en: "Sports & Recreation", ja: "スポーツ・レジャー" },
  EVENT: { en: "Events & Celebrations", ja: "行事・イベント" },
  ARTS: { en: "Arts & Music", ja: "芸術・音楽" },
  OBJECT: { en: "Objects", ja: "物品・日用品" },
  FURNITURE: { en: "Furniture & Interior", ja: "家具・インテリア" },
  ELECTRONICS: { en: "Electronics", ja: "電子機器" },
  MATERIAL: { en: "Materials & Textures", ja: "素材・質感" },
  ACTION: { en: "Actions", ja: "動作・行為" },
  CONCEPT: { en: "Abstract Concepts", ja: "抽象・概念" },
  IMAGE: { en: "Image Types", ja: "画像の種類" },
  CHARACTER: { en: "Characters", ja: "キャラクター" },
} as const;

export type Category = (typeof CATEGORY)[keyof typeof CATEGORY];

export type LabelInfo = {
  en: string;
  ja: string;
  category: Category;
};

const C = CATEGORY;

export const BASE_LABEL: Record<string, LabelInfo> = {
  "0": { en: "Team", ja: "チーム", category: C.PEOPLE },
  "1": { en: "Bonfire", ja: "たき火", category: C.NATURE },
  "2": { en: "Comics", ja: "漫画", category: C.ARTS },
  "3": { en: "Himalayan", ja: "ヒマラヤン（猫の品種）", category: C.ANIMAL },
  // [A] "4": { en: "Iceberg", ja: "氷山", category: C.NATURE },
  "5": { en: "Bento", ja: "弁当", category: C.FOOD },
  "7": { en: "Sink", ja: "流し台・洗面台", category: C.FURNITURE },
  "8": { en: "Toy", ja: "おもちゃ", category: C.OBJECT },
  "9": { en: "Statue", ja: "像・彫像", category: C.ARTS },
  "10": { en: "Cheeseburger", ja: "チーズバーガー", category: C.FOOD },
  "11": { en: "Tractor", ja: "トラクター", category: C.VEHICLE },
  "12": { en: "Sled", ja: "そり", category: C.SPORTS },
  // [B] "13": { en: "Aquarium", ja: "水族館・水槽", category: C.PLACE },
  "14": { en: "Circus", ja: "サーカス", category: C.EVENT },
  "16": { en: "Sitting", ja: "座っている", category: C.ACTION },
  // [C] "17": { en: "Beard", ja: "あごひげ", category: C.BODY },
  "18": { en: "Bridge", ja: "橋", category: C.PLACE },
  "19": { en: "Tights", ja: "タイツ", category: C.CLOTHING },
  "20": { en: "Bird", ja: "鳥", category: C.ANIMAL },
  "21": { en: "Rafting", ja: "ラフティング", category: C.SPORTS },
  "22": { en: "Park", ja: "公園", category: C.PLACE },
  "24": { en: "Factory", ja: "工場", category: C.PLACE },
  // "25": { en: "Graduation", ja: "卒業式", category: C.EVENT },
  "26": { en: "Porcelain", ja: "磁器", category: C.MATERIAL },
  "27": { en: "Twig", ja: "小枝", category: C.PLANT },
  "28": { en: "Petal", ja: "花びら", category: C.PLANT },
  // [A] "29": { en: "Cushion", ja: "クッション", category: C.FURNITURE },
  "30": { en: "Sunglasses", ja: "サングラス", category: C.CLOTHING },
  // "31": { en: "Infrastructure", ja: "インフラ・社会基盤", category: C.PLACE },
  "32": { en: "Ferris wheel", ja: "観覧車", category: C.PLACE },
  // [A] "33": { en: "Pomacentridae", ja: "スズメダイ科（熱帯魚）", category: C.ANIMAL },
  "34": { en: "Wetsuit", ja: "ウェットスーツ", category: C.CLOTHING },
  "35": {
    en: "Shetland sheepdog",
    ja: "シェットランド・シープドッグ",
    category: C.ANIMAL,
  },
  // [A] "36": { en: "Brig", ja: "ブリッグ（2本マストの帆船）", category: C.VEHICLE },
  "37": { en: "Watercolor paint", ja: "水彩画・水彩絵具", category: C.ARTS },
  "38": { en: "Competition", ja: "競技・大会", category: C.SPORTS },
  "39": { en: "Cliff", ja: "崖", category: C.NATURE },
  "40": { en: "Badminton", ja: "バドミントン", category: C.SPORTS },
  // [A] "41": { en: "Safari", ja: "サファリ", category: C.NATURE },
  "42": { en: "Bicycle", ja: "自転車", category: C.VEHICLE },
  // "43": { en: "Stadium", ja: "競技場", category: C.PLACE },
  "45": { en: "Boat", ja: "ボート", category: C.VEHICLE },
  // [C] "46": { en: "Smile", ja: "笑顔", category: C.PEOPLE },
  "47": { en: "Surfboard", ja: "サーフボード", category: C.SPORTS },
  "48": { en: "Fast food", ja: "ファストフード", category: C.FOOD },
  "49": { en: "Sunset", ja: "夕焼け・日没", category: C.WEATHER },
  "50": { en: "Hot dog", ja: "ホットドッグ", category: C.FOOD },
  // "51": { en: "Shorts", ja: "短パン", category: C.CLOTHING },
  "52": { en: "Bus", ja: "バス", category: C.VEHICLE },
  // [A] "53": { en: "Bullfighting", ja: "闘牛", category: C.EVENT },
  // [C] "54": { en: "Sky", ja: "空", category: C.WEATHER },
  "55": { en: "Gerbil", ja: "スナネズミ", category: C.ANIMAL },
  "56": { en: "Rock", ja: "岩", category: C.NATURE },
  // [A] "57": { en: "Interaction", ja: "交流・触れ合い", category: C.CONCEPT },
  "58": { en: "Dress", ja: "ドレス・ワンピース", category: C.CLOTHING },
  // [C] "59": { en: "Toe", ja: "つま先", category: C.BODY },
  "61": { en: "Bear", ja: "クマ", category: C.ANIMAL },
  "62": { en: "Eating", ja: "食べている", category: C.ACTION },
  "63": { en: "Tower", ja: "塔", category: C.PLACE },
  "64": { en: "Brick", ja: "レンガ", category: C.MATERIAL },
  "65": {
    en: "Junk",
    ja: "ジャンク（がらくた）",
    category: C.OBJECT,
  },
  // [C] "66": { en: "Person", ja: "人", category: C.PEOPLE },
  // [B] "67": { en: "Windsurfing", ja: "ウィンドサーフィン", category: C.SPORTS },
  "68": { en: "Swimwear", ja: "水着", category: C.CLOTHING },
  "69": { en: "Roller", ja: "ローラー", category: C.OBJECT },
  "70": { en: "Camping", ja: "キャンプ", category: C.SPORTS },
  "71": { en: "Playground", ja: "遊び場・遊具", category: C.PLACE },
  "72": { en: "Bathroom", ja: "浴室・トイレ", category: C.PLACE },
  // "73": { en: "Laugh", ja: "笑い", category: C.PEOPLE },
  "74": { en: "Balloon", ja: "風船", category: C.OBJECT },
  // "75": { en: "Concert", ja: "コンサート", category: C.EVENT },
  // "76": { en: "Prom", ja: "プロム（卒業ダンスパーティー）", category: C.EVENT },
  "77": { en: "Construction", ja: "建設・工事", category: C.PLACE },
  "78": { en: "Product", ja: "製品", category: C.OBJECT },
  // [A] "79": { en: "Reef", ja: "サンゴ礁", category: C.NATURE },
  "80": { en: "Picnic", ja: "ピクニック", category: C.SPORTS },
  "81": { en: "Wreath", ja: "リース・花輪", category: C.OBJECT },
  "82": { en: "Wheelbarrow", ja: "手押し車", category: C.OBJECT },
  "83": {
    en: "Boxer",
    ja: "ボクサー（犬種・ボクシング選手）",
    category: C.ANIMAL,
  },
  "84": { en: "Necklace", ja: "ネックレス", category: C.CLOTHING },
  "85": { en: "Bracelet", ja: "ブレスレット", category: C.CLOTHING },
  // [A] "86": { en: "Casino", ja: "カジノ", category: C.PLACE },
  // [A] "87": { en: "Windshield", ja: "フロントガラス", category: C.VEHICLE },
  "88": { en: "Stairs", ja: "階段", category: C.PLACE },
  "89": { en: "Computer", ja: "コンピューター", category: C.ELECTRONICS },
  "90": { en: "Cookware and bakeware", ja: "調理器具", category: C.OBJECT },
  // [A] "91": { en: "Monochrome", ja: "モノクロ（白黒画像）", category: C.IMAGE },
  "92": { en: "Chair", ja: "椅子", category: C.FURNITURE },
  "93": { en: "Poster", ja: "ポスター", category: C.IMAGE },
  "94": { en: "Bar", ja: "バー・酒場", category: C.PLACE },
  // [A] "95": { en: "Shipwreck", ja: "難破船", category: C.VEHICLE },
  "96": { en: "Pier", ja: "桟橋", category: C.PLACE },
  // [A] "97": { en: "Community", ja: "コミュニティ", category: C.CONCEPT },
  // [A] "98": { en: "Caving", ja: "洞窟探検", category: C.SPORTS },
  "99": { en: "Cave", ja: "洞窟", category: C.NATURE },
  // "100": { en: "Tie", ja: "ネクタイ", category: C.CLOTHING },
  // [A] "101": { en: "Cabinetry", ja: "戸棚・キャビネット類", category: C.FURNITURE },
  // [A] "102": { en: "Underwater", ja: "水中", category: C.NATURE },
  "103": { en: "Clown", ja: "ピエロ", category: C.PEOPLE },
  // [A] "104": { en: "Nightclub", ja: "ナイトクラブ", category: C.PLACE },
  "105": { en: "Cycling", ja: "サイクリング", category: C.SPORTS },
  // [A] "106": { en: "Comet", ja: "彗星", category: C.SPACE },
  "107": { en: "Mortarboard", ja: "角帽", category: C.CLOTHING },
  "108": { en: "Track", ja: "陸上トラック・線路", category: C.PLACE },
  // "109": { en: "Christmas", ja: "クリスマス", category: C.EVENT },
  "110": { en: "Church", ja: "教会", category: C.PLACE },
  "111": { en: "Clock", ja: "時計", category: C.OBJECT },
  // [A] "112": { en: "Dude", ja: "男・やつ（俗語）", category: C.PEOPLE },
  "113": { en: "Cattle", ja: "牛", category: C.ANIMAL },
  // [A] "114": { en: "Jungle", ja: "ジャングル", category: C.NATURE },
  "115": { en: "Desk", ja: "机", category: C.FURNITURE },
  // [B] "116": { en: "Curling", ja: "カーリング", category: C.SPORTS },
  "117": { en: "Cuisine", ja: "料理", category: C.FOOD },
  "118": { en: "Cat", ja: "猫", category: C.ANIMAL },
  "119": { en: "Juice", ja: "ジュース", category: C.FOOD },
  // "120": { en: "Couscous", ja: "クスクス", category: C.FOOD },
  // [A] "121": { en: "Screenshot", ja: "スクリーンショット", category: C.IMAGE },
  // "122": { en: "Crew", ja: "乗組員・クルー", category: C.PEOPLE },
  // "123": {
  //   en: "Skyline",
  //   ja: "スカイライン（街並みの輪郭）",
  //   category: C.PLACE,
  // },
  "125": { en: "Stuffed toy", ja: "ぬいぐるみ", category: C.OBJECT },
  "126": { en: "Cookie", ja: "クッキー", category: C.FOOD },
  "127": { en: "Tile", ja: "タイル", category: C.MATERIAL },
  // "128": { en: "Hanukkah", ja: "ハヌカ（ユダヤ教の祭り）", category: C.EVENT },
  // "129": { en: "Crochet", ja: "かぎ針編み", category: C.ARTS },
  "130": { en: "Skateboarder", ja: "スケートボーダー", category: C.PEOPLE },
  // [A] "131": { en: "Clipper", ja: "クリッパー（高速帆船）", category: C.VEHICLE },
  // "132": { en: "Nail", ja: "爪・釘", category: C.BODY },
  "133": { en: "Cola", ja: "コーラ", category: C.FOOD },
  "134": { en: "Cutlery", ja: "カトラリー", category: C.OBJECT },
  // [A] "135": { en: "Menu", ja: "メニュー", category: C.OBJECT },
  // "137": { en: "Sari", ja: "サリー（インドの民族衣装）", category: C.CLOTHING },
  "138": { en: "Plush", ja: "ぬいぐるみ・フラシ天", category: C.OBJECT },
  // "139": { en: "Pocket", ja: "ポケット", category: C.CLOTHING },
  "140": { en: "Neon", ja: "ネオン", category: C.OBJECT },
  "141": { en: "Icicle", ja: "つらら", category: C.NATURE },
  // "142": { en: "Pasteles", ja: "パステレス（中南米の料理）", category: C.FOOD },
  "143": { en: "Chain", ja: "鎖", category: C.OBJECT },
  "144": { en: "Dance", ja: "ダンス", category: C.ACTION },
  // [A] "145": { en: "Dune", ja: "砂丘", category: C.NATURE },
  "146": { en: "Santa claus", ja: "サンタクロース", category: C.CHARACTER },
  // "147": { en: "Thanksgiving", ja: "感謝祭", category: C.EVENT },
  // "148": { en: "Tuxedo", ja: "タキシード", category: C.CLOTHING },
  // [C] "149": { en: "Mouth", ja: "口", category: C.BODY },
  // [A] "150": { en: "Desert", ja: "砂漠", category: C.NATURE },
  "151": { en: "Dinosaur", ja: "恐竜", category: C.ANIMAL },
  // "152": { en: "Mufti", ja: "私服（軍人などの平服）", category: C.CLOTHING },
  "153": { en: "Fire", ja: "火・火災", category: C.NATURE },
  // [A] "154": { en: "Bedroom", ja: "寝室", category: C.PLACE },
  "155": { en: "Goggles", ja: "ゴーグル", category: C.CLOTHING },
  "156": { en: "Dragon", ja: "ドラゴン・竜", category: C.CHARACTER },
  // [A] "157": { en: "Couch", ja: "ソファ", category: C.FURNITURE },
  // [B] "158": { en: "Sledding", ja: "そり遊び", category: C.SPORTS },
  "159": { en: "Cap", ja: "キャップ（帽子）", category: C.CLOTHING },
  // [A] "160": { en: "Whiteboard", ja: "ホワイトボード", category: C.OBJECT },
  "161": { en: "Hat", ja: "帽子", category: C.CLOTHING },
  "162": { en: "Gelato", ja: "ジェラート", category: C.FOOD },
  "163": { en: "Cavalier", ja: "キャバリア（犬種）", category: C.ANIMAL },
  "164": { en: "Beanie", ja: "ニット帽", category: C.CLOTHING },
  "165": { en: "Jersey", ja: "ジャージ・ユニフォーム", category: C.CLOTHING },
  "166": { en: "Scarf", ja: "マフラー・スカーフ", category: C.CLOTHING },
  // [A] "167": { en: "Vacation", ja: "休暇", category: C.CONCEPT },
  "168": { en: "Pitch", ja: "ピッチ（競技場）", category: C.PLACE },
  // [A] "169": { en: "Blackboard", ja: "黒板", category: C.OBJECT },
  // "170": { en: "Deejay", ja: "DJ", category: C.PEOPLE },
  "171": { en: "Monument", ja: "記念碑", category: C.PLACE },
  "172": { en: "Bumper", ja: "バンパー", category: C.VEHICLE },
  "173": { en: "Longboard", ja: "ロングボード", category: C.SPORTS },
  "174": { en: "Waterfowl", ja: "水鳥", category: C.ANIMAL },
  // [C] "175": { en: "Flesh", ja: "肌・肉", category: C.BODY },
  "176": { en: "Net", ja: "ネット・網", category: C.OBJECT },
  // "177": { en: "Icing", ja: "アイシング（糖衣）", category: C.FOOD },
  "178": { en: "Dalmatian", ja: "ダルメシアン", category: C.ANIMAL },
  // [B] "179": { en: "Speedboat", ja: "モーターボート", category: C.VEHICLE },
  "180": { en: "Trunk", ja: "木の幹・トランク", category: C.PLANT },
  "181": { en: "Coffee", ja: "コーヒー", category: C.FOOD },
  "182": { en: "Soccer", ja: "サッカー", category: C.SPORTS },
  "183": { en: "Ragdoll", ja: "ラグドール（猫の品種）", category: C.ANIMAL },
  "184": { en: "Food", ja: "食べ物", category: C.FOOD },
  // [C] "185": { en: "Standing", ja: "立っている", category: C.ACTION },
  // [A] "186": { en: "Fiction", ja: "フィクション", category: C.CONCEPT },
  "187": { en: "Fruit", ja: "果物", category: C.FOOD },
  // "188": { en: "Pho", ja: "フォー", category: C.FOOD },
  "189": { en: "Sparkler", ja: "手持ち花火", category: C.EVENT },
  // "190": { en: "Presentation", ja: "プレゼンテーション", category: C.EVENT },
  "191": { en: "Swing", ja: "ブランコ", category: C.OBJECT },
  "192": { en: "Cairn terrier", ja: "ケアーン・テリア", category: C.ANIMAL },
  // "193": { en: "Forest", ja: "森", category: C.NATURE },
  "194": { en: "Flag", ja: "旗", category: C.OBJECT },
  // [A] "195": { en: "Frigate", ja: "フリゲート艦", category: C.VEHICLE },
  // "196": { en: "Foot", ja: "足", category: C.BODY },
  "197": { en: "Jacket", ja: "ジャケット", category: C.CLOTHING },
  // [A] "199": { en: "Pillow", ja: "枕", category: C.FURNITURE },
  // "201": { en: "Bathing", ja: "入浴・水浴び", category: C.ACTION },
  // [A] "202": { en: "Glacier", ja: "氷河", category: C.NATURE },
  "203": { en: "Gymnastics", ja: "体操", category: C.SPORTS },
  // [C] "204": { en: "Ear", ja: "耳", category: C.BODY },
  // [C] "205": { en: "Flora", ja: "植物相", category: C.PLANT },
  "206": { en: "Shell", ja: "貝殻", category: C.NATURE },
  // "207": { en: "Grandparent", ja: "祖父母", category: C.PEOPLE },
  "208": { en: "Ruins", ja: "遺跡", category: C.PLACE },
  // [C] "209": { en: "Eyelash", ja: "まつげ", category: C.BODY },
  // [A] "210": { en: "Bunk bed", ja: "二段ベッド", category: C.FURNITURE },
  // "211": { en: "Balance", ja: "バランス", category: C.CONCEPT },
  "212": { en: "Backpacking", ja: "バックパッキング", category: C.SPORTS },
  "213": { en: "Horse", ja: "馬", category: C.ANIMAL },
  "214": { en: "Glitter", ja: "ラメ・きらめき", category: C.MATERIAL },
  "215": { en: "Saucer", ja: "ソーサー（受け皿）", category: C.OBJECT },
  // [C] "216": { en: "Hair", ja: "髪", category: C.BODY },
  "217": { en: "Miniature", ja: "ミニチュア", category: C.OBJECT },
  "218": { en: "Crowd", ja: "群衆", category: C.PEOPLE },
  // [A] "219": { en: "Curtain", ja: "カーテン", category: C.FURNITURE },
  // [A] "220": { en: "Icon", ja: "アイコン", category: C.IMAGE },
  "221": {
    en: "Pixie-bob",
    ja: "ピクシーボブ（猫の品種）",
    category: C.ANIMAL,
  },
  "222": { en: "Herd", ja: "群れ", category: C.ANIMAL },
  "223": { en: "Insect", ja: "昆虫", category: C.ANIMAL },
  "224": { en: "Ice", ja: "氷", category: C.NATURE },
  // "225": { en: "Bangle", ja: "バングル", category: C.CLOTHING },
  // "226": { en: "Flap", ja: "フラップ・垂れ蓋", category: C.OBJECT },
  "227": { en: "Jewellery", ja: "宝飾品", category: C.CLOTHING },
  "228": { en: "Knitting", ja: "編み物", category: C.ARTS },
  "229": {
    en: "Centrepiece",
    ja: "センターピース（卓上装飾）",
    category: C.OBJECT,
  },
  "230": { en: "Outerwear", ja: "上着", category: C.CLOTHING },
  // [A] "231": { en: "Love", ja: "愛", category: C.CONCEPT },
  // [C] "232": { en: "Muscle", ja: "筋肉", category: C.BODY },
  "233": { en: "Motorcycle", ja: "オートバイ", category: C.VEHICLE },
  "234": { en: "Money", ja: "お金", category: C.OBJECT },
  // [A] "235": { en: "Mosque", ja: "モスク", category: C.PLACE },
  "236": { en: "Tableware", ja: "食器", category: C.OBJECT },
  // [A] "237": { en: "Ballroom", ja: "舞踏場", category: C.PLACE },
  "238": { en: "Kayak", ja: "カヤック", category: C.VEHICLE },
  // [A] "239": { en: "Leisure", ja: "余暇・レジャー", category: C.CONCEPT },
  "240": { en: "Receipt", ja: "レシート", category: C.OBJECT },
  "241": { en: "Lake", ja: "湖", category: C.NATURE },
  "242": { en: "Lighthouse", ja: "灯台", category: C.PLACE },
  "243": { en: "Bridle", ja: "頭絡（馬具）", category: C.OBJECT },
  "244": { en: "Leather", ja: "革", category: C.MATERIAL },
  "245": { en: "Horn", ja: "角・ホルン", category: C.OBJECT },
  "246": { en: "Strap", ja: "ストラップ", category: C.OBJECT },
  "247": { en: "Lego", ja: "レゴ", category: C.OBJECT },
  // [A] "248": { en: "Scuba diving", ja: "スキューバダイビング", category: C.SPORTS },
  "249": { en: "Leggings", ja: "レギンス", category: C.CLOTHING },
  "250": { en: "Pool", ja: "プール", category: C.PLACE },
  "251": { en: "Musical instrument", ja: "楽器", category: C.ARTS },
  // "252": { en: "Musical", ja: "ミュージカル", category: C.ARTS },
  "253": { en: "Metal", ja: "金属", category: C.MATERIAL },
  "254": { en: "Moon", ja: "月", category: C.SPACE },
  "255": { en: "Blazer", ja: "ブレザー", category: C.CLOTHING },
  // "256": { en: "Marriage", ja: "結婚", category: C.EVENT },
  "257": { en: "Mobile phone", ja: "携帯電話", category: C.ELECTRONICS },
  // "258": { en: "Militia", ja: "民兵", category: C.PEOPLE },
  "259": { en: "Tablecloth", ja: "テーブルクロス", category: C.OBJECT },
  "260": { en: "Party", ja: "パーティー", category: C.EVENT },
  // [A] "261": { en: "Nebula", ja: "星雲", category: C.SPACE },
  // "262": { en: "News", ja: "ニュース", category: C.CONCEPT },
  "263": { en: "Newspaper", ja: "新聞", category: C.OBJECT },
  "265": { en: "Piano", ja: "ピアノ", category: C.ARTS },
  "266": { en: "Plant", ja: "植物", category: C.PLANT },
  // [A] "267": { en: "Passport", ja: "パスポート", category: C.OBJECT },
  "268": { en: "Penguin", ja: "ペンギン", category: C.ANIMAL },
  "269": { en: "Shikoku", ja: "四国犬", category: C.ANIMAL },
  "270": { en: "Palace", ja: "宮殿", category: C.PLACE },
  // "271": { en: "Doily", ja: "ドイリー（レースの敷物）", category: C.OBJECT },
  // "272": { en: "Polo", ja: "ポロ（競技）・ポロシャツ", category: C.SPORTS },
  "273": { en: "Paper", ja: "紙", category: C.MATERIAL },
  "274": { en: "Pop music", ja: "ポップ音楽", category: C.ARTS },
  "275": { en: "Skiff", ja: "小舟", category: C.VEHICLE },
  "276": { en: "Pizza", ja: "ピザ", category: C.FOOD },
  "277": { en: "Pet", ja: "ペット", category: C.ANIMAL },
  // "278": { en: "Quilting", ja: "キルティング", category: C.ARTS },
  "279": { en: "Cage", ja: "ケージ・檻", category: C.OBJECT },
  "280": { en: "Skateboard", ja: "スケートボード", category: C.SPORTS },
  // [B] "281": { en: "Surfing", ja: "サーフィン", category: C.SPORTS },
  "282": { en: "Rugby", ja: "ラグビー", category: C.SPORTS },
  // "283": { en: "Lipstick", ja: "口紅", category: C.OBJECT },
  "284": { en: "River", ja: "川", category: C.NATURE },
  "285": { en: "Race", ja: "レース・競走", category: C.SPORTS },
  // "286": { en: "Rowing", ja: "ボート漕ぎ", category: C.SPORTS },
  // [C] "287": { en: "Road", ja: "道路", category: C.PLACE },
  "288": { en: "Running", ja: "ランニング", category: C.SPORTS },
  // "289": { en: "Room", ja: "部屋", category: C.PLACE },
  "290": { en: "Roof", ja: "屋根", category: C.PLACE },
  "291": { en: "Star", ja: "星", category: C.SPACE },
  "292": { en: "Sports", ja: "スポーツ", category: C.SPORTS },
  "293": { en: "Shoe", ja: "靴", category: C.CLOTHING },
  // "294": {
  //   en: "Tubing",
  //   ja: "チュービング（浮き輪での川下り等）",
  //   category: C.SPORTS,
  // },
  // [A] "295": { en: "Space", ja: "宇宙", category: C.SPACE },
  "296": { en: "Sleep", ja: "睡眠", category: C.ACTION },
  // [C] "297": { en: "Skin", ja: "肌", category: C.BODY },
  "298": { en: "Swimming", ja: "水泳", category: C.SPORTS },
  "299": { en: "School", ja: "学校", category: C.PLACE },
  "300": { en: "Sushi", ja: "寿司", category: C.FOOD },
  // [A] "301": { en: "Loveseat", ja: "二人掛けソファ", category: C.FURNITURE },
  // [A] "302": { en: "Superman", ja: "スーパーマン", category: C.CHARACTER },
  // [A] "303": { en: "Cool", ja: "かっこいい", category: C.CONCEPT },
  // [B] "304": { en: "Skiing", ja: "スキー", category: C.SPORTS },
  // [A] "305": { en: "Submarine", ja: "潜水艦", category: C.VEHICLE },
  "306": { en: "Song", ja: "歌", category: C.ARTS },
  // [A] "307": { en: "Class", ja: "授業・教室", category: C.PLACE },
  "308": { en: "Skyscraper", ja: "超高層ビル", category: C.PLACE },
  "309": { en: "Volcano", ja: "火山", category: C.NATURE },
  // [A] "310": { en: "Television", ja: "テレビ", category: C.ELECTRONICS },
  "311": { en: "Rein", ja: "手綱", category: C.OBJECT },
  "312": { en: "Tattoo", ja: "タトゥー", category: C.BODY },
  "313": { en: "Train", ja: "電車", category: C.VEHICLE },
  "314": { en: "Handrail", ja: "手すり", category: C.OBJECT },
  "315": { en: "Cup", ja: "カップ", category: C.OBJECT },
  "316": { en: "Vehicle", ja: "乗り物", category: C.VEHICLE },
  "317": { en: "Handbag", ja: "ハンドバッグ", category: C.CLOTHING },
  // [A] "318": { en: "Lampshade", ja: "ランプシェード", category: C.FURNITURE },
  // [A] "319": { en: "Event", ja: "イベント", category: C.CONCEPT },
  "320": { en: "Wine", ja: "ワイン", category: C.FOOD },
  "321": { en: "Wing", ja: "翼", category: C.ANIMAL },
  "322": { en: "Wheel", ja: "車輪", category: C.VEHICLE },
  // [B] "323": { en: "Wakeboarding", ja: "ウェイクボード", category: C.SPORTS },
  // [A] "324": { en: "Web page", ja: "ウェブページ", category: C.IMAGE },
  "327": { en: "Ranch", ja: "牧場", category: C.PLACE },
  "328": { en: "Fishing", ja: "釣り", category: C.SPORTS },
  // "329": { en: "Heart", ja: "ハート・心臓", category: C.CONCEPT },
  "330": { en: "Cotton", ja: "綿", category: C.MATERIAL },
  "331": { en: "Cappuccino", ja: "カプチーノ", category: C.FOOD },
  "332": { en: "Bread", ja: "パン", category: C.FOOD },
  "333": { en: "Sand", ja: "砂", category: C.NATURE },
  "335": { en: "Museum", ja: "博物館・美術館", category: C.PLACE },
  "336": { en: "Helicopter", ja: "ヘリコプター", category: C.VEHICLE },
  "337": { en: "Mountain", ja: "山", category: C.NATURE },
  "338": { en: "Duck", ja: "カモ・アヒル", category: C.ANIMAL },
  "339": { en: "Soil", ja: "土", category: C.NATURE },
  "340": { en: "Turtle", ja: "カメ", category: C.ANIMAL },
  "341": { en: "Crocodile", ja: "ワニ", category: C.ANIMAL },
  "342": { en: "Musician", ja: "ミュージシャン", category: C.PEOPLE },
  // "343": { en: "Sneakers", ja: "スニーカー", category: C.CLOTHING },
  // "344": { en: "Wool", ja: "羊毛", category: C.MATERIAL },
  "345": { en: "Ring", ja: "指輪", category: C.CLOTHING },
  "346": { en: "Singer", ja: "歌手", category: C.PEOPLE },
  // "347": { en: "Carnival", ja: "カーニバル", category: C.EVENT },
  // [B] "348": { en: "Snowboarding", ja: "スノーボード", category: C.SPORTS },
  // [B] "349": { en: "Waterskiing", ja: "水上スキー", category: C.SPORTS },
  "350": { en: "Wall", ja: "壁", category: C.PLACE },
  // [A] "351": { en: "Rocket", ja: "ロケット", category: C.SPACE },
  // [A] "352": { en: "Countertop", ja: "調理台", category: C.FURNITURE },
  "353": { en: "Beach", ja: "砂浜・海辺", category: C.NATURE },
  "354": { en: "Rainbow", ja: "虹", category: C.WEATHER },
  "355": { en: "Branch", ja: "枝", category: C.PLANT },
  // [C] "356": { en: "Moustache", ja: "口ひげ", category: C.BODY },
  "357": { en: "Garden", ja: "庭園", category: C.PLACE },
  "358": { en: "Gown", ja: "ガウン・ドレス", category: C.CLOTHING },
  "359": { en: "Field", ja: "野原・畑", category: C.NATURE },
  "360": { en: "Dog", ja: "犬", category: C.ANIMAL },
  // [A] "361": { en: "Superhero", ja: "スーパーヒーロー", category: C.CHARACTER },
  "362": { en: "Flower", ja: "花", category: C.PLANT },
  "363": { en: "Placemat", ja: "ランチョンマット", category: C.OBJECT },
  // "364": { en: "Subwoofer", ja: "サブウーファー", category: C.ELECTRONICS },
  // [A] "365": { en: "Cathedral", ja: "大聖堂", category: C.PLACE },
  "366": { en: "Building", ja: "建物", category: C.PLACE },
  "367": { en: "Airplane", ja: "飛行機", category: C.VEHICLE },
  "368": { en: "Fur", ja: "毛皮", category: C.MATERIAL },
  "369": { en: "Bull", ja: "雄牛", category: C.ANIMAL },
  "370": { en: "Bench", ja: "ベンチ", category: C.FURNITURE },
  "371": { en: "Temple", ja: "寺院", category: C.PLACE },
  "372": { en: "Butterfly", ja: "蝶", category: C.ANIMAL },
  // "373": { en: "Model", ja: "モデル・模型", category: C.PEOPLE },
  "374": { en: "Marathon", ja: "マラソン", category: C.SPORTS },
  // "375": { en: "Needlework", ja: "針仕事・刺繍", category: C.ARTS },
  // [A] "376": { en: "Kitchen", ja: "台所", category: C.PLACE },
  "377": { en: "Castle", ja: "城", category: C.PLACE },
  // [A] "378": { en: "Aurora", ja: "オーロラ", category: C.WEATHER },
  "379": { en: "Larva", ja: "幼虫", category: C.ANIMAL },
  "380": { en: "Racing", ja: "レース", category: C.SPORTS },
  "382": { en: "Airliner", ja: "旅客機", category: C.VEHICLE },
  "383": { en: "Dam", ja: "ダム", category: C.PLACE },
  // "384": { en: "Textile", ja: "織物・布地", category: C.MATERIAL },
  // "385": { en: "Groom", ja: "新郎", category: C.PEOPLE },
  // [A] "386": { en: "Fun", ja: "楽しい", category: C.CONCEPT },
  "387": { en: "Steaming", ja: "湯気", category: C.NATURE },
  "388": { en: "Vegetable", ja: "野菜", category: C.FOOD },
  "389": { en: "Unicycle", ja: "一輪車", category: C.VEHICLE },
  "390": { en: "Jeans", ja: "ジーンズ", category: C.CLOTHING },
  "391": { en: "Flowerpot", ja: "植木鉢", category: C.OBJECT },
  // [A] "392": { en: "Drawer", ja: "引き出し", category: C.FURNITURE },
  "393": { en: "Cake", ja: "ケーキ", category: C.FOOD },
  // "394": { en: "Armrest", ja: "肘掛け", category: C.FURNITURE },
  // "395": { en: "Aviation", ja: "航空", category: C.VEHICLE },
  "397": { en: "Fog", ja: "霧", category: C.WEATHER },
  "398": { en: "Fireworks", ja: "花火", category: C.EVENT },
  "399": { en: "Farm", ja: "農場", category: C.PLACE },
  // [B] "400": { en: "Seal", ja: "アザラシ", category: C.ANIMAL },
  "401": { en: "Shelf", ja: "棚", category: C.FURNITURE },
  // [C] "402": { en: "Bangs", ja: "前髪", category: C.BODY },
  // "403": { en: "Lightning", ja: "稲妻", category: C.WEATHER },
  // "404": { en: "Van", ja: "バン", category: C.VEHICLE },
  "405": { en: "Sphynx", ja: "スフィンクス（猫の品種）", category: C.ANIMAL },
  "406": { en: "Tire", ja: "タイヤ", category: C.VEHICLE },
  // "407": { en: "Denim", ja: "デニム", category: C.MATERIAL },
  "408": { en: "Prairie", ja: "草原", category: C.NATURE },
  // [A] "409": { en: "Snorkeling", ja: "シュノーケリング", category: C.SPORTS },
  "410": { en: "Umbrella", ja: "傘", category: C.OBJECT },
  "411": { en: "Asphalt", ja: "アスファルト", category: C.MATERIAL },
  // [B] "412": { en: "Sailboat", ja: "帆船・ヨット", category: C.VEHICLE },
  // "413": { en: "Basset hound", ja: "バセット・ハウンド", category: C.ANIMAL },
  // [A] "414": { en: "Pattern", ja: "模様・柄", category: C.IMAGE },
  // "415": { en: "Supper", ja: "夕食", category: C.FOOD },
  // "416": { en: "Veil", ja: "ベール", category: C.CLOTHING },
  "417": { en: "Waterfall", ja: "滝", category: C.NATURE },
  "419": { en: "Lunch", ja: "昼食", category: C.FOOD },
  // [A] "420": { en: "Odometer", ja: "走行距離計", category: C.VEHICLE },
  "421": { en: "Baby", ja: "赤ちゃん", category: C.PEOPLE },
  "422": { en: "Glasses", ja: "眼鏡", category: C.CLOTHING },
  "423": { en: "Car", ja: "自動車", category: C.VEHICLE },
  // "424": { en: "Aircraft", ja: "航空機", category: C.VEHICLE },
  // [C] "425": { en: "Hand", ja: "手", category: C.BODY },
  // [A] "426": { en: "Rodeo", ja: "ロデオ", category: C.EVENT },
  // [A] "427": { en: "Canyon", ja: "峡谷", category: C.NATURE },
  "428": { en: "Meal", ja: "食事", category: C.FOOD },
  "429": { en: "Softball", ja: "ソフトボール", category: C.SPORTS },
  "430": { en: "Alcohol", ja: "酒類", category: C.FOOD },
  // "431": { en: "Bride", ja: "花嫁", category: C.PEOPLE },
  // [A] "432": { en: "Swamp", ja: "沼地", category: C.NATURE },
  "433": { en: "Pie", ja: "パイ", category: C.FOOD },
  "434": { en: "Bag", ja: "かばん", category: C.CLOTHING },
  // [A] "435": { en: "Joker", ja: "ジョーカー（道化・悪役）", category: C.CHARACTER },
  // [A] "436": { en: "Supervillain", ja: "悪役", category: C.CHARACTER },
  // "437": { en: "Army", ja: "軍隊", category: C.PEOPLE },
  "438": { en: "Canoe", ja: "カヌー", category: C.VEHICLE },
  "439": { en: "Selfie", ja: "自撮り", category: C.IMAGE },
  "440": { en: "Rickshaw", ja: "人力車", category: C.VEHICLE },
  "441": { en: "Barn", ja: "納屋", category: C.PLACE },
  "442": { en: "Archery", ja: "アーチェリー", category: C.SPORTS },
  // [A] "443": { en: "Aerospace engineering", ja: "航空宇宙工学", category: C.SPACE },
  "445": { en: "Storm", ja: "嵐", category: C.WEATHER },
  "446": { en: "Helmet", ja: "ヘルメット", category: C.CLOTHING },
};

export const OBJECT_LABEL_OFFSET = 1000;

export const BASE_KEYWORD_INDEXES = [1, 20, 153, 191, 298, 328, 360, 398] as const;

export const OBJECT_LABEL: Record<string, LabelInfo> = {
  "1000": { en: "Smart speaker", ja: "スマートスピーカー", category: C.ELECTRONICS },
  "1001": { en: "Virtual reality headset", ja: "VRヘッドセット", category: C.ELECTRONICS },
  "1002": { en: "Tumbler", ja: "タンブラー", category: C.OBJECT },
  "1003": { en: "Electric kettle", ja: "電気ケトル", category: C.ELECTRONICS },
  "1004": { en: "Electric razor", ja: "電気かみそり", category: C.ELECTRONICS },
  "1005": { en: "Packaged goods", ja: "包装された商品", category: C.OBJECT },
  "1006": { en: "Kid bike", ja: "子ども用自転車", category: C.VEHICLE },
  "1007": { en: "2D barcode", ja: "二次元バーコード", category: C.OBJECT },
  "1008": { en: "1D barcode", ja: "バーコード", category: C.OBJECT },
  "1009": { en: "Water bottle", ja: "水筒・ボトル", category: C.OBJECT },
  "1010": { en: "Tortoise", ja: "リクガメ", category: C.ANIMAL },
  "1011": { en: "Cooker", ja: "調理器", category: C.ELECTRONICS },
  "1012": { en: "Container", ja: "容器", category: C.OBJECT },
  "1013": { en: "Magpie", ja: "カササギ", category: C.ANIMAL },
  "1014": { en: "Sea turtle", ja: "ウミガメ", category: C.ANIMAL },
  "1015": { en: "Football", ja: "フットボール（ボール）", category: C.SPORTS },
  "1016": { en: "Vacuum flask", ja: "魔法瓶", category: C.OBJECT },
  "1017": { en: "Ambulance", ja: "救急車", category: C.VEHICLE },
  "1018": { en: "Ladder", ja: "はしご", category: C.OBJECT },
  "1019": { en: "Toothbrush", ja: "歯ブラシ", category: C.OBJECT },
  "1020": { en: "Syringe", ja: "注射器", category: C.OBJECT },
  "1021": { en: "Sink", ja: "流し台・洗面台", category: C.FURNITURE },
  "1022": { en: "Toy", ja: "おもちゃ", category: C.OBJECT },
  "1023": { en: "T-shirt", ja: "Tシャツ", category: C.CLOTHING },
  "1024": { en: "Organ", ja: "オルガン", category: C.ARTS },
  "1025": { en: "Cassette deck", ja: "カセットデッキ", category: C.ELECTRONICS },
  "1026": { en: "Apple", ja: "りんご", category: C.FOOD },
  "1027": { en: "Paddle", ja: "パドル・オール", category: C.SPORTS },
  "1028": { en: "Snowman", ja: "雪だるま", category: C.OBJECT },
  "1029": { en: "Beer", ja: "ビール", category: C.FOOD },
  "1030": { en: "Bridge", ja: "橋", category: C.PLACE },
  "1031": { en: "Board game", ja: "ボードゲーム", category: C.OBJECT },
  "1032": { en: "Parking meter", ja: "パーキングメーター", category: C.OBJECT },
  "1033": { en: "Traffic light", ja: "信号機", category: C.OBJECT },
  "1034": { en: "Croissant", ja: "クロワッサン", category: C.FOOD },
  "1035": { en: "Cucumber", ja: "きゅうり", category: C.FOOD },
  "1036": { en: "Radish", ja: "大根・ラディッシュ", category: C.FOOD },
  "1037": { en: "Towel", ja: "タオル", category: C.OBJECT },
  "1038": { en: "Doll", ja: "人形", category: C.OBJECT },
  "1039": { en: "Notebook", ja: "ノート", category: C.OBJECT },
  "1040": { en: "Washing machine", ja: "洗濯機", category: C.ELECTRONICS },
  "1041": { en: "Glove", ja: "手袋", category: C.CLOTHING },
  "1042": { en: "Vinyl record", ja: "レコード盤", category: C.ARTS },
  "1043": { en: "Tick", ja: "ダニ", category: C.ANIMAL },
  "1044": { en: "Belt", ja: "ベルト", category: C.CLOTHING },
  "1045": { en: "Sunglasses", ja: "サングラス", category: C.CLOTHING },
  "1046": { en: "Action figure", ja: "アクションフィギュア", category: C.OBJECT },
  "1047": { en: "Banjo", ja: "バンジョー", category: C.ARTS },
  "1048": { en: "Cart", ja: "カート・台車", category: C.VEHICLE },
  "1049": { en: "Ball", ja: "ボール", category: C.SPORTS },
  "1050": { en: "Backpack", ja: "リュックサック", category: C.CLOTHING },
  "1051": { en: "Bicycle", ja: "自転車", category: C.VEHICLE },
  "1052": { en: "Sweater", ja: "セーター", category: C.CLOTHING },
  "1053": { en: "Stadium", ja: "スタジアム", category: C.PLACE },
  "1054": { en: "Home appliance", ja: "家電", category: C.ELECTRONICS },
  "1055": { en: "Centipede", ja: "ムカデ", category: C.ANIMAL },
  "1056": { en: "Boat", ja: "ボート", category: C.VEHICLE },
  "1057": { en: "Lighting", ja: "照明", category: C.FURNITURE },
  "1058": { en: "Surfboard", ja: "サーフボード", category: C.SPORTS },
  "1059": { en: "Chopsticks", ja: "箸", category: C.OBJECT },
  "1060": { en: "Boot", ja: "ブーツ", category: C.CLOTHING },
  "1061": { en: "Headphones", ja: "ヘッドホン", category: C.ELECTRONICS },
  "1062": { en: "Hot dog", ja: "ホットドッグ", category: C.FOOD },
  "1063": { en: "Shorts", ja: "ショートパンツ", category: C.CLOTHING },
  "1064": { en: "Bus", ja: "バス", category: C.VEHICLE },
  "1065": { en: "Camera lens", ja: "カメラレンズ", category: C.ELECTRONICS },
  "1066": { en: "Screwdriver", ja: "ドライバー（工具）", category: C.OBJECT },
  "1067": { en: "Bicycle wheel", ja: "自転車の車輪", category: C.VEHICLE },
  "1068": { en: "Flash", ja: "フラッシュ（ストロボ）", category: C.ELECTRONICS },
  "1069": { en: "Barge", ja: "はしけ・平底船", category: C.VEHICLE },
  "1070": { en: "Battery", ja: "電池", category: C.ELECTRONICS },
  "1071": { en: "Laptop", ja: "ノートパソコン", category: C.ELECTRONICS },
  "1072": { en: "Miniskirt", ja: "ミニスカート", category: C.CLOTHING },
  "1073": { en: "Drill", ja: "ドリル", category: C.OBJECT },
  "1074": { en: "Dress", ja: "ドレス・ワンピース", category: C.CLOTHING },
  "1075": { en: "Bear", ja: "クマ", category: C.ANIMAL },
  "1076": { en: "Waffle", ja: "ワッフル", category: C.FOOD },
  "1077": { en: "Pancake", ja: "パンケーキ", category: C.FOOD },
  "1078": { en: "Brown bear", ja: "ヒグマ", category: C.ANIMAL },
  "1079": { en: "Woodpecker", ja: "キツツキ", category: C.ANIMAL },
  "1080": { en: "Blue jay", ja: "アオカケス", category: C.ANIMAL },
  "1081": { en: "Pretzel", ja: "プレッツェル", category: C.FOOD },
  "1082": { en: "Bagel", ja: "ベーグル", category: C.FOOD },
  "1083": { en: "Teapot", ja: "ティーポット", category: C.OBJECT },
  "1084": { en: "Person", ja: "人", category: C.PEOPLE },
  "1085": { en: "Bow and arrow", ja: "弓矢", category: C.SPORTS },
  "1086": { en: "Swimwear", ja: "水着", category: C.CLOTHING },
  "1087": { en: "Brassiere", ja: "ブラジャー", category: C.CLOTHING },
  "1088": { en: "Bee", ja: "ハチ", category: C.ANIMAL },
  "1089": { en: "Bat", ja: "コウモリ", category: C.ANIMAL },
  "1090": { en: "Starfish", ja: "ヒトデ", category: C.ANIMAL },
  "1091": { en: "Popcorn", ja: "ポップコーン", category: C.FOOD },
  "1092": { en: "Burrito", ja: "ブリトー", category: C.FOOD },
  "1093": { en: "Chainsaw", ja: "チェーンソー", category: C.OBJECT },
  "1094": { en: "Balloon", ja: "風船", category: C.OBJECT },
  "1095": { en: "Wrench", ja: "レンチ・スパナ", category: C.OBJECT },
  "1096": { en: "Tent", ja: "テント", category: C.OBJECT },
  "1097": { en: "License plate", ja: "ナンバープレート", category: C.VEHICLE },
  "1098": { en: "Lantern", ja: "ランタン", category: C.OBJECT },
  "1099": { en: "Toaster", ja: "トースター", category: C.ELECTRONICS },
  "1100": { en: "Flashlight", ja: "懐中電灯", category: C.OBJECT },
  "1101": { en: "Tiara", ja: "ティアラ", category: C.CLOTHING },
  "1102": { en: "Limousine", ja: "リムジン", category: C.VEHICLE },
  "1103": { en: "Necklace", ja: "ネックレス", category: C.CLOTHING },
  "1104": { en: "Bracelet", ja: "ブレスレット", category: C.CLOTHING },
  "1105": { en: "Scissors", ja: "はさみ", category: C.OBJECT },
  "1106": { en: "Computer keyboard", ja: "キーボード", category: C.ELECTRONICS },
  "1107": { en: "Printer", ja: "プリンター", category: C.ELECTRONICS },
  "1108": { en: "Traffic sign", ja: "交通標識", category: C.OBJECT },
  "1109": { en: "Chair", ja: "椅子", category: C.FURNITURE },
  "1110": { en: "Shirt", ja: "シャツ", category: C.CLOTHING },
  "1111": { en: "Poster", ja: "ポスター", category: C.ARTS },
  "1112": { en: "Thermostat", ja: "サーモスタット", category: C.ELECTRONICS },
  "1113": { en: "Cheese", ja: "チーズ", category: C.FOOD },
  "1114": { en: "Sock", ja: "靴下", category: C.CLOTHING },
  "1115": { en: "Fire hydrant", ja: "消火栓", category: C.OBJECT },
  "1116": { en: "Barbecue grill", ja: "バーベキューグリル", category: C.OBJECT },
  "1117": { en: "Earrings", ja: "イヤリング・ピアス", category: C.CLOTHING },
  "1118": { en: "Tie", ja: "ネクタイ", category: C.CLOTHING },
  "1119": { en: "Cabinetry", ja: "戸棚", category: C.FURNITURE },
  "1120": { en: "Suitcase", ja: "スーツケース", category: C.OBJECT },
  "1121": { en: "Bodysuit", ja: "ボディスーツ", category: C.CLOTHING },
  "1122": { en: "Business card", ja: "名刺", category: C.OBJECT },
  "1123": { en: "Vest", ja: "ベスト", category: C.CLOTHING },
  "1124": { en: "Muffin", ja: "マフィン", category: C.FOOD },
  "1125": { en: "Bidet", ja: "ビデ", category: C.FURNITURE },
  "1126": { en: "Expresso machine", ja: "エスプレッソマシン", category: C.ELECTRONICS },
  "1127": { en: "Snack", ja: "おやつ・スナック", category: C.FOOD },
  "1128": { en: "Snowmobile", ja: "スノーモービル", category: C.VEHICLE },
  "1129": { en: "Clock", ja: "時計", category: C.OBJECT },
  "1130": { en: "Camel", ja: "ラクダ", category: C.ANIMAL },
  "1131": { en: "Figurine", ja: "小さな像・フィギュア", category: C.ARTS },
  "1132": { en: "Cattle", ja: "牛", category: C.ANIMAL },
  "1133": { en: "Jet ski", ja: "水上バイク", category: C.VEHICLE },
  "1134": { en: "Coat", ja: "コート", category: C.CLOTHING },
  "1135": { en: "Suit", ja: "スーツ", category: C.CLOTHING },
  "1136": { en: "Desk", ja: "机", category: C.FURNITURE },
  "1137": { en: "Cat", ja: "猫", category: C.ANIMAL },
  "1138": { en: "Bronze sculpture", ja: "ブロンズ像", category: C.ARTS },
  "1139": { en: "Juice", ja: "ジュース", category: C.FOOD },
  "1140": { en: "Basket", ja: "かご", category: C.OBJECT },
  "1141": { en: "Gondola", ja: "ゴンドラ", category: C.VEHICLE },
  "1142": { en: "Beetle", ja: "甲虫", category: C.ANIMAL },
  "1143": { en: "Cannon", ja: "大砲", category: C.OBJECT },
  "1144": { en: "Mouse", ja: "マウス（ネズミ／パソコン）", category: C.OBJECT },
  "1145": { en: "Wine bottle", ja: "ワインボトル", category: C.FOOD },
  "1146": { en: "Comb", ja: "くし", category: C.OBJECT },
  "1147": { en: "Slipper", ja: "スリッパ", category: C.CLOTHING },
  "1148": { en: "Stuffed toy", ja: "ぬいぐるみ", category: C.OBJECT },
  "1149": { en: "Cookie", ja: "クッキー", category: C.FOOD },
  "1150": { en: "Fountain", ja: "噴水", category: C.PLACE },
  "1151": { en: "Wine cooler", ja: "ワインクーラー", category: C.OBJECT },
  "1152": { en: "Coin", ja: "硬貨", category: C.OBJECT },
  "1153": { en: "Calculator", ja: "電卓", category: C.ELECTRONICS },
  "1154": { en: "Cocktail", ja: "カクテル", category: C.FOOD },
  "1155": { en: "Menu", ja: "メニュー", category: C.OBJECT },
  "1156": { en: "Computer monitor", ja: "モニター", category: C.ELECTRONICS },
  "1157": { en: "Box", ja: "箱", category: C.OBJECT },
  "1158": { en: "Stapler", ja: "ホッチキス", category: C.OBJECT },
  "1159": { en: "Christmas tree", ja: "クリスマスツリー", category: C.EVENT },
  "1160": { en: "Cowboy hat", ja: "カウボーイハット", category: C.CLOTHING },
  "1161": { en: "Video camera", ja: "ビデオカメラ", category: C.ELECTRONICS },
  "1162": { en: "Flip-flops", ja: "ビーチサンダル", category: C.CLOTHING },
  "1163": { en: "Bean bag", ja: "ビーズクッション", category: C.FURNITURE },
  "1164": { en: "Drum", ja: "太鼓・ドラム", category: C.ARTS },
  "1165": { en: "Dessert", ja: "デザート", category: C.FOOD },
  "1166": { en: "Wine rack", ja: "ワインラック", category: C.FURNITURE },
  "1167": { en: "Drink", ja: "飲み物", category: C.FOOD },
  "1168": { en: "Zucchini", ja: "ズッキーニ", category: C.FOOD },
  "1169": { en: "Ladle", ja: "おたま", category: C.OBJECT },
  "1170": { en: "Baseball cap", ja: "野球帽", category: C.CLOTHING },
  "1171": { en: "Smartwatch", ja: "スマートウォッチ", category: C.ELECTRONICS },
  "1172": { en: "Dairy", ja: "乳製品", category: C.FOOD },
  "1173": { en: "Bib", ja: "よだれかけ", category: C.CLOTHING },
  "1174": { en: "Bowtie", ja: "蝶ネクタイ", category: C.CLOTHING },
  "1175": { en: "Toy train", ja: "おもちゃの電車", category: C.OBJECT },
  "1176": { en: "Dice", ja: "サイコロ", category: C.OBJECT },
  "1177": { en: "Oven", ja: "オーブン", category: C.ELECTRONICS },
  "1178": { en: "Dinosaur", ja: "恐竜", category: C.ANIMAL },
  "1179": { en: "Display device", ja: "ディスプレイ", category: C.ELECTRONICS },
  "1180": { en: "Goggles", ja: "ゴーグル", category: C.CLOTHING },
  "1181": { en: "Wallet", ja: "財布", category: C.OBJECT },
  "1182": { en: "Ratchet", ja: "ラチェット（工具）", category: C.OBJECT },
  "1183": { en: "Couch", ja: "ソファ", category: C.FURNITURE },
  "1184": { en: "Cricket ball", ja: "クリケットボール", category: C.SPORTS },
  "1185": { en: "Winter melon", ja: "冬瓜", category: C.FOOD },
  "1186": { en: "Spatula", ja: "ヘラ・フライ返し", category: C.OBJECT },
  "1187": { en: "Cap", ja: "キャップ（帽子）", category: C.CLOTHING },
  "1188": { en: "Whiteboard", ja: "ホワイトボード", category: C.OBJECT },
  "1189": { en: "Pencil sharpener", ja: "鉛筆削り", category: C.OBJECT },
  "1190": { en: "Door", ja: "ドア", category: C.PLACE },
  "1191": { en: "Hat", ja: "帽子", category: C.CLOTHING },
  "1192": { en: "Shower", ja: "シャワー", category: C.FURNITURE },
  "1193": { en: "Lemur", ja: "キツネザル", category: C.ANIMAL },
  "1194": { en: "Fedora", ja: "中折れ帽", category: C.CLOTHING },
  "1195": { en: "Guacamole", ja: "ワカモレ", category: C.FOOD },
  "1196": { en: "Scarf", ja: "スカーフ・マフラー", category: C.CLOTHING },
  "1197": { en: "Dolphin", ja: "イルカ", category: C.ANIMAL },
  "1198": { en: "Sombrero", ja: "ソンブレロ", category: C.CLOTHING },
  "1199": { en: "Tin can", ja: "缶", category: C.OBJECT },
  "1200": { en: "Mug", ja: "マグカップ", category: C.OBJECT },
  "1201": { en: "Tap", ja: "蛇口", category: C.FURNITURE },
  "1202": { en: "Harbor seal", ja: "ゼニガタアザラシ", category: C.ANIMAL },
  "1203": { en: "Stretcher", ja: "担架", category: C.OBJECT },
  "1204": { en: "Lock", ja: "錠前", category: C.OBJECT },
  "1205": { en: "Roller skates", ja: "ローラースケート", category: C.SPORTS },
  "1206": { en: "Coffee cup", ja: "コーヒーカップ", category: C.OBJECT },
  "1207": { en: "Straw hat", ja: "麦わら帽子", category: C.CLOTHING },
  "1208": { en: "Overall", ja: "オーバーオール", category: C.CLOTHING },
  "1209": { en: "Cutting board", ja: "まな板", category: C.OBJECT },
  "1210": { en: "Blender", ja: "ミキサー", category: C.ELECTRONICS },
  "1211": { en: "Stove", ja: "コンロ", category: C.ELECTRONICS },
  "1212": { en: "Stop sign", ja: "一時停止標識", category: C.OBJECT },
  "1213": { en: "Volleyball", ja: "バレーボール", category: C.SPORTS },
  "1214": { en: "Vase", ja: "花瓶", category: C.OBJECT },
  "1215": { en: "Slow cooker", ja: "スロークッカー", category: C.ELECTRONICS },
  "1216": { en: "Post-it note", ja: "付箋", category: C.OBJECT },
  "1217": { en: "Wardrobe", ja: "洋服だんす", category: C.FURNITURE },
  "1218": { en: "Pinwheel", ja: "風車（おもちゃ）", category: C.OBJECT },
  "1219": { en: "Whisk", ja: "泡立て器", category: C.OBJECT },
  "1220": { en: "Paper towel", ja: "ペーパータオル", category: C.OBJECT },
  "1221": { en: "Food", ja: "食べ物", category: C.FOOD },
  "1222": { en: "Sun hat", ja: "日よけ帽", category: C.CLOTHING },
  "1223": { en: "Flying disc", ja: "フライングディスク", category: C.SPORTS },
  "1224": { en: "Chandelier", ja: "シャンデリア", category: C.FURNITURE },
  "1225": { en: "Skirt", ja: "スカート", category: C.CLOTHING },
  "1226": { en: "Gas stove", ja: "ガスコンロ", category: C.ELECTRONICS },
  "1227": { en: "Salt and pepper shakers", ja: "塩・こしょう入れ", category: C.OBJECT },
  "1228": { en: "Mechanical fan", ja: "扇風機", category: C.ELECTRONICS },
  "1229": { en: "Face powder", ja: "フェイスパウダー", category: C.OBJECT },
  "1230": { en: "Fax", ja: "ファックス", category: C.ELECTRONICS },
  "1231": { en: "Fruit", ja: "果物", category: C.FOOD },
  "1232": { en: "French fries", ja: "フライドポテト", category: C.FOOD },
  "1233": { en: "Nightstand", ja: "ナイトテーブル", category: C.FURNITURE },
  "1234": { en: "Barrel", ja: "樽", category: C.OBJECT },
  "1235": { en: "Kite", ja: "凧", category: C.SPORTS },
  "1236": { en: "Tart", ja: "タルト", category: C.FOOD },
  "1237": { en: "Treadmill", ja: "ランニングマシン", category: C.SPORTS },
  "1238": { en: "Fox", ja: "キツネ", category: C.ANIMAL },
  "1239": { en: "Throw pillow", ja: "クッション", category: C.FURNITURE },
  "1240": { en: "Flag", ja: "旗", category: C.OBJECT },
  "1241": { en: "Horn", ja: "ホルン", category: C.ARTS },
  "1242": { en: "Window blind", ja: "ブラインド", category: C.FURNITURE },
  "1243": { en: "Golf cart", ja: "ゴルフカート", category: C.VEHICLE },
  "1244": { en: "Jacket", ja: "ジャケット", category: C.CLOTHING },
  "1245": { en: "Jumpsuit", ja: "つなぎ・ジャンプスーツ", category: C.CLOTHING },
  "1246": { en: "Egg", ja: "卵", category: C.FOOD },
  "1247": { en: "Street light", ja: "街灯", category: C.OBJECT },
  "1248": { en: "Guitar", ja: "ギター", category: C.ARTS },
  "1249": { en: "Pillow", ja: "枕", category: C.FURNITURE },
  "1250": { en: "Isopod", ja: "ダンゴムシ・ワラジムシ", category: C.ANIMAL },
  "1251": { en: "Visor", ja: "サンバイザー", category: C.CLOTHING },
  "1252": { en: "Grape", ja: "ぶどう", category: C.FOOD },
  "1253": { en: "Bookcase", ja: "本棚", category: C.FURNITURE },
  "1254": { en: "Candle hold", ja: "燭台", category: C.OBJECT },
  "1255": { en: "Power outlet", ja: "コンセント", category: C.ELECTRONICS },
  "1256": { en: "Panda", ja: "パンダ", category: C.ANIMAL },
  "1257": { en: "Giraffe", ja: "キリン", category: C.ANIMAL },
  "1258": { en: "Door handle", ja: "ドアノブ", category: C.OBJECT },
  "1259": { en: "Rhinoceros", ja: "サイ", category: C.ANIMAL },
  "1260": { en: "Bathtub", ja: "浴槽", category: C.FURNITURE },
  "1261": { en: "Stroller", ja: "ベビーカー", category: C.VEHICLE },
  "1262": { en: "Goldfish", ja: "金魚", category: C.ANIMAL },
  "1263": { en: "Houseplant", ja: "観葉植物", category: C.PLANT },
  "1264": { en: "Goat", ja: "ヤギ", category: C.ANIMAL },
  "1265": { en: "Baseball bat", ja: "野球のバット", category: C.SPORTS },
  "1266": { en: "Baseball glove", ja: "野球のグローブ", category: C.SPORTS },
  "1267": { en: "Top", ja: "トップス", category: C.CLOTHING },
  "1268": { en: "Grandfather clock", ja: "大型の振り子時計", category: C.FURNITURE },
  "1269": { en: "Light switch", ja: "照明スイッチ", category: C.ELECTRONICS },
  "1270": { en: "House", ja: "家", category: C.PLACE },
  "1271": { en: "Stationary bicycle", ja: "エアロバイク", category: C.SPORTS },
  "1272": { en: "Hammer", ja: "ハンマー", category: C.OBJECT },
  "1273": { en: "Ceiling fan", ja: "シーリングファン", category: C.ELECTRONICS },
  "1274": { en: "Keychain", ja: "キーホルダー", category: C.OBJECT },
  "1275": { en: "Adhesive tape", ja: "粘着テープ", category: C.OBJECT },
  "1276": { en: "Harp", ja: "ハープ", category: C.ARTS },
  "1277": { en: "Blanket", ja: "毛布", category: C.OBJECT },
  "1278": { en: "Sandal", ja: "サンダル", category: C.CLOTHING },
  "1279": { en: "Bicycle helmet", ja: "自転車用ヘルメット", category: C.CLOTHING },
  "1280": { en: "Handheld video game console", ja: "携帯ゲーム機", category: C.ELECTRONICS },
  "1281": { en: "Saucer", ja: "ソーサー（受け皿）", category: C.OBJECT },
  "1282": { en: "Teacup", ja: "ティーカップ", category: C.OBJECT },
  "1283": { en: "Harpsichord", ja: "チェンバロ", category: C.ARTS },
  "1284": { en: "Heater", ja: "ヒーター", category: C.ELECTRONICS },
  "1285": { en: "Harmonica", ja: "ハーモニカ", category: C.ARTS },
  "1286": { en: "Hamster", ja: "ハムスター", category: C.ANIMAL },
  "1287": { en: "Hardware", ja: "金物・工具類", category: C.OBJECT },
  "1288": { en: "Greeting card", ja: "グリーティングカード", category: C.OBJECT },
  "1289": { en: "Curtain", ja: "カーテン", category: C.FURNITURE },
  "1290": { en: "Kettle", ja: "やかん", category: C.OBJECT },
  "1291": { en: "Bed", ja: "ベッド", category: C.FURNITURE },
  "1292": { en: "Fireplace", ja: "暖炉", category: C.FURNITURE },
  "1293": { en: "Scale", ja: "はかり", category: C.OBJECT },
  "1294": { en: "Baseball", ja: "野球ボール", category: C.SPORTS },
  "1295": { en: "Insect", ja: "昆虫", category: C.ANIMAL },
  "1296": { en: "Luggage", ja: "手荷物", category: C.OBJECT },
  "1297": { en: "Hair dryer", ja: "ヘアドライヤー", category: C.ELECTRONICS },
  "1298": { en: "Indoor rower", ja: "ローイングマシン", category: C.SPORTS },
  "1299": { en: "Food processor", ja: "フードプロセッサー", category: C.ELECTRONICS },
  "1300": { en: "Jewellery", ja: "宝飾品", category: C.CLOTHING },
  "1301": { en: "Refrigerator", ja: "冷蔵庫", category: C.ELECTRONICS },
  "1302": { en: "Wood-burning stove", ja: "薪ストーブ", category: C.FURNITURE },
  "1303": { en: "Punching bag", ja: "サンドバッグ", category: C.SPORTS },
  "1304": { en: "Deep fryer", ja: "フライヤー", category: C.ELECTRONICS },
  "1305": { en: "Common fig", ja: "いちじく", category: C.FOOD },
  "1306": { en: "Cocktail shaker", ja: "カクテルシェーカー", category: C.OBJECT },
  "1307": { en: "Jaguar", ja: "ジャガー", category: C.ANIMAL },
  "1308": { en: "Golf ball", ja: "ゴルフボール", category: C.SPORTS },
  "1309": { en: "Wireless router", ja: "無線ルーター", category: C.ELECTRONICS },
  "1310": { en: "Alarm clock", ja: "目覚まし時計", category: C.OBJECT },
  "1311": { en: "Filing cabinet", ja: "ファイルキャビネット", category: C.FURNITURE },
  "1312": { en: "Artichoke", ja: "アーティチョーク", category: C.FOOD },
  "1313": { en: "Outerwear", ja: "上着", category: C.CLOTHING },
  "1314": { en: "Cufflink", ja: "カフスボタン", category: C.CLOTHING },
  "1315": { en: "Motorcycle", ja: "オートバイ", category: C.VEHICLE },
  "1316": { en: "Table", ja: "テーブル", category: C.FURNITURE },
  "1317": { en: "Tableware", ja: "食器", category: C.OBJECT },
  "1318": { en: "Kangaroo", ja: "カンガルー", category: C.ANIMAL },
  "1319": { en: "Koala", ja: "コアラ", category: C.ANIMAL },
  "1320": { en: "Knife", ja: "ナイフ", category: C.OBJECT },
  "1321": { en: "Bottle", ja: "ボトル・瓶", category: C.OBJECT },
  "1322": { en: "Bottle opener", ja: "栓抜き", category: C.OBJECT },
  "1323": { en: "Electric toothbrush", ja: "電動歯ブラシ", category: C.ELECTRONICS },
  "1324": { en: "Lynx", ja: "オオヤマネコ", category: C.ANIMAL },
  "1325": { en: "Receipt", ja: "レシート", category: C.OBJECT },
  "1326": { en: "Lighthouse", ja: "灯台", category: C.PLACE },
  "1327": { en: "Dumbbell", ja: "ダンベル", category: C.SPORTS },
  "1328": { en: "Bowl", ja: "ボウル・どんぶり", category: C.OBJECT },
  "1329": { en: "Lizard", ja: "トカゲ", category: C.ANIMAL },
  "1330": { en: "Head-mounted display", ja: "ヘッドマウントディスプレイ", category: C.ELECTRONICS },
  "1331": { en: "Lego", ja: "ブロック玩具", category: C.OBJECT },
  "1332": { en: "Check", ja: "小切手", category: C.OBJECT },
  "1333": { en: "Billiard table", ja: "ビリヤード台", category: C.SPORTS },
  "1334": { en: "Mouse", ja: "マウス（ネズミ／パソコン）", category: C.OBJECT },
  "1335": { en: "Swim cap", ja: "水泳帽", category: C.CLOTHING },
  "1336": { en: "Frying pan", ja: "フライパン", category: C.OBJECT },
  "1337": { en: "Snowplow", ja: "除雪車", category: C.VEHICLE },
  "1338": { en: "Bathroom cabinet", ja: "洗面所の戸棚", category: C.FURNITURE },
  "1339": { en: "Bust", ja: "胸像", category: C.ARTS },
  "1340": { en: "Waffle iron", ja: "ワッフルメーカー", category: C.ELECTRONICS },
  "1341": { en: "Milk", ja: "牛乳", category: C.FOOD },
  "1342": { en: "Ring binder", ja: "リングバインダー", category: C.OBJECT },
  "1343": { en: "Plate", ja: "皿", category: C.OBJECT },
  "1344": { en: "Mobile phone", ja: "携帯電話", category: C.ELECTRONICS },
  "1345": { en: "Baked goods", ja: "焼き菓子・パン", category: C.FOOD },
  "1346": { en: "Mushroom", ja: "きのこ", category: C.PLANT },
  "1347": { en: "Crutch", ja: "松葉づえ", category: C.OBJECT },
  "1348": { en: "Mirror", ja: "鏡", category: C.FURNITURE },
  "1349": { en: "Pitcher", ja: "水差し（ピッチャー）", category: C.OBJECT },
  "1350": { en: "Lifejacket", ja: "救命胴衣", category: C.CLOTHING },
  "1351": { en: "Pencil case", ja: "筆箱", category: C.OBJECT },
  "1352": { en: "Sweatpants", ja: "スウェットパンツ", category: C.CLOTHING },
  "1353": { en: "Musical keyboard", ja: "鍵盤楽器", category: C.ARTS },
  "1354": { en: "Scoreboard", ja: "スコアボード", category: C.SPORTS },
  "1355": { en: "Briefcase", ja: "ブリーフケース", category: C.OBJECT },
  "1356": { en: "Kitchen knife", ja: "包丁", category: C.OBJECT },
  "1357": { en: "Magazine", ja: "雑誌", category: C.OBJECT },
  "1358": { en: "Table tennis racket", ja: "卓球のラケット", category: C.SPORTS },
  "1359": { en: "Portable media player", ja: "携帯音楽プレーヤー", category: C.ELECTRONICS },
  "1360": { en: "Hoodie", ja: "パーカー", category: C.CLOTHING },
  "1361": { en: "Nail", ja: "釘", category: C.OBJECT },
  "1362": { en: "Tennis ball", ja: "テニスボール", category: C.SPORTS },
  "1363": { en: "Oboe", ja: "オーボエ", category: C.ARTS },
  "1364": { en: "Chest of drawers", ja: "たんす", category: C.FURNITURE },
  "1365": { en: "Ostrich", ja: "ダチョウ", category: C.ANIMAL },
  "1366": { en: "Painting", ja: "絵画", category: C.ARTS },
  "1367": { en: "Piano", ja: "ピアノ", category: C.ARTS },
  "1368": { en: "Playing card", ja: "トランプ", category: C.OBJECT },
  "1369": { en: "Plant", ja: "植物", category: C.PLANT },
  "1370": { en: "Passport", ja: "パスポート", category: C.OBJECT },
  "1371": { en: "Potato", ja: "じゃがいも", category: C.FOOD },
  "1372": { en: "Pasta", ja: "パスタ", category: C.FOOD },
  "1373": { en: "Penguin", ja: "ペンギン", category: C.ANIMAL },
  "1374": { en: "Pumpkin", ja: "かぼちゃ", category: C.FOOD },
  "1375": { en: "Pear", ja: "洋なし", category: C.FOOD },
  "1376": { en: "Infant bed", ja: "ベビーベッド", category: C.FURNITURE },
  "1377": { en: "Polar bear", ja: "ホッキョクグマ", category: C.ANIMAL },
  "1378": { en: "Mixer", ja: "ハンドミキサー", category: C.ELECTRONICS },
  "1379": { en: "Cupboard", ja: "食器棚", category: C.FURNITURE },
  "1380": { en: "Jacuzzi", ja: "ジャグジー", category: C.FURNITURE },
  "1381": { en: "Pizza", ja: "ピザ", category: C.FOOD },
  "1382": { en: "Pig", ja: "ブタ", category: C.ANIMAL },
  "1383": { en: "Digital clock", ja: "デジタル時計", category: C.ELECTRONICS },
  "1384": { en: "Snowboard", ja: "スノーボード", category: C.SPORTS },
  "1385": { en: "Skateboard", ja: "スケートボード", category: C.SPORTS },
  "1386": { en: "Rifle", ja: "ライフル", category: C.OBJECT },
  "1387": { en: "Lipstick", ja: "口紅", category: C.OBJECT },
  "1388": { en: "Raven", ja: "カラス", category: C.ANIMAL },
  "1389": { en: "High heels", ja: "ハイヒール", category: C.CLOTHING },
  "1390": { en: "Red panda", ja: "レッサーパンダ", category: C.ANIMAL },
  "1391": { en: "Rabbit", ja: "ウサギ", category: C.ANIMAL },
  "1392": { en: "Sculpture", ja: "彫刻", category: C.ARTS },
  "1393": { en: "Saxophone", ja: "サックス", category: C.ARTS },
  "1394": { en: "Shotgun", ja: "散弾銃", category: C.OBJECT },
  "1395": { en: "Submarine sandwich", ja: "サブマリンサンド", category: C.FOOD },
  "1396": { en: "Ship", ja: "船", category: C.VEHICLE },
  "1397": { en: "Shoe", ja: "靴", category: C.CLOTHING },
  "1398": { en: "Sword", ja: "剣・刀", category: C.OBJECT },
  "1399": { en: "Picture frame", ja: "額縁", category: C.OBJECT },
  "1400": { en: "Sushi", ja: "寿司", category: C.FOOD },
  "1401": { en: "Loveseat", ja: "二人掛けソファ", category: C.FURNITURE },
  "1402": { en: "Ski", ja: "スキー板", category: C.SPORTS },
  "1403": { en: "Squirrel", ja: "リス", category: C.ANIMAL },
  "1404": { en: "Tripod", ja: "三脚", category: C.OBJECT },
  "1405": { en: "Stethoscope", ja: "聴診器", category: C.OBJECT },
  "1406": { en: "Submarine", ja: "潜水艦", category: C.VEHICLE },
  "1407": { en: "Scorpion", ja: "サソリ", category: C.ANIMAL },
  "1408": { en: "Segway", ja: "セグウェイ", category: C.VEHICLE },
  "1409": { en: "Weight training bench", ja: "トレーニングベンチ", category: C.SPORTS },
  "1410": { en: "Snake", ja: "ヘビ", category: C.ANIMAL },
  "1411": { en: "Coffee table", ja: "ローテーブル", category: C.FURNITURE },
  "1412": { en: "Video game console", ja: "ゲーム機", category: C.ELECTRONICS },
  "1413": { en: "Sheep", ja: "ヒツジ", category: C.ANIMAL },
  "1414": { en: "Single-lens reflex camera", ja: "一眼レフカメラ", category: C.ELECTRONICS },
  "1415": { en: "Television", ja: "テレビ", category: C.ELECTRONICS },
  "1416": { en: "Trombone", ja: "トロンボーン", category: C.ARTS },
  "1417": { en: "Tank", ja: "戦車", category: C.VEHICLE },
  "1418": { en: "Taco", ja: "タコス", category: C.FOOD },
  "1419": { en: "Telephone", ja: "電話機", category: C.ELECTRONICS },
  "1420": { en: "Torch", ja: "たいまつ", category: C.OBJECT },
  "1421": { en: "Tiger", ja: "トラ", category: C.ANIMAL },
  "1422": { en: "Strawberry", ja: "いちご", category: C.FOOD },
  "1423": { en: "Trumpet", ja: "トランペット", category: C.ARTS },
  "1424": { en: "Tomato", ja: "トマト", category: C.FOOD },
  "1425": { en: "Train", ja: "電車・列車", category: C.VEHICLE },
  "1426": { en: "Pants", ja: "ズボン", category: C.CLOTHING },
  "1427": { en: "cup", ja: "カップ", category: C.OBJECT },
  "1428": { en: "Football helmet", ja: "アメフト用ヘルメット", category: C.SPORTS },
  "1429": { en: "Truck", ja: "トラック", category: C.VEHICLE },
  "1430": { en: "Measuring cup", ja: "計量カップ", category: C.OBJECT },
  "1431": { en: "Coffeemaker", ja: "コーヒーメーカー", category: C.ELECTRONICS },
  "1432": { en: "Violin", ja: "バイオリン", category: C.ARTS },
  "1433": { en: "Vacuum", ja: "掃除機", category: C.ELECTRONICS },
  "1434": { en: "Handbag", ja: "ハンドバッグ", category: C.CLOTHING },
  "1435": { en: "Weapon", ja: "武器", category: C.OBJECT },
  "1436": { en: "Wheel", ja: "車輪", category: C.VEHICLE },
  "1437": { en: "Worm", ja: "ミミズ", category: C.ANIMAL },
  "1438": { en: "Wok", ja: "中華鍋", category: C.OBJECT },
  "1439": { en: "Whale", ja: "クジラ", category: C.ANIMAL },
  "1440": { en: "Zebra", ja: "シマウマ", category: C.ANIMAL },
  "1441": { en: "Carseat", ja: "チャイルドシート", category: C.VEHICLE },
  "1442": { en: "Jug", ja: "水差し", category: C.OBJECT },
  "1443": { en: "Light fixture", ja: "照明器具", category: C.FURNITURE },
  "1444": { en: "Pizza cutter", ja: "ピザカッター", category: C.OBJECT },
  "1445": { en: "Cream", ja: "クリーム", category: C.FOOD },
  "1446": { en: "Monkey", ja: "サル", category: C.ANIMAL },
  "1447": { en: "Lion", ja: "ライオン", category: C.ANIMAL },
  "1448": { en: "Bread", ja: "パン", category: C.FOOD },
  "1449": { en: "Chicken", ja: "ニワトリ", category: C.ANIMAL },
  "1450": { en: "Eagle", ja: "ワシ", category: C.ANIMAL },
  "1451": { en: "Helicopter", ja: "ヘリコプター", category: C.VEHICLE },
  "1452": { en: "Owl", ja: "フクロウ", category: C.ANIMAL },
  "1453": { en: "Duck", ja: "カモ・アヒル", category: C.ANIMAL },
  "1454": { en: "Turtle", ja: "カメ", category: C.ANIMAL },
  "1455": { en: "Hippopotamus", ja: "カバ", category: C.ANIMAL },
  "1456": { en: "Crocodile", ja: "ワニ", category: C.ANIMAL },
  "1457": { en: "Toilet", ja: "トイレ（便器）", category: C.FURNITURE },
  "1458": { en: "Garden gnome", ja: "庭の小人の置物", category: C.OBJECT },
  "1459": { en: "Toilet paper", ja: "トイレットペーパー", category: C.OBJECT },
  "1460": { en: "Squid", ja: "イカ", category: C.ANIMAL },
  "1461": { en: "Clothing", ja: "衣服", category: C.CLOTHING },
  "1462": { en: "Footwear", ja: "履物", category: C.CLOTHING },
  "1463": { en: "Lemon", ja: "レモン", category: C.FOOD },
  "1464": { en: "Sneakers", ja: "スニーカー", category: C.CLOTHING },
  "1465": { en: "Spider", ja: "クモ", category: C.ANIMAL },
  "1466": { en: "Deer", ja: "シカ", category: C.ANIMAL },
  "1467": { en: "Ring", ja: "指輪", category: C.CLOTHING },
  "1468": { en: "Frog", ja: "カエル", category: C.ANIMAL },
  "1469": { en: "Banana", ja: "バナナ", category: C.FOOD },
  "1470": { en: "Rocket", ja: "ロケット", category: C.SPACE },
  "1471": { en: "Wine glass", ja: "ワイングラス", category: C.OBJECT },
  "1472": { en: "Oyster", ja: "カキ（貝）", category: C.FOOD },
  "1473": { en: "Chisel", ja: "のみ（工具）", category: C.OBJECT },
  "1474": { en: "Ant", ja: "アリ", category: C.ANIMAL },
  "1475": { en: "Countertop", ja: "調理台", category: C.FURNITURE },
  "1476": { en: "Optical disc", ja: "光ディスク", category: C.ELECTRONICS },
  "1477": { en: "Tablet computer", ja: "タブレット", category: C.ELECTRONICS },
  "1478": { en: "Waste container", ja: "ごみ箱", category: C.OBJECT },
  "1479": { en: "Electronic device", ja: "電子機器", category: C.ELECTRONICS },
  "1480": { en: "Book", ja: "本", category: C.OBJECT },
  "1481": { en: "Elephant", ja: "ゾウ", category: C.ANIMAL },
  "1482": { en: "Robotic vacuum cleaner", ja: "ロボット掃除機", category: C.ELECTRONICS },
  "1483": { en: "Shark", ja: "サメ", category: C.ANIMAL },
  "1484": { en: "Toy block", ja: "積み木", category: C.OBJECT },
  "1485": { en: "Candle", ja: "ろうそく", category: C.OBJECT },
  "1486": { en: "Leopard", ja: "ヒョウ", category: C.ANIMAL },
  "1487": { en: "Axe", ja: "斧", category: C.OBJECT },
  "1488": { en: "Hand dryer", ja: "ハンドドライヤー", category: C.ELECTRONICS },
  "1489": { en: "Soap dispenser", ja: "ソープディスペンサー", category: C.OBJECT },
  "1490": { en: "Porcupine", ja: "ヤマアラシ", category: C.ANIMAL },
  "1491": { en: "Flower", ja: "花", category: C.PLANT },
  "1492": { en: "Furniture", ja: "家具", category: C.FURNITURE },
  "1493": { en: "Canary", ja: "カナリア", category: C.ANIMAL },
  "1494": { en: "Cheetah", ja: "チーター", category: C.ANIMAL },
  "1495": { en: "Hamburger", ja: "ハンバーガー", category: C.FOOD },
  "1496": { en: "Satchel", ja: "ショルダーバッグ", category: C.CLOTHING },
  "1497": { en: "Loudspeaker", ja: "スピーカー", category: C.ELECTRONICS },
  "1498": { en: "Building", ja: "建物", category: C.PLACE },
  "1499": { en: "Fish", ja: "魚", category: C.ANIMAL },
  "1500": { en: "Lobster", ja: "ロブスター", category: C.ANIMAL },
  "1501": { en: "Asparagus", ja: "アスパラガス", category: C.FOOD },
  "1502": { en: "Hedgehog", ja: "ハリネズミ", category: C.ANIMAL },
  "1503": { en: "Airplane", ja: "飛行機", category: C.VEHICLE },
  "1504": { en: "Spoon", ja: "スプーン", category: C.OBJECT },
  "1505": { en: "Otter", ja: "カワウソ", category: C.ANIMAL },
  "1506": { en: "Bull", ja: "雄牛", category: C.ANIMAL },
  "1507": { en: "Underpants", ja: "下着（パンツ）", category: C.CLOTHING },
  "1508": { en: "Projector", ja: "プロジェクター", category: C.ELECTRONICS },
  "1509": { en: "Bench", ja: "ベンチ", category: C.FURNITURE },
  "1510": { en: "Driver's license", ja: "運転免許証", category: C.OBJECT },
  "1511": { en: "Ice cream", ja: "アイスクリーム", category: C.FOOD },
  "1512": { en: "Caterpillar", ja: "毛虫・イモムシ", category: C.ANIMAL },
  "1513": { en: "Butterfly", ja: "チョウ", category: C.ANIMAL },
  "1514": { en: "Parachute", ja: "パラシュート", category: C.SPORTS },
  "1515": { en: "Orange", ja: "オレンジ", category: C.FOOD },
  "1516": { en: "Antelope", ja: "レイヨウ", category: C.ANIMAL },
  "1517": { en: "Beaker", ja: "ビーカー", category: C.OBJECT },
  "1518": { en: "Romper", ja: "ロンパース", category: C.CLOTHING },
  "1519": { en: "Window", ja: "窓", category: C.PLACE },
  "1520": { en: "Castle", ja: "城", category: C.PLACE },
  "1521": { en: "Jellyfish", ja: "クラゲ", category: C.ANIMAL },
  "1522": { en: "Moths and butterflies", ja: "ガ・チョウ", category: C.ANIMAL },
  "1523": { en: "Goose", ja: "ガチョウ", category: C.ANIMAL },
  "1524": { en: "Mule", ja: "ラバ", category: C.ANIMAL },
  "1525": { en: "Swan", ja: "白鳥", category: C.ANIMAL },
  "1526": { en: "Peach", ja: "桃", category: C.FOOD },
  "1527": { en: "Coconut", ja: "ココナッツ", category: C.FOOD },
  "1528": { en: "Scooter", ja: "スクーター・キックボード", category: C.VEHICLE },
  "1529": { en: "Soccer ball", ja: "サッカーボール", category: C.SPORTS },
  "1530": { en: "Raccoon", ja: "アライグマ", category: C.ANIMAL },
  "1531": { en: "Fork", ja: "フォーク", category: C.OBJECT },
  "1532": { en: "Lamp", ja: "ランプ・電気スタンド", category: C.FURNITURE },
  "1533": { en: "Camera", ja: "カメラ", category: C.ELECTRONICS },
  "1534": { en: "Squash", ja: "カボチャ類（スクワッシュ）", category: C.FOOD },
  "1535": { en: "Racket", ja: "ラケット", category: C.SPORTS },
  "1536": { en: "Vegetable", ja: "野菜", category: C.FOOD },
  "1537": { en: "Diaper", ja: "おむつ", category: C.CLOTHING },
  "1538": { en: "Unicycle", ja: "一輪車", category: C.VEHICLE },
  "1539": { en: "Falcon", ja: "ハヤブサ", category: C.ANIMAL },
  "1540": { en: "Apron", ja: "エプロン", category: C.CLOTHING },
  "1541": { en: "Chime", ja: "チャイム・風鈴", category: C.ARTS },
  "1542": { en: "Snail", ja: "カタツムリ", category: C.ANIMAL },
  "1543": { en: "Cabbage", ja: "キャベツ", category: C.FOOD },
  "1544": { en: "Carrot", ja: "にんじん", category: C.FOOD },
  "1545": { en: "Mango", ja: "マンゴー", category: C.FOOD },
  "1546": { en: "Jeans", ja: "ジーンズ", category: C.CLOTHING },
  "1547": { en: "Flowerpot", ja: "植木鉢", category: C.OBJECT },
  "1548": { en: "Pineapple", ja: "パイナップル", category: C.FOOD },
  "1549": { en: "Stool", ja: "スツール", category: C.FURNITURE },
  "1550": { en: "Basketball", ja: "バスケットボール", category: C.SPORTS },
  "1551": { en: "Envelope", ja: "封筒", category: C.OBJECT },
  "1552": { en: "Cake", ja: "ケーキ", category: C.FOOD },
  "1553": { en: "Dragonfly", ja: "トンボ", category: C.ANIMAL },
  "1554": { en: "Microwave oven", ja: "電子レンジ", category: C.ELECTRONICS },
  "1555": { en: "Honeycomb", ja: "ハチの巣", category: C.NATURE },
  "1556": { en: "Drone", ja: "ドローン", category: C.ELECTRONICS },
  "1557": { en: "Sea lion", ja: "アシカ", category: C.ANIMAL },
  "1558": { en: "Barcode", ja: "バーコード", category: C.OBJECT },
  "1559": { en: "Lady bug", ja: "テントウムシ", category: C.ANIMAL },
  "1560": { en: "Shelf", ja: "棚", category: C.FURNITURE },
  "1561": { en: "Watch", ja: "腕時計", category: C.CLOTHING },
  "1562": { en: "Candy", ja: "キャンディ・お菓子", category: C.FOOD },
  "1563": { en: "Salad", ja: "サラダ", category: C.FOOD },
  "1564": { en: "Parrot", ja: "オウム", category: C.ANIMAL },
  "1565": { en: "Handgun", ja: "拳銃", category: C.OBJECT },
  "1566": { en: "Sparrow", ja: "スズメ", category: C.ANIMAL },
  "1567": { en: "Van", ja: "バン", category: C.VEHICLE },
  "1568": { en: "Ice skate", ja: "アイススケート靴", category: C.SPORTS },
  "1569": { en: "Grinder", ja: "グラインダー", category: C.OBJECT },
  "1570": { en: "Spice rack", ja: "スパイスラック", category: C.FURNITURE },
  "1571": { en: "Light bulb", ja: "電球", category: C.ELECTRONICS },
  "1572": { en: "Toy vehicle", ja: "おもちゃの乗り物", category: C.OBJECT },
  "1573": { en: "Corded phone", ja: "固定電話", category: C.ELECTRONICS },
  "1574": { en: "Dartboard", ja: "ダーツボード", category: C.SPORTS },
  "1575": { en: "Tennis racket", ja: "テニスラケット", category: C.SPORTS },
  "1576": { en: "Wall clock", ja: "掛け時計", category: C.FURNITURE },
  "1577": { en: "Serving tray", ja: "お盆", category: C.OBJECT },
  "1578": { en: "Kitchen & dining room table", ja: "ダイニングテーブル", category: C.FURNITURE },
  "1579": { en: "Dog bed", ja: "犬用ベッド", category: C.FURNITURE },
  "1580": { en: "Cake stand", ja: "ケーキスタンド", category: C.OBJECT },
  "1581": { en: "Baby carrier", ja: "抱っこひも", category: C.OBJECT },
  "1582": { en: "Facial tissue holder", ja: "ティッシュケース", category: C.OBJECT },
  "1583": { en: "Pressure cooker", ja: "圧力鍋", category: C.OBJECT },
  "1584": { en: "Shipping box", ja: "段ボール箱", category: C.OBJECT },
  "1585": { en: "Kitchen Appliance", ja: "キッチン家電", category: C.ELECTRONICS },
  "1586": { en: "Tire", ja: "タイヤ", category: C.VEHICLE },
  "1587": { en: "Ruler", ja: "定規", category: C.OBJECT },
  "1588": { en: "Luggage & bags", ja: "かばん類", category: C.OBJECT },
  "1589": { en: "Microphone", ja: "マイク", category: C.ELECTRONICS },
  "1590": { en: "Broccoli", ja: "ブロッコリー", category: C.FOOD },
  "1591": { en: "Umbrella", ja: "傘", category: C.OBJECT },
  "1592": { en: "Pastry", ja: "ペストリー", category: C.FOOD },
  "1593": { en: "Grapefruit", ja: "グレープフルーツ", category: C.FOOD },
  "1594": { en: "Eyewear", ja: "アイウェア", category: C.CLOTHING },
  "1595": { en: "Band-aid", ja: "ばんそうこう", category: C.OBJECT },
  "1596": { en: "Bell pepper", ja: "ピーマン", category: C.FOOD },
  "1597": { en: "Turkey", ja: "七面鳥", category: C.ANIMAL },
  "1598": { en: "Pomegranate", ja: "ざくろ", category: C.FOOD },
  "1599": { en: "Doughnut", ja: "ドーナツ", category: C.FOOD },
  "1600": { en: "Glasses", ja: "眼鏡", category: C.CLOTHING },
  "1601": { en: "Pen", ja: "ペン", category: C.OBJECT },
  "1602": { en: "Car", ja: "自動車", category: C.VEHICLE },
  "1603": { en: "Skunk", ja: "スカンク", category: C.ANIMAL },
  "1604": { en: "Teddy bear", ja: "テディベア", category: C.OBJECT },
  "1605": { en: "Watermelon", ja: "スイカ", category: C.FOOD },
  "1606": { en: "Cantaloupe", ja: "メロン", category: C.FOOD },
  "1607": { en: "Dishwasher", ja: "食器洗い機", category: C.ELECTRONICS },
  "1608": { en: "Flute", ja: "フルート", category: C.ARTS },
  "1609": { en: "Sandwich", ja: "サンドイッチ", category: C.FOOD },
  "1610": { en: "Bladeless fan", ja: "羽根のない扇風機", category: C.ELECTRONICS },
  "1611": { en: "Shrimp", ja: "エビ", category: C.FOOD },
  "1612": { en: "Sewing machine", ja: "ミシン", category: C.ELECTRONICS },
  "1613": { en: "Binoculars", ja: "双眼鏡", category: C.OBJECT },
  "1614": { en: "Rays and skates", ja: "エイ", category: C.ANIMAL },
  "1615": { en: "Accordion", ja: "アコーディオン", category: C.ARTS },
  "1616": { en: "Crab", ja: "カニ", category: C.ANIMAL },
  "1617": { en: "Bag", ja: "かばん", category: C.CLOTHING },
  "1618": { en: "Crown", ja: "王冠", category: C.CLOTHING },
  "1619": { en: "Seahorse", ja: "タツノオトシゴ", category: C.ANIMAL },
  "1620": { en: "Perfume", ja: "香水", category: C.OBJECT },
  "1621": { en: "Alpaca", ja: "アルパカ", category: C.ANIMAL },
  "1622": { en: "Canoe", ja: "カヌー", category: C.VEHICLE },
  "1623": { en: "Game controller", ja: "ゲームコントローラー", category: C.ELECTRONICS },
  "1624": { en: "Remote control", ja: "リモコン", category: C.ELECTRONICS },
  "1625": { en: "Wheelchair", ja: "車椅子", category: C.VEHICLE },
  "1626": { en: "Rugby ball", ja: "ラグビーボール", category: C.SPORTS },
  "1627": { en: "Armadillo", ja: "アルマジロ", category: C.ANIMAL },
  "1628": { en: "Maracas", ja: "マラカス", category: C.ARTS },
  "1629": { en: "Activity tracker", ja: "活動量計", category: C.ELECTRONICS },
  "1630": { en: "Helmet", ja: "ヘルメット", category: C.CLOTHING },
};

export const LABEL: Record<string, LabelInfo> = {
  ...Object.fromEntries(
    BASE_KEYWORD_INDEXES.flatMap((i) => {
      const info = BASE_LABEL[String(i)];
      return info ? [[String(i), info] as const] : [];
    }),
  ),
  ...OBJECT_LABEL,
};
